import {chromium} from '/opt/frankendom-shadow/repo/node_modules/playwright/index.mjs';import fs from 'node:fs';import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1400,height:785}}),report={scope:'Isolated original-rig neck repair and representative head/complexion/hair ingredients, no runtime integration/gameplay/device claim',errors:[],samples:[]};page.on('pageerror',e=>report.errors.push(e.message));
try{await page.goto('http://127.0.0.1:18926/review.html');await page.waitForFunction(()=>window.__pilot,null,{timeout:60000});
for(const [clip,phase]of [['HollowIdle',0],['HollowWalk',.25],['Attack',.34],['Guard',.15],['Hit',.35],['Death',.8]]){const s=await page.evaluate(({clip,phase})=>__pilot.sample(clip,phase),{clip,phase});report.samples.push(s);assert(s.finite&&s.maxBoneDelta<1e-12&&s.maxKnifeDelta<1e-12);await page.screenshot({path:`results/pilot-${clip}.png`});}
for(const phase of [0,.125,.25,.5,.75,.875,.999999]){const s=await page.evaluate(phase=>__pilot.sample('Hit',phase),phase);report.samples.push(s);assert(s.finite&&s.maxBoneDelta<1e-12&&s.maxKnifeDelta<1e-12);}
await page.evaluate(()=>{__pilot.sample('Guard',0);__pilot.close()});await page.screenshot({path:'results/pilot-heads.png'});
await page.evaluate(()=>__pilot.crooked());for(const[clip,phase]of[['HollowIdle',0],['HollowWalk',.25],['Hit',.35],['Death',.8]]){const s=await page.evaluate(({clip,phase})=>__pilot.sample(clip,phase),{clip,phase});report.samples.push({...s,crooked:true});assert(s.finite&&s.maxBoneDelta<1e-4&&s.maxKnifeDelta<1e-4);await page.screenshot({path:`results/crooked-${clip}.png`});}
for(const factor of [.85,1.15]){await page.evaluate(f=>__pilot.size(f),factor);for(const[clip,phase]of[['HollowWalk',.25],['Hit',.35]]){const s=await page.evaluate(({clip,phase})=>__pilot.sample(clip,phase),{clip,phase});report.samples.push({...s,crooked:true,factor});assert(s.finite&&s.maxBoneDelta<1e-4&&s.maxKnifeDelta<1e-4);await page.screenshot({path:`results/extreme-${factor}-${clip}.png`});}}
await page.setViewportSize({width:393,height:852});await page.goto('http://127.0.0.1:18926/london.html');await page.waitForFunction(()=>window.__london,null,{timeout:60000});for(const[clip,phase]of[['HollowWalk',.25],['Hit',.35],['Death',.8]]){report.samples.push(await page.evaluate(({clip,phase})=>__london.sample(clip,phase,393,852),{clip,phase}));await page.screenshot({path:`results/london-${clip}.png`});}
await page.setViewportSize({width:852,height:393});report.samples.push(await page.evaluate(()=>__london.sample('HollowWalk',.25,852,393)));await page.screenshot({path:'results/london-landscape.png'});
assert.deepEqual(report.errors,[]);console.log('REPRESENTATIVE_INGREDIENT_PILOT_PASS');}
finally{fs.writeFileSync('results/review.json',JSON.stringify(report,null,2));await browser.close();}
