import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';
import {loadGeometry} from '../../art/donor/probe.mjs';import {createActors} from '../src/actors.js';import {disposeActorSources} from '../src/actor-resources.js';import {createGame} from '../src/combat.js';
const publicRoot=new URL('../public/',import.meta.url),manifest=JSON.parse(fs.readFileSync(new URL('assets/manifest-hollow.json',publicRoot)));
test('all eighteen geometry pipelines compose on native rigs and reset safely (white texel shim; not pigment proof)',async t=>{
 const prior=globalThis.document;globalThis.document={createElement:()=>({getContext:()=>({createRadialGradient:()=>({addColorStop(){}}),fillRect(){},drawImage(){},getImageData:()=>({data:new Uint8Array([255,255,255,255])})})})};t.after(()=>{if(prior===undefined)delete globalThis.document;else globalThis.document=prior;});
 const models=new Map();for(const[name,description]of Object.entries(manifest.models))models.set(name,{description,gltf:await loadGeometry(fs.readFileSync(new URL('assets/'+description.url,publicRoot))),equipment:description.equipment?await loadGeometry(fs.readFileSync(new URL('assets/'+description.equipment.url,publicRoot))):null});
 // The offline geometry parser deliberately omits images; pigment is checked by the compiled native browser tour.
 models.get('original-dog').gltf.scene.traverse(m=>{if(m.isSkinnedMesh&&m.material.name==='Weathered brindle coat')m.material.map=new T.Texture({width:1,height:1});});
 const sources=new Set([...models.values()].flatMap(m=>[m.gltf,m.equipment].filter(Boolean))),world={areaId:'westminster',layout:{characterScale:1.265},spawn:{x:0,z:-6},move:(p,d)=>({x:p.x+d.x,z:p.z+d.z}),lineClear:()=>true,geometry:{clear:()=>true,lineClear:()=>true},toRender:(p,h=0)=>new T.Vector3(p.x,h,-p.z)},actors=createActors(new T.Scene(),world,{manifest,models,dispose:()=>disposeActorSources(sources)},{visualScale:1.3225});t.after(()=>actors.dispose());
 const encounter={id:'hollow-scavengers',character:{rig:'hollow-scavenger',weapon:'knife',contactRig:'hero',bodyScale:1}},seen=new Set();
 for(const cycle of ['A','B'])for(const area of ['westminster','east','south']){actors.reset();world.areaId=area;const g=createGame(world,{pilot:'donor-knife',encounter,rat:true,dog:true,roach:true,drone:true,animalVariants:true,animalCycle:cycle,areaResidents:true,openingGroup:false});actors.update(g,0);for(const e of g.enemies.filter(e=>e.animalRecipe)){seen.add(e.animalRecipe);const v=actors.views.get(e.id);assert.equal(v.animalAppearanceId,e.animalRecipe);assert(Math.abs(v.root.scale.x-1.6729625*(e.rig==='original-dog'?2:3))<1e-9);assert.equal(v.motion.currentClip,e.rig==='original-rat'?'rat_idle':e.rig==='original-dog'?'dog_idle':'roach_idle');if(['dog-gaunt-hound','dog-stocky-yard'].includes(e.animalRecipe))assert.equal(v.bodyShape.recipe.id,e.animalRecipe);}}
 assert.equal(seen.size,18);actors.reset();assert.equal(actors.views.size,0);
});
