import test from 'node:test';import assert from 'node:assert/strict';import {createGame,stepGame,attack,receiveHit} from '../src/combat.js';import {travelTo} from '../src/travel.js';
const opts=cycle=>({pilot:'donor-knife',encounter:{id:'hollow-scavengers',character:{rig:'hollow-scavenger',weapon:'knife',contactRig:'hero',bodyScale:1}},animalVariants:true,animalCycle:cycle,areaResidents:true,openingGroup:false,rat:true,dog:true,roach:true,drone:true});
function fixture(area='east',cycle='B'){const world={areaId:area,layout:{characterScale:1.265},spawn:{x:0,z:-6},move:(p,d)=>({x:p.x+d.x,z:p.z+d.z}),lineClear:()=>true,async loadArea(a){this.areaId=a;return{x:0,z:-6}}};return createGame(world,opts(cycle));}
const ticks=(g,n,intent={})=>{for(let i=0;i<n;i++)stepGame(g,intent)};
function solo(g,key,gap=1){const e=g.enemies.find(e=>e.placementKey===key);assert(e);g.enemies=[e];g.player.pos={x:e.pos.x,z:e.pos.z-gap};g.ratContact={capture:()=>({}),calf:()=>({...e.pos,y:.05}),foot:()=>({...e.pos,y:.05}),hit:()=>false};return e;}
test('five bindings initialize once; Pack/East9 exclusion and081 Roach territory retained',()=>{const east=fixture(),stocky=east.enemies.find(e=>e.animalRecipe==='dog-stocky-yard');assert.equal(stocky.moveSpeed,2.21);assert.equal(stocky.recoveryDelay,.15);assert.equal(stocky.hp,30);assert.equal(stocky.radius,1.54);assert.equal(east.enemies.find(e=>e.animalRecipe==='dog-gaunt-hound').animalRole.intent.retreatSeconds,.55);assert.equal(east.enemies.find(e=>e.animalRecipe==='roach-nest-guard').residentIntent.homeLeash,5);const south=fixture('south');assert.equal(south.enemies.find(e=>e.animalRecipe==='rat-nest-defender').residentIntent.homeLeash,5);assert.equal(south.enemies.find(e=>e.animalRecipe==='roach-skitter').moveSpeed,1.9800000000000002);const a=fixture('east','A'),pack=a.enemies.find(e=>e.animalRecipe==='dog-pack-chaser');assert.equal(pack.residentIntent.companionDistance,6);assert.equal(pack.animalRole,undefined);assert.equal(a.enemies.find(e=>e.placementKey==='east-roamer-9').moveSpeed,2.6);assert.equal(a.enemies.length,10);});
test('actual native bite END records completion and next tick requests retreat; blocked hold',()=>{const g=fixture(),e=solo(g,'east-roamer-7');stepGame(g,{});assert(e.swing?.native);const end=e.swing.end;while(g.time<end-1e-8)stepGame(g,{});assert.deepEqual(e.completedAttack,{endedAt:end,uninterrupted:true});const pos={...e.pos};stepGame(g,{});assert(e.pos.z>pos.z,'withdraw away from player');g.world.move=p=>({...p});const blocked={...e.pos};stepGame(g,{});assert.deepEqual(e.pos,blocked);assert.equal(e.swing,null);});
test('same-tick actual damage resolution suppresses natural-end retreat record',()=>{const g=fixture(),e=solo(g,'east-roamer-7');stepGame(g,{});const end=e.swing.end;while(g.time<end-20/60-1e-8)stepGame(g,{});assert(attack(g,'slash',{x:0,z:1}));g.ratContact.hit=(a)=>a.id===0;while(g.time<end-1e-8)stepGame(g,{});assert.equal(e.hp,10);assert(e.staggerUntil>g.time);assert.equal(e.completedAttack,null);assert.equal(e.swing,null);});
test('controlled actual parry API cancels prior completion rather than grants normal-END',()=>{const g=fixture(),e=solo(g,'east-roamer-7');e.completedAttack={endedAt:0,uninterrupted:true};stepGame(g,{guard:true,guardPressed:true,aim:{x:0,z:1}});receiveHit(g,{amount:4,origin:{...e.pos},attacker:e,block:true,parry:true,moveId:'light_right'});assert(g.events.some(x=>x.type==='parry'));assert.equal(e.completedAttack,null);assert.equal(e.swing,null);});
test('Stocky native bite adds .15 recovery once; native clip ticks unchanged',()=>{const g=fixture(),e=solo(g,'east-roamer-9');stepGame(g,{});assert(e.swing);assert.deepEqual(e.swing.timing,{windup:18,active:6,recovery:24});assert(Math.abs(e.ready-e.swing.end-.15)<1e-9);assert.equal(e.swing.def.damage,8);});
test('Skitter actual wake/rhythm pauses approach without cancelling native swing',()=>{const g=fixture('south'),e=solo(g,'south-roamer-2',5);stepGame(g,{});assert.equal(e.wokeAt,g.time);ticks(g,30);const pos={...e.pos};stepGame(g,{});assert.deepEqual(e.pos,pos);g.player.pos={x:e.pos.x,z:e.pos.z-1};while(!e.swing&&g.time<2)stepGame(g,{});assert(e.swing?.native);const s=e.swing;ticks(g,10);assert.equal(e.swing,s);assert.equal(e.swing.clip,'roach_bite_scaled');});
test('actual travel cancels pending bite/retreat, parked elapsed shifts wake once',async()=>{const g=fixture(),e=solo(g,'east-roamer-7');stepGame(g,{});e.completedAttack={endedAt:0,uninterrupted:true};const woke=e.wokeAt,parked=g.time;await travelTo(g,{areaId:'south'});assert.equal(e.completedAttack,null);assert.equal(e.swing,null);ticks(g,15);const elapsed=g.time-parked;await travelTo(g,{areaId:'east'});assert(Math.abs(e.wokeAt-woke-elapsed)<1e-8);assert.equal(e.completedAttack,null);assert.equal(e.moveSpeed,2.1);});

test('actual confirmed death clears transient role clocks, ordinary reward/kill stays exactlyonce',()=>{const g=fixture(),e=solo(g,'east-roamer-7');g.ratContact.hit=a=>a.id===0;assert(attack(g,'slash',{x:0,z:1}));ticks(g,54);assert.equal(e.hp,10);e.completedAttack={endedAt:g.time,uninterrupted:true};assert(attack(g,'slash',{x:0,z:1}));ticks(g,26);assert.equal(e.hp,0);assert.equal(e.completedAttack,null);assert.equal(e.wokeAt,null);assert.equal(g.kills,1);ticks(g,2);assert.equal(g.kills,1);});
