import test from 'node:test';import assert from 'node:assert/strict';import {resolveBoundAnimalRole,nativeAttackCompletion} from '../src/animal-role-bindings.js';import {canWakeResident,recoveryMovement,approachRhythm} from '../src/creature-behaviour-intents.js';import {territoryHomeStep} from '../src/roach-territory.js';
const caps=['home','lineOfSight','completedAttack','collisionMove','wakeTime','nativeLocomotion'],row=(recipe,rig,key,area,speed)=>({id:7,animalRecipe:recipe,rig,placementKey:key,areaId:area,hp:20,moveSpeed:speed,recoveryDelay:0,home:{x:0,z:0},pos:{x:1,z:0}}),resolve=e=>resolveBoundAnimalRole(e,{areaId:e.areaId,animalCycle:'B',behaviourCapabilities:caps});
const examples=[row('rat-sewer','original-rat','east-roamer-7','east',2.1),row('rat-nest-defender','original-rat','south-roamer-3','south',2.1),row('dog-gaunt-hound','original-dog','east-roamer-4','east',2.6),row('dog-stocky-yard','original-dog','east-roamer-9','east',2.6),row('roach-skitter','original-roach','south-roamer-2','south',1.8)];
test('five exact079 bindings resolve once without actor writes, damage or HP parameters',()=>{for(const e of examples){const before=JSON.stringify(e),r=resolve(e);assert.equal(r.recipeId,e.animalRecipe);assert.deepEqual(resolve(e),r);assert.equal(JSON.stringify(e),before);assert.deepEqual(Object.keys(r.parameters).sort(),['moveSpeed','recoveryDelay']);}assert.equal(resolve(examples[3]).parameters.moveSpeed,2.21);assert.equal(resolve(examples[3]).parameters.recoveryDelay,.15);assert.equal(resolve(examples[4]).parameters.moveSpeed,1.9800000000000002);});
test('ordinary other-cycle/species/key/dead/malformed residents remain excluded; capabilities must exist',()=>{const e=examples[2];for(const patch of [{animalRecipe:'dog-pack-chaser'},{rig:'low-hover-drone'},{rig:'hollow-scavenger'},{placementKey:'east-roamer-6'},{hp:0},{home:null},{pos:{x:Infinity,z:0}}])assert.equal(resolve({...e,...patch}),null);assert.equal(resolveBoundAnimalRole(e,{areaId:'south',animalCycle:'B',behaviourCapabilities:caps}),null);assert.equal(resolveBoundAnimalRole(e,{areaId:'east',animalCycle:'A',behaviourCapabilities:caps}),null);assert(resolveBoundAnimalRole(examples[0],{areaId:'east',animalCycle:'A',behaviourCapabilities:caps}));assert.throws(()=>resolveBoundAnimalRole(e,{areaId:'east',animalCycle:'B'}),/Unsupported/);});
test('retreat requires actual normal native END, never attack start/hurt/cancel/human/player',()=>{const s={native:true,action:'bite',clip:'dog_bite_scaled',start:1,end:1.8},o={reason:'normal',time:1.8,alive:true};assert.deepEqual(nativeAttackCompletion(s,o),{endedAt:1.8,uninterrupted:true});for(const patch of [{reason:'hurt'},{reason:'cancel'},{time:1.7},{alive:false},{hurt:true}])assert.equal(nativeAttackCompletion(s,{...o,...patch}),null);for(const patch of [{native:false},{action:'slash'},{clip:'Heavy'},{end:NaN}])assert.equal(nativeAttackCompletion({...s,...patch},o),null);});
test('rat and gaunt dog .55s withdrawal preserve native swings and blocked holds',()=>{for(const e of [examples[0],examples[2]]){const p=resolve(e).intent,o={alive:true,alerted:true,time:2.2,distance:1,retreatPathClear:true,completedAttack:{endedAt:2,uninterrupted:true}};assert.equal(recoveryMovement(p,o),'withdraw');assert.equal(recoveryMovement(p,{...o,time:2.55}),'native');assert.equal(recoveryMovement(p,{...o,retreatPathClear:false}),'hold');for(const patch of [{hurt:true},{swingActive:true},{alive:false}])assert.equal(recoveryMovement(p,{...o,...patch}),'native');assert.equal(recoveryMovement(p,{...o,completedAttack:null}),'native');}});
test('RatNest uses existing territory4/5 with native-authority return and blocked hold',()=>{const p=resolve(examples[1]).intent,w={alive:true,playerAlive:true,sameArea:true,lineClear:true,distance:4,playerHomeDistance:5};assert(canWakeResident(p,w));assert.equal(canWakeResident(p,{...w,distance:4.00001}),false);const o={alive:true,alerted:true,playerHomeDistance:5.1,homeDistance:2};assert.deepEqual(territoryHomeStep(p,o),{alerted:false,returning:true,action:'return'});assert.equal(territoryHomeStep(p,{...o,returnPathClear:false}).action,'hold');});
test('Skitter .45/.35 rhythm only gates approach/new bite; active swing/hurt/death never paused',()=>{const p=resolve(examples[4]).intent,o={alive:true,alerted:true,wokeAt:0,time:.449999};assert.equal(approachRhythm(p,o),'native');assert.equal(approachRhythm(p,{...o,time:.45}),'hold');assert.equal(approachRhythm(p,{...o,time:.79999}),'hold');assert.equal(approachRhythm(p,{...o,time:.8}),'native');for(const patch of [{swingActive:true},{hurt:true},{alive:false}])assert.equal(approachRhythm(p,{...o,time:.6,...patch}),'native');assert.equal(approachRhythm(p,{...o,wokeAt:NaN}),'hold');});
