import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import {CLOTHING_PALETTE_VERSION,TOP_COLOURS,TROUSER_COLOURS,PAIRINGS,outfitFor} from '../src/clothing-palettes.js';
const luminance=c=>.2126*c[0]+.7152*c[1]+.0722*c[2];
test('two immutable libraries each contain50 unique stable IDs and linear colours',()=>{assert.equal(CLOTHING_PALETTE_VERSION,'armagedom-clothing-033-v1');for(const rows of [TOP_COLOURS,TROUSER_COLOURS]){assert.equal(rows.length,50);assert.equal(new Set(rows.map(c=>c.id)).size,50);assert.equal(new Set(rows.map(c=>c.linear.join(','))).size,50);assert.ok(Object.isFrozen(rows));for(const row of rows){assert.ok(Object.isFrozen(row));assert.ok(Object.isFrozen(row.linear));assert.equal(row.linear.length,3);assert.ok(row.linear.every(c=>Number.isFinite(c)&&c>0&&c<1));assert.ok(row.family.length);}}});
test('worn colours include dark and light factors across13 families without fluorescent saturation',()=>{for(const rows of [TOP_COLOURS,TROUSER_COLOURS]){assert.equal(new Set(rows.map(c=>c.family)).size,13);const ls=rows.map(c=>luminance(c.linear));assert.ok(Math.min(...ls)<.02);assert.ok(Math.max(...ls)>.35);for(const row of rows){const srgb=row.linear.map(c=>c<=.0031308?12.92*c:1.055*c**(1/2.4)-.055);assert.ok(Math.max(...srgb)-Math.min(...srgb)<.34);}}});
test('sRGB swatches are converted once to true linear factors',()=>{const charcoal=TOP_COLOURS.find(c=>c.id==='top-charcoal-01');assert.ok(Math.abs(charcoal.linear[0]-0.017641954488384078)<1e-12);assert.ok(charcoal.linear[0]<36/255);});
test('every top has a frozen nonempty curated pairing set with explicit tonal separation',()=>{assert.ok(Object.isFrozen(PAIRINGS));assert.deepEqual(Object.keys(PAIRINGS),TOP_COLOURS.map(c=>c.id));for(const top of TOP_COLOURS){const ids=PAIRINGS[top.id];assert.ok(Object.isFrozen(ids));assert.ok(ids.length>0);assert.equal(new Set(ids).size,ids.length);for(const id of ids){const bottom=TROUSER_COLOURS.find(c=>c.id===id);assert.ok(bottom);assert.notEqual(top.family,bottom.family);assert.ok(Math.abs(luminance(top.linear)-luminance(bottom.linear))>=.035);}}});
test('all approved outfits preserve exact factors and reuse immutable identity',()=>{const all=new Set();for(const top of TOP_COLOURS)for(const id of PAIRINGS[top.id]){const bottom=TROUSER_COLOURS.find(c=>c.id===id),o=outfitFor(top.id,id);assert.ok(Object.isFrozen(o));assert.equal(outfitFor(top.id,id),o);assert.equal(o.topId,top.id);assert.equal(o.trouserId,id);assert.equal(o.jacket,top.linear);assert.equal(o.trousers,bottom.linear);assert.ok(!all.has(o.id));all.add(o.id);assert.throws(()=>{o.jacket[0]=1;},TypeError);}});
test('invalid and unapproved pairings never silently choose another outfit',()=>{assert.throws(()=>outfitFor('missing',TROUSER_COLOURS[0].id));assert.throws(()=>outfitFor(TOP_COLOURS[0].id,'missing'));assert.throws(()=>outfitFor(null,null));for(const top of TOP_COLOURS){const id=TROUSER_COLOURS.find(c=>!PAIRINGS[top.id].includes(c.id)).id;assert.throws(()=>outfitFor(top.id,id));}});

test('all50 trouser colours are reachable through approved pairings',()=>{const ids=new Set(Object.values(PAIRINGS).flat());assert.equal(ids.size,50);for(const row of TROUSER_COLOURS)assert.ok(ids.has(row.id));});

test('original Hollow semantic garment slots and vertex grime are distinct from skin/gear',()=>{const bytes=readFileSync(new URL('../public/assets/hollow-scavenger/hollow-scavenger.glb',import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),'b309eeb508a1c31babbfeaf13275ace3f54990dab380ae719c0d5881416f89fc');const glb=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)));assert.equal(glb.materials[4].name,'Torn charcoal canvas jacket');assert.equal(glb.materials[5].name,'Worn tobacco trousers');const p=glb.meshes[2].primitives;assert.deepEqual(p.map(r=>r.material),[3,4,5,6]);assert.ok(p.every(r=>r.attributes.COLOR_0!==undefined));});
