import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';
import {loadGeometry,endpoints} from '../../art/donor/probe.mjs';import {clone} from 'three/addons/utils/SkeletonUtils.js';import {equipDonorPlayer,DonorMotion} from '../src/donor-motion.js';import {CrookedHollowMotion,crookedPhase} from '../src/crooked-hollow.js';
const body=await loadGeometry(fs.readFileSync(new URL('../public/assets/hollow-scavenger/hollow-scavenger.glb',import.meta.url))),knife=await loadGeometry(fs.readFileSync(new URL('../public/assets/hollow-scavenger/knife.glb',import.meta.url))),description=JSON.parse(fs.readFileSync(new URL('../public/assets/hollow-scavenger/manifest.json',import.meta.url))).models['hollow-scavenger'];
function make(crooked){const source=equipDonorPlayer({scene:clone(body.scene),animations:body.animations},knife),root=new T.Group();root.add(source.scene);const native=new DonorMotion(root,source.scene,source.animations,description);return {root,source,native,motion:crooked?new CrookedHollowMotion(native):native};}
const position=(view,name)=>view.source.scene.getObjectByName(name).getWorldPosition(new T.Vector3());
const all=()=>body.animations.map(c=>({name:c.name,tracks:c.tracks.map(t=>Array.from(t.values))}));
test('deep fold lowers head, hangs hands, and restoration returns the actual rig exactly',()=>{const a=make(false),b=make(true);a.motion.sample('HollowIdle',0);b.motion.sample('HollowIdle',0);assert.ok(position(a,'Head').y-position(b,'Head').y>.20);for(const side of ['l','r'])assert.ok(position(b,'hand_'+side).y<position(b,'pelvis').y+.15);b.motion.restore();for(const name of ['pelvis','Head','hand_l','hand_r','foot_l','foot_r'])assert.ok(position(a,name).distanceTo(position(b,name))<1e-10);a.motion.dispose();b.motion.dispose();});
test('shuffling is nonlinear, continuous, wraps, and uneven at half-stride',()=>{assert.equal(crookedPhase(0),0);assert.equal(crookedPhase(1),0);assert.equal(crookedPhase(-.5),.5);assert.ok(crookedPhase(.28)<.15);assert.ok(crookedPhase(.82)<.7);assert.ok(Math.abs(crookedPhase(.4999)-crookedPhase(.5001))<.001);});
test('ground targets remain near native floor with asymmetric shortened steps on actual gait',()=>{const a=make(false),b=make(true);let shortened=0;for(const phase of [0,.1,.25,.4,.5,.65,.8,.95]){a.motion.sample('HollowWalk',crookedPhase(phase));b.motion.sample('HollowWalk',phase);for(const side of ['l','r']){const old=position(a,'foot_'+side),now=position(b,'foot_'+side);assert.ok(Math.abs(old.y-now.y)<.008,`${side}/${phase} floor drift ${old.y-now.y}`);assert.ok(now.toArray().every(Number.isFinite));if(Math.abs(old.z-position(a,'pelvis').z)>.05&&Math.abs(now.z-position(b,'pelvis').z)<Math.abs(old.z-position(a,'pelvis').z))shortened++;}}assert.ok(shortened>8);a.motion.dispose();b.motion.dispose();});
test('native weapon contact and all reactions stay exact after entering crooked locomotion',()=>{const a=make(false),b=make(true),before=all();for(const name of ['Attack','Return','Riposte','Heavy','Hit','Death','Roll','Guard','Parry','Deflected'])for(const phase of [0,.25,.5,.8,.999]){b.motion.sample('HollowWalk',.25);a.motion.sample(name,phase);b.motion.sample(name,phase);const ae=endpoints(a.source),be=endpoints(b.source);for(let i=0;i<ae.length;i++)assert.ok(ae[i].distanceTo(be[i])<1e-10);for(const bone of ['pelvis','spine_01','Head','foot_l','foot_r'])assert.ok(position(a,bone).distanceTo(position(b,bone))<1e-10);}assert.deepEqual(all(),before);a.motion.dispose();b.motion.dispose();});
test('same simulation tick reapply does not accumulate or lose folded posture',()=>{const b=make(true),entity={hp:40};b.motion.update(entity,1,1/60);const head=position(b,'Head'),foot=position(b,'foot_r');for(let i=0;i<12;i++){b.motion.update(entity,1,1/120);assert.ok(head.distanceTo(position(b,'Head'))<1e-10);assert.ok(foot.distanceTo(position(b,'foot_r'))<1e-10);}b.motion.dispose();});
test('clone independence, root transform preservation and disposal restore',()=>{const a=make(false),b=make(true);const original=all(),root=b.root.matrix.clone(),aHead=position(a,'Head');for(let i=0;i<10;i++)b.motion.sample('Run',i/10);assert.ok(aHead.distanceTo(position(a,'Head'))<1e-10);assert.deepEqual(all(),original);assert.deepEqual(b.root.matrix.toArray(),root.toArray());b.motion.restore();b.native.sample('HollowIdle',0);a.motion.sample('HollowIdle',0);assert.ok(position(a,'Head').distanceTo(position(b,'Head'))<1e-10);b.motion.dispose();assert.equal(b.native.disposed,true);a.motion.dispose();});
test('native update preserves every knife contact tick after crooked gait and hurt/death transitions',()=>{const a=make(false),b=make(true);for(const [clip,windup,active,recovery,sourceContact]of [['Attack',14,6,16,.34],['Return',14,6,16,.34],['Riposte',12,4,20,.34],['Heavy',22,5,26,.48]])for(let age=0;age<windup+active+recovery;age++){b.motion.sample('HollowWalk',.37);const entity={hp:40,swing:{clip,ageTicks:age,timing:{windup,active,recovery},sourceContact,end:Infinity}};a.motion.update(entity,age/60,1/60);b.motion.update(entity,age/60,1/60);const ae=endpoints(a.source),be=endpoints(b.source);for(let i=0;i<ae.length;i++)assert.ok(ae[i].distanceTo(be[i])<1e-10);}for(const entity of [{hp:40,response:{clip:'Hit',start:0,ticks:60}},{hp:0,response:{clip:'Death',start:0,ticks:120}}]){b.motion.sample('HollowWalk',.37);a.motion.update(entity,.3,1/60);b.motion.update(entity,.3,1/60);for(const bone of ['pelvis','Head','hand_r','foot_l'])assert.ok(position(a,bone).distanceTo(position(b,bone))<1e-10);}a.motion.dispose();b.motion.dispose();});
