import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';
import {ratLowBlade} from '../src/rat-contact.js';import bladePath from '../src/rat-data/blade-path.json' with {type:'json'};
import {loadGeometry} from '../../art/donor/probe.mjs';import {createActors} from '../src/actors.js';import {disposeActorSources} from '../src/actor-resources.js';
import {travelTo} from '../src/travel.js';
import {createGame,stepGame,attack,receiveHit} from '../src/combat.js';import {createHollowEncounter} from '../src/hollow-encounter.js';import {pistolCue} from '../src/pistol-targeting.js';
const publicRoot=new URL('../public/',import.meta.url),manifest=JSON.parse(fs.readFileSync(new URL('assets/manifest-hollow.json',publicRoot)));
const encounter=createHollowEncounter({rig:'hollow-scavenger',weapon:'knife',contactRig:'hero',bodyScale:1});
function world(){return {areaId:'east',layout:{characterScale:1.265},spawn:{x:0,z:0},move:(p,d)=>({x:p.x+d.x,z:p.z+d.z}),lineClear:()=>true,geometry:{clear:()=>true,lineClear:()=>true},toRender:(p,h=0)=>new T.Vector3(p.x,h,-p.z)};}
const options={pilot:'donor-knife',encounter,rat:true,dog:true,pistol:true,supplies:true,finishers:true,areaResidents:true,openingGroup:false};

test('one dog replaces South8 with approved stats and preserves rat and West identities',()=>{
 const g=createGame({...world(),areaId:'south'},options),dog=g.enemies.find(e=>e.rig==='original-dog');assert.equal(g.enemies.length,9);assert.equal(dog.placementKey,'south-roamer-8');assert.equal(dog.hp,30);assert.equal(dog.radius,1.54);assert.equal(dog.moveSpeed,2.6);assert.equal(dog.weapon,'teeth');assert.equal(g.enemies.filter(e=>e.rig==='original-dog').length,1);assert.equal(createGame(world(),options).enemies.find(e=>e.placementKey==='east-roamer-7').rig,'original-rat');assert.equal(createGame({...world(),areaId:'westminster'},options).enemies.length,6);
 g.enemies=[dog];dog.home=null;dog.pos={x:0,z:4};g.player.pos={x:0,z:0};Object.assign(g.pistol,{collected:true,equipped:true,magazine:6});g.pistolUserFacing={x:0,z:1};assert.equal(pistolCue(g).height,.70);stepGame(g,{actions:['fire'],aim:{x:0,z:1}});assert.equal(dog.hp,5);for(let i=0;i<90;i++)stepGame(g);stepGame(g,{actions:['fire'],aim:{x:0,z:1}});assert.equal(dog.hp,0);assert.equal(dog.response.clip,'dog_death');assert.equal(dog.response.ticks,60);assert.equal(dog.finisher.recipeId,'ordinary');assert.deepEqual(g.supplies.issued,[]);
});
test('dog calf target and whole-body direction remain committed through the native bite',()=>{
 const g=createGame({...world(),areaId:'south'},options),dog=g.enemies.find(e=>e.rig==='original-dog');g.enemies=[dog];g.player.pos={x:0,z:0};delete dog.contactGoalReach;Object.assign(dog,{radius:.77,pos:{x:0,z:1.17},facing:{x:0,z:-1},home:null,alerted:true,ready:0});let calls=0,goal={x:0,y:.5,z:.2,face:3181};g.ratContact={capture:()=>null,calf:()=>{calls++;return goal;}};
 stepGame(g);assert.equal(dog.swing.clip,'dog_bite_calf');assert.deepEqual(dog.swing.timing,{windup:18,active:6,recovery:24});assert.deepEqual(dog.swing.calfGoal,goal);const committed={...dog.facing};goal={x:.5,y:.5,z:0,face:1867};g.player.facing={x:1,z:0};for(let i=0;i<10;i++)stepGame(g);assert.equal(calls,1);assert.deepEqual(dog.facing,committed);assert.equal(dog.swing.calfGoal.face,3181);
});
for(const guarded of [false,true])test(`historical 1x dog geometry regression: approach and two-canine ${guarded?'block':'bite'} then native low and ordinary pistol death`,async t=>{
 const prior=globalThis.document;globalThis.document={createElement:()=>({width:0,height:0,getContext:()=>({createRadialGradient:()=>({addColorStop(){}}),fillRect(){}})})};t.after(()=>{if(prior===undefined)delete globalThis.document;else globalThis.document=prior;});
 const models=new Map();for(const[name,original]of Object.entries(manifest.models)){const description=name==='original-dog'?{...original,scale:1,contact:{canines:original.contact.canines,calfFaces:[{runtimeName:'Skin',face:3181,vertices:[1186,1201,1200]},{runtimeName:'Skin',face:1867,vertices:[1305,1307,1308]}]},clips:{...original.clips,attack:'dog_bite_calf'}}:original;models.set(name,{description,gltf:await loadGeometry(fs.readFileSync(new URL('assets/'+description.url,publicRoot))),equipment:description.equipment?await loadGeometry(fs.readFileSync(new URL('assets/'+description.equipment.url,publicRoot))):null});}
 const w={...world(),areaId:'south'},g=createGame(w,options),dog=g.enemies.find(e=>e.rig==='original-dog');g.enemies=[dog];g.player.pos={x:0,z:0};g.player.facing={x:-Math.SQRT1_2,z:Math.SQRT1_2};delete dog.contactGoalReach;Object.assign(dog,{radius:.77,pos:{x:-1.5,z:1.5},home:null,alerted:true});
 const sources=new Set([...models.values()].flatMap(m=>[m.gltf,m.equipment].filter(Boolean))),actors=createActors(new T.Scene(),w,{models,manifest,dispose:()=>disposeActorSources(sources)},{visualScale:1.3225});t.after(()=>actors.dispose());actors.update(g,0);g.ratContact=actors.ratContact();const events=[],commits=[];
 for(let i=0;i<240;i++){stepGame(g,guarded?{guard:true}:{});events.push(...g.events);commits.push(...g.events.filter(e=>e.type==='enemy-attack'&&e.actor===dog).map(e=>({tick:g.tick,goal:{...dog.swing.calfGoal},dir:{...dog.swing.dir}})));assert.ok(Math.hypot(dog.pos.x,dog.pos.z)>=1.17-1e-8);actors.events(g);actors.update(g,1/60,0,{presentationDt:1/60});if(events.some(e=>e.type===(guarded?'block':'hit')&&e.actor===g.player))break;}
 console.log('DOG_CONTACT',JSON.stringify({guarded,commits,events:events.filter(e=>['hit','block','parry'].includes(e.type)).map(e=>({type:e.type,amount:e.amount,move:e.moveId,weapon:e.weapon})),pos:dog.pos}));assert.ok(events.some(e=>e.type===(guarded?'block':'hit')&&e.actor===g.player));assert.ok(!events.some(e=>e.type==='parry'));if(!guarded)assert.equal(g.player.hp,142);else assert.equal(g.player.hp,150);assert.equal(commits[0].goal.face,guarded?1867:3181);assert.ok(commits[0].goal.y>=.49&&commits[0].goal.y<=.54);
 // Reuse the authored low blade against the actual dog skin; ordinary input remains the authority.
 g.player.ready=g.player.hurtUntil=g.player.dodgeUntil=0;g.player.guarding=false;dog.swing=null;dog.ready=100;assert.equal(attack(g,'slash'),true);assert.equal(g.player.swing.moveId,'dog_low');const before=dog.hp;for(let i=0;i<54;i++){stepGame(g);actors.events(g);actors.update(g,1/60,0,{presentationDt:1/60});}console.log('DOG_LOW',dog.hp,before);assert.equal(dog.hp,before-10);
 // Cancelled source responses are not a finisher capability; pistol uses native ordinary dog death.
 Object.assign(g.pistol,{collected:true,equipped:true,magazine:6});g.player.ready=g.player.hurtUntil=0;g.pistolUserFacing=normalDirection(dog.pos,g.player.pos);stepGame(g,{actions:['fire'],aim:g.pistolUserFacing});assert.equal(dog.hp,0);assert.equal(dog.response.clip,'dog_death');assert.equal(dog.finisher.recipeId,'ordinary');assert.equal(actors.views.get(dog.id).finisher,undefined);assert.deepEqual(g.supplies.issued,[]);actors.reset();actors.update(g,0,0,{restoreCorpses:true});assert.equal(actors.views.get(dog.id).motion.description.motion,'dog');
});
function normalDirection(to,from){const x=to.x-from.x,z=to.z-from.z,n=Math.hypot(x,z);return{x:x/n,z:z/n};}
