import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {createEffects} from '../src/effects.js';import {createLowHoverDroneLibrary} from '../src/low-hover-drone.js';import {droneHoverHeight} from '../src/drone-mechanics.js';import {pistolCue} from '../src/pistol-targeting.js';
test('raised visible frame, live aim marker, shot endpoint and emitted bolt use physical body height',()=>{
 const scene=new T.Scene(),world={areaId:'westminster',toRender:(p,h=0)=>new T.Vector3(p.x,h,-p.z),lineClear:()=>true},library=createLowHoverDroneLibrary(),actor={id:1,rig:'low-hover-drone',hp:20,radius:.55,pos:{x:0,z:3},areaId:'westminster'},drone=library.spawn({scene,position:{x:0,z:-3}}),g={pilot:'donor-knife',world,time:Math.PI/6,player:{id:0,hp:150,pos:{x:0,z:0},facing:{x:0,z:1},hurtUntil:0,dodgeUntil:0},pistol:{equipped:true,collected:true,magazine:6,nextFireAt:0,reloadingUntil:0},enemies:[actor],corpses:[],bolts:[],loot:[],events:[]};
 drone.update({time:g.time});drone.root.updateMatrixWorld(true);const frame=drone.root.getObjectByName('ARM_Drone_Rigid_Frame'),bounds=new T.Box3().setFromObject(frame);assert.equal(drone.root.position.y,droneHoverHeight(g.time));assert(bounds.min.y>.6);assert.equal(pistolCue(g).height,drone.root.position.y);
 const fx=createEffects(scene,world,null,()=>null,{reducedMotion:()=>false,getView:e=>e===actor?{root:drone.root}:null});fx.update(g);assert.equal(scene.getObjectByName('Pistol aim marker').position.y,drone.root.position.y);
 g.events=[{type:'shot',actor:g.player,origin:g.player.pos,end:actor.pos,targetId:actor.id,direction:g.player.facing}];fx.events(g);fx.update(g);const tracer=scene.getObjectByName('Combat pooled tracer');assert(Math.abs(tracer.geometry.attributes.position.getY(1)-drone.root.position.y)<1e-7);
 g.bolts=[{id:2,pos:actor.pos,height:droneHoverHeight(g.time)}];fx.update(g);const bolt=scene.children.find(o=>o.isMesh&&o.geometry.type==='SphereGeometry');assert.equal(bolt.position.y,drone.root.position.y);fx.dispose();drone.dispose();library.dispose();assert.equal(scene.children.length,0);
});
