import test from 'node:test';import assert from 'node:assert/strict';import * as T from 'three';
import {createEffects} from '../src/effects.js';import {createLowHoverDroneLibrary} from '../src/low-hover-drone.js';import {droneHoverHeight,DRONE_RULES} from '../src/drone-mechanics.js';import {pistolCue} from '../src/pistol-targeting.js';
test('raised visible frame, live aim marker, shot endpoint and emitted bolt use physical body height',()=>{
 const scene=new T.Scene(),world={areaId:'westminster',camera:new T.PerspectiveCamera(),toRender:(p,h=0)=>new T.Vector3(p.x,h,-p.z),lineClear:()=>true},library=createLowHoverDroneLibrary(),actor={id:1,rig:'low-hover-drone',hp:20,radius:DRONE_RULES.radius,pos:{x:0,z:3},areaId:'westminster'},drone=library.spawn({scene,position:{x:0,z:-3}}),g={pilot:'donor-knife',world,time:Math.PI/6,player:{id:0,hp:150,pos:{x:0,z:0},facing:{x:0,z:1},hurtUntil:0,dodgeUntil:0},pistol:{equipped:true,collected:true,magazine:6,nextFireAt:0,reloadingUntil:0},enemies:[actor],corpses:[],bolts:[],loot:[],events:[]};
 drone.update({time:g.time});drone.root.updateMatrixWorld(true);const frame=drone.root.getObjectByName('ARM_Drone_Rigid_Frame'),bounds=new T.Box3().setFromObject(frame);assert.equal(drone.root.position.y,droneHoverHeight(g.time));assert(bounds.min.y>.48);assert.deepEqual(drone.root.scale.toArray(),[2,2,2]);assert.equal(pistolCue(g).height,drone.root.position.y);
 const fx=createEffects(scene,world,null,()=>null,{reducedMotion:()=>false,getView:e=>e===actor?{root:drone.root}:null});fx.update(g);assert.equal(scene.getObjectByName('Pistol aim marker').position.y,drone.root.position.y);
 g.events=[{type:'shot',actor:g.player,origin:g.player.pos,end:actor.pos,targetId:actor.id,direction:g.player.facing}];fx.events(g);fx.update(g);const tracer=scene.getObjectByName('Combat pooled tracer');assert(Math.abs(tracer.geometry.attributes.position.getY(1)-drone.root.position.y)<1e-7);
 g.bolts=[{id:2,pos:actor.pos,dir:{x:0,z:1},expires:g.time+.5,height:droneHoverHeight(g.time)}];fx.update(g);const bolt=scene.getObjectByName('ARM laser bolt 2');assert.equal(bolt.position.y,drone.root.position.y);fx.dispose();drone.dispose();library.dispose();assert.equal(scene.children.length,0);
});

test('pointer on raised rigid body resolves its actual surface; foreground depth mask and ordinary ground aim retain authority',async()=>{
 const {LondonWorld}=await import('../src/world.js'),{pistolPointerPoint}=await import('../src/pistol-targeting.js'),fs=await import('node:fs'),layout=JSON.parse(fs.readFileSync(new URL('../public/world/westminster/layout.json',import.meta.url))),scene=new T.Scene(),world=new LondonWorld({THREE:T,scene,camera:new T.PerspectiveCamera(),layout,texture:new T.Texture()}),library=createLowHoverDroneLibrary(),actor={id:1,rig:'low-hover-drone',hp:20,radius:DRONE_RULES.radius,pos:{x:8,z:-3}},drone=library.spawn({scene,position:world.toRender(actor.pos)}),views=new Map([[1,{model:drone.root}]]),player={hp:150,pos:{x:5.8,z:-3},facing:{x:1,z:0},hurtUntil:0,dodgeUntil:0};
 world.update(player.pos,0,393,852,true);drone.update({time:.4});drone.root.updateMatrixWorld(true);const body=drone.root.position.clone().project(world.camera),ground=world.screenToGround(body.x,body.y),g={world,time:.4,player,pistol:{equipped:true,magazine:6,reloadingUntil:0,nextFireAt:0},enemies:[actor],pistolUserFacing:{x:ground.x-player.pos.x,z:ground.z-player.pos.z}};assert.equal(pistolCue(g).targetId,actor.id,'Doubled physical circle accepts this inherited ground ray; surface picking still follows actual frame');
 const surface=pistolPointerPoint(world,views,[actor],body.x,body.y);g.pistolUserFacing={x:surface.x-player.pos.x,z:surface.z-player.pos.z};assert.equal(pistolCue(g).targetId,actor.id);assert.deepEqual(pistolPointerPoint(world,views,[],body.x,body.y),ground);
 const shield=new T.Mesh(new T.PlaneGeometry(10,10),new T.MeshBasicMaterial({side:T.DoubleSide}));shield.position.copy(world.ray.ray.origin).addScaledVector(world.ray.ray.direction,1);shield.lookAt(world.ray.ray.origin);shield.updateMatrixWorld(true);world.masks.push(shield);assert.deepEqual(pistolPointerPoint(world,views,[actor],body.x,body.y),ground);shield.geometry.dispose();shield.material.dispose();drone.dispose();library.dispose();world.dispose();
});
