import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {clone} from 'three/addons/utils/SkeletonUtils.js';
import {FACE_RECIPES,ORIGINAL_FACE_ID} from '../src/face-recipes.js';import {createFaceAppearanceLibrary} from '../src/face-appearance.js';
globalThis.ProgressEvent=class{constructor(_,fields){Object.assign(this,fields)}};
const bytes=fs.readFileSync(new URL('../../art/appearance-pilot/proof-final/neck-repair.glb',import.meta.url));
assert.equal(createHash('sha256').update(bytes).digest('hex'),'352533ecf93234b23a69752b266b134eee387c35e5fc87ea0c2230085fa4f1ff');
const n=bytes.readUInt32LE(12),doc=JSON.parse(bytes.subarray(20,20+n)),bin=bytes.subarray(28+n);doc.images=[];doc.textures=[];doc.materials=doc.materials.map(m=>({name:m.name}));doc.buffers[0].uri='data:application/octet-stream;base64,'+bin.toString('base64');
const source=(await new GLTFLoader().parseAsync(JSON.stringify(doc),'')).scene;
function own(){const m=clone(source);m.traverse(n=>{if(n.isMesh)n.material=Array.isArray(n.material)?n.material.map(m=>m.clone()):n.material.clone()});return m;}
function signature(model){const h=createHash('sha256');model.traverse(n=>{if(n.isMesh){for(const[k,a]of Object.entries(n.geometry.attributes))h.update(k).update(new Uint8Array(a.array.buffer,a.array.byteOffset,a.array.byteLength));for(const m of(Array.isArray(n.material)?n.material:[n.material]))h.update(JSON.stringify([m.name,m.color.toArray(),m.vertexColors]));}if(n.isBone)h.update(JSON.stringify([n.name,n.position.toArray(),n.quaternion.toArray(),n.scale.toArray()]));});return h.digest('hex');}
test('actual repaired rig handles all50 recipes with bounded shared geometry and no source/clone cross-mutation',()=>{
  const kit=createFaceAppearanceLibrary(source),a=own(),b=own(),sourceBefore=signature(source),bBefore=signature(b),aBefore=signature(a),geometries=new Set();
  for(const r of FACE_RECIPES){const handle=kit.apply(a,r.id);a.traverse(n=>{if(n.isMesh&&!n.name.startsWith('Hollow body'))geometries.add(n.geometry)});assert.equal(signature(source),sourceBefore);assert.equal(signature(b),bBefore);const hair=a.getObjectByName('Scavenger hair');if(r.hairPreset==='buzz')assert(!hair);else{assert(hair);assert.equal(hair.skeleton,a.getObjectByName('Photo').skeleton);const w=hair.geometry.getAttribute('skinWeight');for(let i=0;i<w.count;i++)assert(Math.abs(w.getX(i)+w.getY(i)+w.getZ(i)+w.getW(i)-1)<1e-6);}
    handle.dispose();handle.dispose();assert.equal(signature(a),aBefore);assert.equal(kit.stats().activeActors,0);}
  assert.equal(kit.stats().cachedGeometries,22);assert(kit.stats().geometryBytes<8*1024*1024);let sourceDisposals=0,cachedDisposals=0;source.getObjectByName('Photo').geometry.addEventListener('dispose',()=>sourceDisposals++);for(const g of geometries)if(g!==source.getObjectByName('Photo').geometry)g.addEventListener('dispose',()=>cachedDisposals++);kit.dispose();kit.dispose();assert.equal(sourceDisposals,0);assert.equal(cachedDisposals,22);assert.throws(()=>kit.apply(a,FACE_RECIPES[0].id),/disposed/);
});
test('fallback/unknown/shared-material rejection preserve the rig; owned hair disposes once without skeleton disposal',()=>{
  const kit=createFaceAppearanceLibrary(source),a=own(),before=signature(a);kit.apply(a,ORIGINAL_FACE_ID).dispose();assert.equal(signature(a),before);assert.throws(()=>kit.apply(a,'bad-id'),/Unknown face recipe/);assert.equal(signature(a),before);const unsafe=clone(source),unsafeBefore=signature(unsafe);assert.throws(()=>kit.apply(unsafe,FACE_RECIPES[1].id),/Clone actor materials/);assert.equal(signature(unsafe),unsafeBefore);
  const r=FACE_RECIPES.find(r=>r.hairPreset!=='buzz'),h=kit.apply(a,r.id);let materialDisposals=0,skeletonDisposals=0;h.extraMaterials[0].addEventListener('dispose',()=>materialDisposals++);const skeleton=a.getObjectByName('Photo').skeleton,originalDispose=skeleton.dispose;skeleton.dispose=()=>skeletonDisposals++;assert.throws(()=>kit.dispose(),/Dispose actor appearances/);h.dispose();h.dispose();assert.equal(materialDisposals,1);assert.equal(skeletonDisposals,0);skeleton.dispose=originalDispose;kit.dispose();assert.equal(signature(a),before);
});
