import test from 'node:test';import assert from 'node:assert/strict';import {createGame,stepGame} from '../src/combat.js';import {createDroneState} from '../src/drone-mechanics.js';
const encounter={id:'hollow-scavengers',character:{rig:'hollow-scavenger',weapon:'knife',contactRig:'hero',bodyScale:1}};
function fresh(cycle='A',area='east'){
 const world={areaId:area,layout:{characterScale:1.265},spawn:{x:20,z:-6},move:(p,d)=>({x:p.x+d.x,z:p.z+d.z}),lineClear:()=>true};
 return createGame(world,{pilot:'donor-knife',encounter,pistol:true,rat:true,dog:true,roach:true,drone:true,animalVariants:true,animalCycle:cycle,areaResidents:true,openingGroup:false});
}
function setup(gap=4){const g=fresh(),e=g.enemies.find(e=>e.placementKey==='east-roamer-4'),ally=g.enemies.find(e=>e.placementKey==='east-roamer-9');g.enemies=[e,ally];Object.assign(e,{pos:{x:0,z:0},home:{x:0,z:0},patrol:[{x:0,z:0},{x:2,z:0}],patrolIndex:1,facing:{x:0,z:1}});Object.assign(ally,{pos:{x:4,z:0},home:{x:4,z:0},recoverUntil:100});g.player.pos={x:0,z:gap};return{g,e,ally};}
test('Pack activates only Cycle A East4; unbound dogs retain native baseline parameters',()=>{for(const cycle of ['A','B'])for(const area of ['east','south','westminster']){const g=fresh(cycle,area);assert.equal(g.enemies.length,area==='westminster'?7:10);assert.deepEqual(g.enemies.filter(e=>e.residentIntent?.companionDistance>0).map(e=>e.placementKey),area==='east'&&cycle==='A'?['east-roamer-4']:[]);for(const e of g.enemies.filter(e=>e.rig==='original-dog')){assert.deepEqual([e.hp,e.radius],[30,1.54]);if(!e.animalRole)assert.deepEqual([e.moveSpeed,e.recoveryDelay],[2.6,0]);}}});
test('integrated wake requires self distance or alerted East9, independent pair and player LOS',()=>{for(const [alerted,pairLOS,playerLOS,wakes]of [[false,true,true,false],[true,true,true,true],[true,false,true,false],[true,true,false,false]]){const{g,e,ally}=setup();ally.alerted=alerted;g.world.lineClear=(a,b)=>Math.abs(a.x-b.x)>3?pairLOS:playerLOS;stepGame(g);assert.equal(e.alerted,wakes);assert.equal(e.packCompanions.hasEligibleCompanion,pairLOS);if(wakes){assert.equal(e.packMovement,'native');assert(e.pos.z>0);}}const{g,e}=setup(2.4);g.enemies=[e];stepGame(g);assert(e.alerted);assert.equal(e.packMovement,'hold');});
test('alerted drone, human, rat, roach, foreign or dead East9 cannot wake or pair Pack',()=>{for(const [rig,key,area,hp]of [['low-hover-drone','east-drone-1','east',20],['hollow-scavenger','east-roamer-1','east',40],['original-rat','east-roamer-7','east',20],['original-roach','east-roamer-5','east',20],['original-dog','east-roamer-9','south',30],['original-dog','east-roamer-9','east',0]]){const{g,e,ally}=setup();Object.assign(ally,{rig,placementKey:key,areaId:area,hp,alerted:true,droneState:createDroneState()});stepGame(g);assert.equal(e.alerted,false);assert.equal(e.packCompanions.hasEligibleCompanion,false);}});
test('isolated clear retreat uses backward native movement and bypasses pursuit steering',()=>{const{g,e}=setup(1.95);g.enemies=[e];e.alerted=true;g.bridgeSteering={steer(){throw Error('forward pursuit steering used during retreat')},reset(){}};stepGame(g);assert.equal(e.packMovement,'withdraw');assert(e.pos.z<0);assert(e.facing.z>.99);assert.equal(e.swing,null);});
test('isolated hold and blocked retreat preserve roots and deny new bite',()=>{for(const gap of [1.95,2,4]){const{g,e}=setup(gap);g.enemies=[e];e.alerted=true;if(gap<2)g.world.move=p=>({...p});const before={...e.pos};stepGame(g);assert.equal(e.packMovement,'hold');assert.deepEqual(e.pos,before);assert.equal(e.swing,null);}});
test('native recovery retains authority; leash independently clears alert',()=>{const{g,e}=setup(1.95);g.enemies=[e];e.alerted=true;e.recoverUntil=1;const before={...e.pos};stepGame(g);assert.deepEqual(e.pos,before);assert.equal(e.packMovement,'native');e.recoverUntil=0;g.player.pos={x:0,z:13};stepGame(g);assert.equal(e.alerted,false);assert.equal(e.returning,false);assert.equal(e.hp,30);});
test('an already active paired native bite continues after companion disappears',()=>{const{g,e,ally}=setup(1.94);ally.alerted=true;g.ratContact={capture:()=>null,calf:()=>({x:0,z:.4,y:1.05,face:2400})};stepGame(g);assert.equal(e.swing?.clip,'dog_bite_scaled');const swing=e.swing;g.enemies=[e];stepGame(g);assert.equal(e.swing,swing);assert.equal(e.packMovement,'native');assert.equal(e.swing.def.damage,8);});
