import test from 'node:test';
import assert from 'node:assert/strict';
import {pistolCue,resolvePistolShot} from '../src/pistol-targeting.js';
import {createGame,stepGame,enemy} from '../src/combat.js';
const world=()=>({areaId:'westminster',spawn:{x:0,z:-6},layout:{characterScale:1.265},move:(p,d)=>({x:p.x+d.x,z:p.z+d.z}),lineClear:()=>true});
function fixture(){const w=world(),g=createGame(w,{pilot:'donor-knife',pistol:true});stepGame(g,{actions:['pickup']},1/60);g.wave=1;g.enemies=[Object.assign(enemy(0,{x:0,z:0}),{staggerUntil:100,areaId:'westminster'})];return g;}
const shot=g=>resolvePistolShot({position:g.player.pos,aim:g.pistolUserFacing,targets:g.enemies,lineClear:g.world.lineClear,areaId:g.world.areaId});
test('cue reads original intent and agrees with native assisted Fire without retaining or turning',()=>{const g=fixture(),e=g.enemies[0];e.pos.x=.5;const before=JSON.stringify(g);const cue=pistolCue(g,{visibleIds:[e.id]});assert.equal(cue.targetId,e.id);assert.equal(JSON.stringify(g),before);const trace=shot(g);stepGame(g,{actions:['fire'],combatVisibleIds:[e.id]},1/60);const actual=g.events.find(e=>e.type==='shot');assert.equal(actual.targetId,cue.targetId);assert.deepEqual(actual.direction,trace.direction);assert.equal(g.pistol.magazine,5);assert.equal(e.hp,30);assert.equal(g.pistolTargetId,null);assert.deepEqual(g.pistolUserFacing,{x:0,z:1});assert.deepEqual(g.player.facing,actual.direction);});
test('far aligned selection cannot advertise past the nearer first trace hit',()=>{const g=fixture();const near=g.enemies[0];near.pos={x:.2,z:-3};const far=Object.assign(enemy(0,{x:0,z:4}),{staggerUntil:100});g.enemies.push(far);assert.equal(shot(g).targetId,near.id);assert.equal(pistolCue(g).targetId,near.id);stepGame(g,{actions:['fire']},1/60);assert.equal(g.events.find(e=>e.type==='shot').targetId,near.id);assert.equal(far.hp,55);});
test('current LOS, area, viewport, alive, cone and range gate upper-body target immediately',()=>{for(const mode of ['blocked','foreign','invisible','dead','rear','side','far','offscreen']){const g=fixture(),e=g.enemies[0];if(mode==='blocked')g.world.lineClear=(_a,b)=>b.z< -2;if(mode==='foreign')e.areaId='east';if(mode==='invisible')e.visible=false;if(mode==='dead')e.hp=0;if(mode==='rear')e.pos.z=-10;if(mode==='side')e.pos.x=10;if(mode==='far')e.pos.z=13;assert.equal(pistolCue(g,{visibleIds:mode==='offscreen'?[]:[e.id]}).targetId,null,mode);}});
test('ineligible nearer trace hit never advertises far eligible selection',()=>{const g=fixture(),near=g.enemies[0],far=Object.assign(enemy(0,{x:0,z:4}),{staggerUntil:100});near.pos.z=-3;g.enemies.push(far);assert.equal(resolvePistolShot({position:g.player.pos,aim:g.pistolUserFacing,targets:g.enemies,visibleIds:[far.id],lineClear:g.world.lineClear,areaId:'westminster'}).targetId,near.id);assert.equal(pistolCue(g,{visibleIds:[far.id]}).targetId,null);});
test('empty, reload, cooldown, hurt, dodge and swing show only muted free aim',()=>{for(const mode of ['empty','reload','cooldown','hurt','dodge','swing']){const g=fixture();if(mode==='empty')g.pistol.magazine=0;if(mode==='reload')g.pistol.reloadingUntil=2;if(mode==='cooldown')g.pistol.nextFireAt=2;if(mode==='hurt')g.player.hurtUntil=2;if(mode==='dodge')g.player.dodgeUntil=2;if(mode==='swing')g.player.swing={};const cue=pistolCue(g);assert.equal(cue.targetId,null,mode);assert.equal(cue.ready,false,mode);assert.deepEqual(cue.position,{x:0,z:-2});}});
test('pause, holster, death and Retry cannot carry a target marker',()=>{const g=fixture();assert.ok(pistolCue(g).targetId);assert.equal(pistolCue(g,{paused:true}),null);g.pistol.equipped=false;assert.equal(pistolCue(g),null);g.pistol.equipped=true;g.player.hp=0;assert.equal(pistolCue(g),null);g.player.hp=150;g.finished=true;assert.equal(pistolCue(g),null);assert.equal(pistolCue(createGame(world(),{pilot:'donor-knife',pistol:true})),null);});
test('free aim follows changed user intent immediately, never prior assisted facing',()=>{const g=fixture();g.player.facing={x:0,z:1};g.pistolUserFacing={x:1,z:0};assert.equal(pistolCue(g).targetId,null);assert.deepEqual(pistolCue(g).position,{x:4,z:-6});});
