import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';import {createEffects} from '../src/effects.js';
const actor={id:0,pos:{x:0,z:0},facing:{x:0,z:1},hp:150};const victim={id:1,pos:{x:2,z:3},facing:{x:0,z:-1}};
const world={toRender:(p,h=0)=>new THREE.Vector3(p.x,h,-p.z)};
const game=()=>({pilot:'donor-knife',time:1,player:{...actor},pistol:{equipped:true,collected:true},events:[],enemies:[],bolts:[],loot:[]});
const shot={type:'shot',actor,origin:actor.pos,end:victim.pos,direction:actor.facing};const hit={type:'hit',actor:victim,position:victim.pos,weapon:'pistol',amount:25};
test('only actual shot starts120ms recoil; misses recoil, dry/rejected do not',()=>{const scene=new THREE.Scene(),fx=createEffects(scene,world),g=game();assert.equal(fx.pistolRecoil(g),0);g.events=[{type:'dry',actor}];fx.events(g);assert.equal(fx.pistolRecoil(g),0);g.events=[shot];fx.events(g);assert.equal(fx.pistolRecoil(g),1);g.time+=.06;assert.ok(Math.abs(fx.pistolRecoil(g)-.5)<1e-8);g.time+=.061;assert.equal(fx.pistolRecoil(g),0);g.events=[{type:'dry',actor}];fx.events(g);assert.equal(fx.pistolRecoil(g),0);fx.dispose();});
test('positive pistol hit gets existing-line impact pop; blocked/zero/miss cannot kick',()=>{const scene=new THREE.Scene(),fx=createEffects(scene,world),g=game(),camera=new THREE.PerspectiveCamera();const base=camera.projectionMatrix.toArray();let shifted=false;const renderer={render:()=>{shifted=camera.projectionMatrix.toArray().some((v,i)=>v!==base[i]);}};g.events=[{...hit,amount:0},{...hit,blocked:true},shot];fx.events(g);fx.render(renderer,camera,g,393);assert.equal(shifted,false);assert.equal(scene.children.filter(o=>o.name==='Pistol impact pop').length,0);g.events=[hit];fx.events(g);const pop=scene.children.find(o=>o.name==='Pistol impact pop');assert.ok(pop);assert.equal(pop.material.color.getHex(),0xffdf9a);const vertices=pop.geometry.attributes.position;for(let i=0;i<vertices.count;i++)assert.ok(Math.abs(Math.hypot(vertices.getX(i),vertices.getZ(i))-.22)<1e-6);fx.render(renderer,camera,g,393);assert.equal(shifted,true);g.time+=.101;fx.update(g);assert.equal(scene.children.some(o=>o.name==='Pistol impact pop'),false);fx.dispose();});
test('2CSSpx135ms render kick restores exact projection/inverse, never accumulates, including throw',()=>{const scene=new THREE.Scene(),fx=createEffects(scene,world),g=game(),camera=new THREE.PerspectiveCamera(),original=camera.projectionMatrix.toArray(),inverse=camera.projectionMatrixInverse.toArray(),point=new THREE.Vector3(0,0,-3);const baseline=point.clone().project(camera).y;g.events=[hit];fx.events(g);let offset=0;const renderer={render:()=>{offset=point.clone().project(camera).y-baseline;}};for(let i=0;i<3;i++){fx.render(renderer,camera,g,852);assert.ok(Math.abs(offset+4/852)<1e-12);assert.deepEqual(camera.projectionMatrix.toArray(),original);assert.deepEqual(camera.projectionMatrixInverse.toArray(),inverse);}g.time+=.0675;fx.render(renderer,camera,g,852);assert.ok(Math.abs(offset+2/852)<1e-12);g.time+=.068;fx.render(renderer,camera,g,852);assert.equal(offset,0);g.events=[hit];fx.events(g);assert.throws(()=>fx.render({render(){throw Error('draw failed')}},camera,g,852));assert.deepEqual(camera.projectionMatrix.toArray(),original);assert.deepEqual(camera.projectionMatrixInverse.toArray(),inverse);fx.dispose();});
test('reduced motion and cancel/reset/holster/death/ending clear transient pistol presentation',()=>{let reduced=false;const scene=new THREE.Scene(),fx=createEffects(scene,world,null,()=>null,{reducedMotion:()=>reduced}),g=game(),camera=new THREE.PerspectiveCamera(),base=camera.projectionMatrix.toArray();let shifted=false;const renderer={render:()=>{shifted=camera.projectionMatrix.toArray().some((v,i)=>v!==base[i]);}};g.events=[shot,hit];fx.events(g);reduced=true;fx.render(renderer,camera,g,393);assert.equal(shifted,false);reduced=false;fx.clearPistolFeedback();fx.render(renderer,camera,g,393);assert.equal(shifted,false);assert.equal(fx.pistolRecoil(g),0);for(const mode of ['holster','death','ending','reset']){g.player.hp=150;g.finished=false;g.pistol.equipped=true;g.events=[shot,hit];fx.events(g);if(mode==='holster')g.pistol.equipped=false;if(mode==='death')g.player.hp=0;if(mode==='ending')g.finished=true;if(mode==='reset')fx.reset();fx.update(g);fx.render(renderer,camera,g,393);assert.equal(shifted,false);assert.equal(fx.pistolRecoil(g),0);}fx.dispose();assert.equal(scene.children.length,0);});

test('billboard brackets reuse owned resources and hide on cancellation/weapon/death/reset',()=>{
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,2,.1,100);camera.position.set(0,10,20);camera.lookAt(0,0,0);camera.updateMatrixWorld();
 const w={...world,camera,areaId:'westminster',lineClear:()=>true},g=game();g.world=w;g.player.dodgeUntil=g.player.hurtUntil=0;g.pistol.magazine=6;g.pistol.nextFireAt=g.pistol.reloadingUntil=0;g.enemies=[{id:1,hp:40,pos:{x:0,z:4},radius:.4}];
 const fx=createEffects(scene,w),marker=scene.children.find(o=>o.name==='Pistol aim marker'),geometries=marker.children.map(o=>o.geometry),materials=marker.children.map(o=>o.material);
 for(let i=0;i<60;i++){fx.update(g,{visibleIds:[1],viewportHeight:i%2?852:393});assert.equal(marker.userData.targetId,1);assert.ok(marker.quaternion.equals(camera.quaternion));assert.equal(marker.children.length,3);assert.deepEqual(marker.children.map(o=>o.geometry),geometries);assert.deepEqual(marker.children.map(o=>o.material),materials);}
 assert.equal(marker.children[2].visible,true);g.pistol.magazine=0;fx.update(g);assert.equal(marker.userData.targetId,null);assert.equal(marker.userData.ready,false);assert.equal(marker.children[2].visible,false);assert.ok(materials[1].opacity<.3);
 fx.update(g,{paused:true});assert.equal(marker.visible,false);g.pistol.magazine=6;fx.update(g);fx.clearPistolFeedback();assert.equal(marker.visible,false);assert.equal(marker.userData.targetId,null);
 for(const mode of ['holster','death','reset']){g.pistol.equipped=true;g.player.hp=150;fx.update(g);if(mode==='holster')g.pistol.equipped=false;if(mode==='death')g.player.hp=0;if(mode==='reset')fx.reset();else fx.update(g);assert.equal(marker.visible,false);}
 let disposed=0;for(const resource of [...geometries,...materials])resource.addEventListener('dispose',()=>disposed++);fx.dispose();assert.equal(disposed,6);assert.equal(scene.children.length,0);
});
