import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';import {createEffects} from '../src/effects.js';
const actor={id:0,pos:{x:0,z:0},facing:{x:0,z:1},hp:150};const victim={id:1,pos:{x:2,z:3},facing:{x:0,z:-1}};
const world={toRender:(p,h=0)=>new THREE.Vector3(p.x,h,-p.z)};
const game=()=>({pilot:'donor-knife',time:1,player:{...actor},pistol:{equipped:true,collected:true},events:[],enemies:[],bolts:[],loot:[]});
const shot={type:'shot',actor,origin:actor.pos,end:victim.pos,direction:actor.facing};const hit={type:'hit',actor:victim,position:victim.pos,weapon:'pistol',amount:25};
test('only actual shot starts reference recoil; dry/cooldown and presentation pause cannot restart it',()=>{const scene=new THREE.Scene(),fx=createEffects(scene,world),g=game();g.events=[{type:'dry',actor}];fx.events(g);assert.equal(fx.pistolRecoil(g),0);g.events=[shot];fx.events(g);assert.equal(fx.pistolRecoil(g),1);fx.advance(.05);assert.ok(Math.abs(fx.pistolRecoil(g)-Math.exp(-.60))<1e-8);const before=fx.snapshot();fx.advance(10,{paused:true});assert.deepEqual(fx.snapshot(),before);g.events=[{type:'dry',actor}];fx.events(g);assert.equal(fx.pistolRecoil(g),before.shot);for(let i=0;i<60;i++)fx.advance(1/60);assert.equal(fx.pistolRecoil(g),0);fx.dispose();});
test('shot camera cue plus one confirmed lethal hit burst; blocked and zero hits create none',()=>{const scene=new THREE.Scene(),fx=createEffects(scene,world),g=game();g.events=[{...hit,amount:0},{...hit,blocked:true},shot];fx.events(g);assert.equal(fx.snapshot().activeParticles,0);assert.ok(Math.hypot(fx.snapshot().cameraX,fx.snapshot().cameraY)>0);g.events=[hit,{type:'death',actor:victim}];fx.events(g);assert.equal(fx.snapshot().activeParticles,12);assert.equal(fx.snapshot().hold,.08);fx.advance(.04);assert.equal(fx.snapshot().hold,.04);for(let i=0;i<60;i++)fx.advance(1/60);assert.equal(fx.snapshot().activeParticles,0);fx.dispose();assert.equal(scene.children.length,0);});
test('bounded pixel camera kick restores exact projection/inverse including repeated draw and throw',()=>{const scene=new THREE.Scene(),fx=createEffects(scene,world),g=game(),camera=new THREE.PerspectiveCamera(),original=camera.projectionMatrix.toArray(),inverse=camera.projectionMatrixInverse.toArray();g.events=[hit];fx.events(g);for(let i=0;i<3;i++){let shifted=false;fx.render({render(){shifted=camera.projectionMatrix.toArray().some((v,n)=>v!==original[n]);}},camera,g,852);assert.equal(shifted,true);assert.deepEqual(camera.projectionMatrix.toArray(),original);assert.deepEqual(camera.projectionMatrixInverse.toArray(),inverse);}assert.ok(Math.hypot(fx.snapshot().cameraX,fx.snapshot().cameraY)<=8);assert.throws(()=>fx.render({render(){throw Error('draw failed');}},camera,g,852));assert.deepEqual(camera.projectionMatrix.toArray(),original);assert.deepEqual(camera.projectionMatrixInverse.toArray(),inverse);fx.dispose();});
test('High Low Off/reduced motion/reset keep bounded pools and basic shot feedback without gameplay mutation',()=>{let reduced=false;const scene=new THREE.Scene(),fx=createEffects(scene,world,null,()=>null,{reducedMotion:()=>reduced}),g=game(),pools=scene.getObjectByName('Combat feedback pool'),resources=pools.children.map(o=>o.geometry),before=JSON.stringify(g);for(const mode of ['high','low','off']){fx.configureFeedback(mode);g.events=[shot,hit];fx.events(g);fx.update(g);const s=fx.snapshot();assert.equal(s.mode,mode);assert.equal(s.activeParticles,mode==='high'?8:mode==='low'?3:1);assert.equal(s.activeTracers,1);assert.equal(s.muzzleFlash,true);assert.equal(s.shot,mode==='high'?1:mode==='low'?.4:0);assert.equal(s.hold,mode==='high'?.05:0);assert.deepEqual(pools.children.map(o=>o.geometry),resources);fx.clearPistolFeedback();assert.equal(fx.snapshot().activeParticles,0);assert.equal(fx.snapshot().activeTracers,0);}fx.configureFeedback('high');reduced=true;fx.advance(0);g.events=[shot,hit];fx.events(g);assert.equal(fx.snapshot().mode,'low');assert.equal(fx.snapshot().cameraX,0);assert.equal(fx.snapshot().cameraY,0);for(let i=0;i<100;i++){g.events=[shot,hit];fx.events(g);fx.update(g);}assert.ok(fx.snapshot().activeParticles<=48);assert.ok(fx.snapshot().activeTracers<=16);fx.reset();g.events=[];assert.equal(JSON.stringify(g),before);fx.dispose();assert.equal(scene.children.length,0);});

test('outlined crosshair and target indicator reuse owned resources and hide on cancellation/weapon/death/reset',()=>{
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,2,.1,100);camera.position.set(0,10,20);camera.lookAt(0,0,0);camera.updateMatrixWorld();
 const w={...world,camera,areaId:'westminster',lineClear:()=>true},g=game();g.world=w;g.player.dodgeUntil=g.player.hurtUntil=0;g.pistol.magazine=6;g.pistol.nextFireAt=g.pistol.reloadingUntil=0;g.enemies=[{id:1,hp:40,pos:{x:0,z:4},radius:.4}];
 const fx=createEffects(scene,w,null,()=>null,{getView:e=>({root:{scale:{y:1.67*(e.mobSize??1)}}})}),marker=scene.children.find(o=>o.name==='Pistol aim marker'),geometries=marker.children.map(o=>o.geometry),materials=marker.children.map(o=>o.material);
 const cross=geometries[1].getAttribute('position');assert.ok(Math.abs(cross.getY(0))<.03&&cross.getX(0)<-.2&&cross.getX(1)>.2,'horizontal cross stroke spans centre');assert.ok(cross.getY(6)<-.2&&cross.getY(8)>.2,'vertical cross stroke spans centre');
 for(let i=0;i<60;i++){const factor=[.85,1.15,1][i%3],height=i%2?852:393;g.enemies[0].mobSize=factor;fx.update(g,{visibleIds:[1],viewportHeight:height});assert.equal(marker.position.y,1.15*1.67*factor);assert.ok(Math.abs(marker.scale.x-2*24*marker.position.distanceTo(camera.position)/(height*camera.projectionMatrix.elements[5]))<1e-12);assert.equal(marker.userData.targetId,1);assert.ok(marker.quaternion.equals(camera.quaternion));assert.equal(marker.children.length,3);assert.deepEqual(marker.children.map(o=>o.geometry),geometries);assert.deepEqual(marker.children.map(o=>o.material),materials);}
 assert.equal(marker.children[2].visible,true);g.pistol.magazine=0;fx.update(g);assert.equal(marker.position.y,1.15*1.67*g.enemies[0].mobSize);assert.equal(marker.userData.targetId,1);assert.equal(marker.userData.ready,false);assert.equal(marker.children[2].visible,true);assert.ok(materials[1].opacity>=.6);
 fx.update(g,{paused:true});assert.equal(marker.visible,false);g.pistol.magazine=6;fx.update(g);fx.clearPistolFeedback();assert.equal(marker.visible,false);assert.equal(marker.userData.targetId,null);
 for(const mode of ['holster','death','reset']){g.pistol.equipped=true;g.player.hp=150;fx.update(g);if(mode==='holster')g.pistol.equipped=false;if(mode==='death')g.player.hp=0;if(mode==='reset')fx.reset();else fx.update(g);assert.equal(marker.visible,false);}
 let disposed=0;for(const resource of [...geometries,...materials])resource.addEventListener('dispose',()=>disposed++);fx.dispose();assert.equal(disposed,6);assert.equal(scene.children.length,0);
});

test('slow displayed frames preserve short feedback; only confirmed hit shows resolved marker',()=>{
 const scene=new THREE.Scene(),marker={hidden:true,style:{},textContent:''},fx=createEffects(scene,world,null,()=>null,{hitMarker:marker}),g=game();
 g.events=[shot];fx.events(g);fx.update(g);assert.equal(marker.hidden,true);fx.advance(1);fx.update(g);assert.ok(fx.pistolRecoil(g)>0,'slow wallgap is one capped presentation step');assert.ok(fx.snapshot().activeTracers>0);assert.equal(fx.snapshot().muzzleFlash,true);
 g.events=[{...hit,blocked:true},{...hit,amount:0}];fx.events(g);fx.update(g);assert.equal(marker.hidden,true);
 g.events=[hit];fx.events(g);fx.update(g);assert.equal(marker.textContent,'HIT');assert.equal(marker.hidden,false);assert.equal(fx.snapshot().hitConfirmation.life,.2);
 fx.advance(1);fx.update(g);assert.equal(marker.hidden,false);assert.equal(fx.snapshot().activeParticles,8);
 g.events=[hit,{type:'death',actor:victim}];fx.events(g);fx.update(g);assert.equal(marker.textContent,'DOWN');fx.clearPistolFeedback();assert.equal(marker.hidden,true);fx.dispose();
});

test('offscreen free crosshair stays visible at portrait edge without advertising a target',()=>{
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,393/852,.1,100);camera.position.set(0,10,20);camera.lookAt(0,0,0);camera.updateMatrixWorld();const w={...world,camera,areaId:'westminster',lineClear:()=>true},g=game();g.world=w;g.player.pos={x:50,z:0};g.player.facing={x:1,z:0};g.mobileAiming=true;g.pistol.magazine=6;g.pistol.nextFireAt=g.pistol.reloadingUntil=0;g.player.hurtUntil=g.player.dodgeUntil=0;
 const fx=createEffects(scene,w);fx.update(g,{viewportWidth:393,viewportHeight:852});const marker=scene.getObjectByName('Pistol aim marker'),p=marker.position.clone().project(camera);assert.equal(marker.visible,true);assert.equal(marker.userData.targetId,null);assert.equal(marker.userData.edge,true);assert.ok(Math.abs(p.x)<=1-52/393+1e-9&&Math.abs(p.y)<=1-52/852+1e-9);assert.equal(marker.children[2].visible,true);fx.dispose();
});
