import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import * as T from'three';import{createGame,attack,stepGame}from'../src/combat.js';import{createHollowEncounter}from'../src/hollow-encounter.js';import{createEffects}from'../src/effects.js';
const w=clear=>({areaId:'westminster',layout:{characterScale:1.265},spawn:{x:0,z:0},move:(p,d)=>({x:p.x+d.x,z:p.z+d.z}),lineClear:()=>clear,geometry:{clear:()=>true}}),opts={pilot:'donor-knife',encounter:createHollowEncounter({rig:'hollow-scavenger',weapon:'knife',contactRig:'hero',bodyScale:1}),rat:true,dog:true,roach:true,supplies:true,areaResidents:true,openingGroup:false};
test('rat factor3 applies only in descriptor; dog2x/roach3x remain independently configured and actor mass/stat fields stay approved',()=>{const m=JSON.parse(fs.readFileSync(new URL('../public/assets/manifest-hollow.json',import.meta.url)));assert.equal(m.models['original-rat'].scale,3);assert.equal(m.models['original-dog'].scale,2);assert.equal(m.models['original-roach'].scale,3);assert.equal(m.models.vagrant.scale,1);const g=createGame(w(true),opts),r=g.enemies.find(e=>e.rig==='original-rat');assert.deepEqual([r.mobSize,r.bodyScale,r.radius,r.combatScale,r.hp,r.moveSpeed],[1,1,1.09,g.player.combatScale,20,2.1]);assert.equal(r.contactGoalReach,1.050307904880233);assert.equal(m.models['original-rat'].sha256,'4aa89380963ea3523a3bea05427ae8b54cc0104e656a1ec42cfef5e18cbc7e83');});
test('ordinary Slash selects native Low at real enlarged legal boundary without granting damage; blocked/hidden/far targets reject',()=>{for(const [distance,clear,visible,expected]of [[1.49,true,true,true],[1.49,false,true,false],[1.49,true,false,false],[3,true,true,false]]){const g=createGame(w(clear),opts),r=g.enemies.find(e=>e.rig==='original-rat');g.enemies=[r];Object.assign(r,{pos:{x:0,z:distance},home:null,ready:100});g.player.pos={x:0,z:0};g.player.facing={x:1,z:0};assert(attack(g,'slash',g.player.facing,visible?[r.id]:[]));assert.equal(g.player.swing.moveId==='rat_low',expected);if(expected){assert.equal(g.player.swing.lowTargetId,r.id);assert.deepEqual(g.player.swing.dir,{x:0,z:1});}for(let i=0;i<54;i++)stepGame(g);assert.equal(r.hp,20,'potential selection cannot grant a mesh hit');}});
test('animal hit particles use actual body-height times displayed root once',()=>{for(const [rig,base,factor]of [['original-rat',.18,3],['original-dog',.35,1],['original-roach',.08,3]]){const scene=new T.Scene(),rootScale=1.6729625*factor,actor={id:1,rig,pos:{x:0,z:0},mobSize:1},fx=createEffects(scene,{toRender:(p,h=0)=>new T.Vector3(p.x,h,-p.z)},null,undefined,{getView:()=>({root:{scale:{y:rootScale}}})});fx.events({pilot:'donor-knife',player:{id:0},time:1,events:[{type:'hit',actor,amount:10}]});const mat=new T.Matrix4();scene.getObjectByName('Combat pooled particles').getMatrixAt(0,mat);assert.ok(Math.abs(new T.Vector3().setFromMatrixPosition(mat).y-base*rootScale)<1e-6);fx.dispose();assert.equal(scene.children.length,0);}});

test('enlarged rat bite stroke uses measured potential front reach while player Low stays unscaled',()=>{for(const [moveId,actor,radius]of [['rat_bite',{id:1,kind:0,rig:'original-rat',contactGoalReach:1.050307904880233,pos:{x:0,z:0}},1.050307904880233],['rat_low',{id:0,kind:-1,pos:{x:0,z:0}},1.2]]){const scene=new T.Scene(),fx=createEffects(scene,{toRender:(p,h=0)=>new T.Vector3(p.x,h,-p.z)});fx.events({pilot:'donor-knife',time:1,events:[{type:'strike',actor,moveId,dir:{x:0,z:1}}]});const a=scene.children.find(o=>o.isLine).geometry.attributes.position;let max=0;for(let i=0;i<a.count;i++){assert.ok(Math.abs(a.getY(i)-.15)<1e-7);max=Math.max(max,Math.hypot(a.getX(i),a.getZ(i)));}assert.ok(Math.abs(max-radius)<1e-6);fx.dispose();}});

test('mixed eligible cohort keeps a single target identity through Slash animation and direction',()=>{
 for(const humanDistance of [1.543,3]){const g=createGame(w(true),opts),rat=g.enemies.find(e=>e.rig==='original-rat'),human=g.enemies.find(e=>e.placementKey==='westminster-roamer-1');g.enemies=[rat,human];g.player.pos={x:0,z:0};assert.equal(g.player.combatScale,1.265);Object.assign(rat,{pos:{x:0,z:2.118},home:null});Object.assign(human,{pos:{x:humanDistance,z:0},mobSize:1.15,bodyScale:1,combatScale:1.265*1.15,home:null});assert(attack(g,'slash',{x:0,z:1}));if(humanDistance===1.543){assert.notEqual(g.player.swing.moveId,'rat_low');assert.equal(g.player.swing.lowTargetId,undefined);assert.deepEqual(g.player.swing.dir,{x:1,z:0});}else{assert.equal(g.player.swing.moveId,'rat_low');assert.equal(g.player.swing.lowTargetId,rat.id);assert.deepEqual(g.player.swing.dir,{x:0,z:1});}}
});
