import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{createGame,stepGame}from'../src/combat.js';import{createHollowEncounter}from'../src/hollow-encounter.js';import{travelTo}from'../src/travel.js';import{pistolCue}from'../src/pistol-targeting.js';import{AREA_MOB_SPAWNS}from'../src/area-mob-spawns.js';import{encodeRun,restoreRun,applySavedRun}from'../src/pistol-save.js';
const opts={pilot:'donor-knife',encounter:createHollowEncounter({rig:'hollow-scavenger',weapon:'knife',contactRig:'hero',bodyScale:1}),rat:true,dog:true,roach:true,pistol:true,supplies:true,finishers:true,areaResidents:true,openingGroup:false},world=(area='westminster')=>({areaId:area,layout:{characterScale:1.265},spawn:{x:0,z:-6},move:(p,d)=>({x:p.x+d.x,z:p.z+d.z}),lineClear:()=>true,geometry:{clear:()=>true}});
test('roach replaces only West2, keeps native placement/protected rewards and saved issued-key absence',async()=>{const w=world(),g=createGame(w,opts),r=g.enemies.find(e=>e.rig==='original-roach'),p=AREA_MOB_SPAWNS.westminster.find(p=>p.key==='westminster-roamer-2');assert.equal(g.enemies.length,6);assert.equal(r.placementKey,p.key);assert.deepEqual(r.pos,p.pos);assert.deepEqual(r.home,p.pos);assert.deepEqual(r.patrol,p.patrol);assert.deepEqual([r.hp,r.radius,r.mobSize,r.bodyScale,r.moveSpeed],[20,.53,1,1,1.8]);assert.equal(g.enemies.find(e=>e.placementKey==='westminster-roamer-4').rig,'original-rat');assert.equal(g.enemies.find(e=>e.placementKey==='westminster-roamer-6').rig,'original-dog');g.supplies.issued=[p.key];const f=createGame(world(),opts);applySavedRun(f,restoreRun(f,encodeRun(g)));assert.equal(f.enemies.length,5);assert(!f.enemies.some(e=>e.placementKey===p.key));const ew=world('east'),e=createGame(ew,opts);e.supplies.issued=[p.key];ew.loadArea=async id=>{ew.areaId=id;return{x:0,z:-6}};assert(!e.enemies.some(e=>e.rig==='original-roach'));await travelTo(e,{areaId:'westminster'});assert(!e.enemies.some(e=>e.placementKey===p.key));assert.deepEqual(e.supplies.pending,[]);});
test('roach attack accepts real-root legal spacing despite goal offset greater than rat cap; commits one native bite',()=>{const g=createGame(world(),opts),r=g.enemies.find(e=>e.rig==='original-roach');g.enemies=[r];g.player.pos={x:0,z:0};Object.assign(r,{home:null,alerted:true,pos:{x:0,z:.93},facing:{x:0,z:-1},ready:0});let calls=0,goal={x:0,y:.05,z:.48,face:150};g.ratContact={capture:()=>null,calf:()=>{calls++;return goal}};stepGame(g);assert.equal(r.swing.clip,'roach_bite');assert.deepEqual(r.swing.timing,{windup:15,active:6,recovery:15});assert.equal(r.swing.def.damage,4);assert.equal(r.swing.def.staminaDamage,4);assert.equal(r.swing.def.parryable,false);assert.equal(r.swing.native,true);assert.deepEqual(r.swing.calfGoal,goal);const dir={...r.facing};goal={x:.4,y:.05,z:0,face:137};for(let i=0;i<10;i++)stepGame(g);assert.equal(calls,1);assert.deepEqual(r.facing,dir);assert.equal(r.swing.calfGoal.face,150);});
test('roach native pistol cue is body-height and death is ordinary with preserved no-supply ledger',()=>{const g=createGame(world(),opts),r=g.enemies.find(e=>e.rig==='original-roach');g.enemies=[r];r.home=null;r.pos={x:0,z:4};g.player.pos={x:0,z:0};Object.assign(g.pistol,{collected:true,equipped:true,magazine:6});g.pistolUserFacing={x:0,z:1};assert.equal(pistolCue(g).height,.08);stepGame(g,{actions:['fire'],aim:{x:0,z:1}});assert.equal(r.hp,0);assert.equal(r.response.clip,'roach_death');assert.equal(r.response.ticks,48);assert.equal(r.finisher.recipeId,'ordinary');assert.deepEqual(g.supplies.issued,['westminster-roamer-2']);assert.deepEqual(g.supplies.pending,[]);const descriptor=JSON.parse(fs.readFileSync(new URL('../public/assets/manifest-hollow.json',import.meta.url))).models['original-roach'];assert.deepEqual(descriptor.contact.calfBand,[.04,.075]);assert.equal(descriptor.contact.canines.length,2);});

test('only roach approach follows the currently visible foot before legal-root commitment',()=>{
 for(const [rig,area]of [['original-roach','westminster'],['original-dog','south']]){
  const g=createGame(world(area),opts),e=g.enemies.find(e=>e.rig===rig);g.enemies=[e];g.player.pos={x:0,z:0};Object.assign(e,{home:null,alerted:true,pos:{x:0,z:2},facing:{x:0,z:-1},ready:0});let calls=0;g.ratContact={capture:()=>null,calf:()=>{calls++;return{x:.5,y:.05,z:.5,face:137}}};stepGame(g);
  assert.equal(e.swing,null);assert.ok(e.pos.z<2);if(rig==='original-roach'){assert.equal(calls,1);assert.ok(e.pos.x>0);}else{assert.equal(calls,0);assert.equal(e.pos.x,0);}
 }
});

test('missing visible roach foot preserves root approach outside legal gap and denies attack without a goal',()=>{
 for(const distance of [2,.93]){const g=createGame(world(),opts),e=g.enemies.find(e=>e.rig==='original-roach');g.enemies=[e];g.player.pos={x:0,z:0};Object.assign(e,{home:null,alerted:true,pos:{x:0,z:distance},facing:{x:0,z:-1},ready:0});let calls=0;g.ratContact={capture:()=>null,calf:()=>{calls++;return null}};stepGame(g);assert.equal(calls,1);assert.equal(e.swing,null);assert.equal(e.pos.x,0);if(distance===2)assert(e.pos.z<2);else assert.equal(e.pos.z,distance);}
});
