import test from 'node:test';import assert from 'node:assert/strict';import {createGame,stepGame} from '../src/combat.js';
const encounter={id:'hollow-scavengers',character:{rig:'hollow-scavenger',weapon:'knife',contactRig:'hero',bodyScale:1}};
function fresh(cycle='B',area='east'){return createGame({areaId:area,layout:{characterScale:1.265},spawn:{x:30,z:-6},move:(p,d)=>({x:p.x+d.x,z:p.z+d.z}),lineClear:()=>true},{pilot:'donor-knife',encounter,rat:true,dog:true,roach:true,pistol:true,supplies:true,finishers:true,animalVariants:true,animalCycle:cycle,areaResidents:true,openingGroup:false});}
function setup(gap=4){const g=fresh(),e=g.enemies.find(e=>e.placementKey==='east-roamer-2');g.enemies=[e];Object.assign(e,{pos:{x:0,z:0},home:{x:0,z:0},patrol:[{x:0,z:0},{x:2,z:0}],patrolIndex:1,facing:{x:0,z:1}});g.player.pos={x:0,z:gap};return{g,e};}
test('territory binding is exact CycleB East2 and preserves native stats/other area populations',()=>{for(const cycle of ['A','B'])for(const area of ['east','south','westminster']){const g=fresh(cycle,area);assert.equal(g.enemies.length,area==='westminster'?6:9);const selected=g.enemies.filter(e=>e.animalRecipe==='roach-nest-guard'&&e.residentIntent?.companionDistance===0);assert.deepEqual(selected.map(e=>e.placementKey),cycle==='B'&&area==='east'?['east-roamer-2']:[]);if(selected.length)assert.deepEqual([selected[0].hp,selected[0].radius,selected[0].moveSpeed,selected[0].recoveryDelay],[20,1.59,1.8,0]);}});
test('actual loop wake has 4m boundary/playerLOS and never creates pack state',()=>{for(const [gap,los,wake]of [[4,true,true],[4.0001,true,false],[3,false,false]]){const{g,e}=setup(gap);g.world.lineClear=()=>los;stepGame(g);assert.equal(e.alerted,wake);assert.equal(e.packCompanions,undefined);assert.equal(e.packMovement,undefined);}});
test('5m home breach clears alert before ordinary return, blocked movement holds, arrival clears',()=>{for(const blocked of [false,true]){const{g,e}=setup(5.001);e.alerted=true;e.pos={x:0,z:2};e.facing={x:0,z:-1};g.bridgeSteering={steer(){throw Error('player pursuit used during return')},reset(){}};if(blocked)g.world.move=p=>({...p});stepGame(g);assert.equal(e.alerted,false);assert.equal(e.returning,true);assert.equal(e.swing,null);assert.equal(e.hp,20);assert(blocked?e.pos.z===2:e.pos.z<2);e.pos={x:0,z:.19};stepGame(g);assert.equal(e.returning,false);}});
test('existing native scaled bite and recovery retain priority over leash',()=>{const{g,e}=setup(1.99);g.ratContact={capture:()=>null,calf:()=>({x:0,z:.4,y:.16,face:150})};stepGame(g);assert.equal(e.swing?.clip,'roach_bite_scaled');assert.equal(e.swing.def.damage,4);const swing=e.swing;g.player.pos={x:0,z:6};stepGame(g);assert.equal(e.swing,swing);assert.equal(e.alerted,true);e.swing=null;e.recoverUntil=g.time+1;const before={...e.pos};stepGame(g);assert.deepEqual(e.pos,before);assert(e.alerted);e.recoverUntil=0;stepGame(g);assert.equal(e.alerted,false);});
test('baseline roach stays ordinary and territory false LOS cannot start a new bite',()=>{const a=fresh('A').enemies.find(e=>e.placementKey==='east-roamer-2');assert.equal(a.residentIntent,undefined);const{g,e}=setup(6);e.alerted=true;e.pos={x:0,z:2};g.world.lineClear=()=>false;stepGame(g);assert.equal(e.returning,true);assert.deepEqual(e.pos,{x:0,z:2});assert.equal(e.swing,null);});
