import assert from 'node:assert/strict';
import {controlledEntry,readState,ordinaryInput,waitSimulation,aimAt} from './scenarios.mjs';
import {near} from './gaunt.mjs';import {pause,resume} from './crown.mjs';
async function paused(page){if(!await page.evaluate(()=>document.getElementById('menu').open))await pause(page);}
async function enter(page,areaId){await paused(page);return controlledEntry(page,{areaId});}
async function role(page,key){return page.evaluate(key=>{const q=__qa,g=q.game,e=g.enemies.find(e=>e.placementKey===key),v=q.actors.views.get(e.id),calf=g.ratContact?.calf(g,e);return{key,id:e.id,time:g.time,tick:g.tick,hp:e.hp,radius:e.radius,rig:e.rig,recipe:e.animalRecipe,role:e.animalRole,intent:e.residentIntent,moveSpeed:e.moveSpeed,recoveryDelay:e.recoveryDelay,wokeAt:e.wokeAt,alerted:e.alerted,returning:e.returning,home:{...e.home},pos:{...e.pos},facing:{...e.facing},ready:e.ready,hurtUntil:e.staggerUntil,completed:e.completedAttack,swing:e.swing?{native:e.swing.native,action:e.swing.action,clip:e.swing.clip,start:e.swing.start,end:e.swing.end,timing:e.swing.timing,damage:e.swing.def.damage}:null,calf,calfGap:calf?Math.hypot(calf.x-e.pos.x,calf.z-e.pos.z):null,goalReach:e.contactGoalReach,player:{pos:{...g.player.pos},hp:g.player.hp},clip:(v?.motion?.native??v?.motion)?.currentClip,homeDistance:Math.hypot(e.pos.x-e.home.x,e.pos.z-e.home.z),playerHomeDistance:Math.hypot(g.player.pos.x-e.home.x,g.player.pos.z-e.home.z)};},key);}
export async function roleRows(page,{cycle}={}){await paused(page);if(cycle==='B'&&await page.evaluate(()=>__qa.game.animalCycle)==='A'){await ordinaryInput(page,()=>page.click('#retry'),{reset:true,label:'roles-normal-retry-cycle-b'});await paused(page);}const rows=[];for(const area of ['east','south']){const entry=await enter(page,area);const row=await page.evaluate(()=>{const q=__qa,g=q.game;return{area:q.world.areaId,cycle:g.animalCycle,actors:g.enemies.map(e=>({key:e.placementKey,rig:e.rig,hp:e.hp,radius:e.radius,recipe:e.animalRecipe,role:e.animalRole,intent:e.residentIntent,moveSpeed:e.moveSpeed,recoveryDelay:e.recoveryDelay,home:e.home,pos:e.pos,humanBody:e.humanBodyRecipe}))};});assert.equal(row.cycle,cycle);assert.equal(row.actors.length,10);const selected=row.actors.filter(e=>e.role),expected=area==='east'?(cycle==='A'?['east-roamer-7']:['east-roamer-4','east-roamer-7','east-roamer-9']):(cycle==='A'?[]:['south-roamer-2','south-roamer-3']);assert.deepEqual(selected.map(e=>e.key),expected);for(const e of selected){assert.equal(e.hp,e.rig==='original-dog'?30:20);assert.deepEqual(Object.keys(e.role.parameters).sort(),['moveSpeed','recoveryDelay']);}if(cycle==='B'&&area==='east'){const stocky=selected.find(e=>e.key==='east-roamer-9');assert.equal(stocky.moveSpeed,2.21);assert.equal(stocky.recoveryDelay,.15);assert.equal(row.actors.find(e=>e.key==='east-roamer-2').intent.homeLeash,5);}if(cycle==='B'&&area==='south'){assert.equal(selected.find(e=>e.key==='south-roamer-2').moveSpeed,1.9800000000000002);assert.equal(selected.find(e=>e.key==='south-roamer-3').intent.homeLeash,5);}rows.push({entry,row});}return{rows,scope:'Actual two-cycle exact five binding construction/once-only parameters and existing populations; body/rig/HP/radius preserved. Prior Gaunt/Pack/territory geometry and native proofs reused.'};}
export async function roleRetreat(page,{key,area,screenshotPath}={}){await enter(page,area);const before=await role(page,key),gap=before.radius+.4+.05,entry=await near(page,key,gap);await resume(page);await aimAt(page,before.id);await page.keyboard.down('f');let start,ended,after;try{
 const handle=await waitSimulation(page,key=>{const q=__qa,e=q.game.enemies.find(e=>e.placementKey===key),s=e.swing;if(!s?.native||s.action!=='bite')return false;return{time:q.game.time,start:s.start,end:s.end,clip:s.clip,timing:s.timing,ready:e.ready,damage:s.def.damage};},key,{seconds:6,label:'roles-real-native-bite-start'});start=await handle.jsonValue();
 await waitSimulation(page,({key,end})=>{const q=__qa,e=q.game.enemies.find(e=>e.placementKey===key);return e.completedAttack?.uninterrupted&&e.completedAttack.endedAt===end&&!e.swing;},{key,end:start.end},{seconds:3,label:'roles-normal-end-not-cancel'});ended=await role(page,key);
 const handle2=await waitSimulation(page,({key,pos,player,end})=>{const q=__qa,e=q.game.enemies.find(e=>e.placementKey===key),p=q.game.player.pos,dx=e.pos.x-pos.x,dz=e.pos.z-pos.z,gap=Math.hypot(e.pos.x-p.x,e.pos.z-p.z),old=Math.hypot(pos.x-player.x,pos.z-player.z);if(e.completedAttack?.endedAt!==end||e.swing)return false;const away={x:e.pos.x-p.x,z:e.pos.z-p.z},length=Math.hypot(away.x,away.z),n=q.world.move(e.pos,{x:away.x/length*e.moveSpeed/60,z:away.z/length*e.moveSpeed/60},e.radius);if(gap-old>.01&&(dx*away.x+dz*away.z)>0)return{kind:'withdraw',time:q.game.time,gap,old,delta:{x:dx,z:dz}};if(q.game.time-end>.2&&Math.hypot(n.x-e.pos.x,n.z-e.pos.z)<1e-8&&Math.hypot(dx,dz)<1e-8)return{kind:'registered-blocked-hold',time:q.game.time,gap,old};return false;},{key,pos:ended.pos,player:ended.player.pos,end:start.end},{seconds:1,label:'roles-real-end-withdraw-or-registered-hold'});after=await role(page,key);after.movement=await handle2.jsonValue();assert.equal(after.hp,before.hp);assert.equal(after.moveSpeed,before.moveSpeed);assert.equal(after.recoveryDelay,before.recoveryDelay);assert.equal(after.completed.uninterrupted,true);assert.equal(after.swing,null);if(screenshotPath)await page.screenshot({path:screenshotPath});
 }catch(error){error.diagnostic={role:await role(page,key),before,start,ended,after};throw error;}finally{await page.keyboard.up('f');}await paused(page);return{before,entry,start,ended,after,screenshotPath,scope:'Actual native bite normal-END record triggers backward withdrawal or actual registered blocked hold; physical damage is observed separately, no new contact/hitbox/fullfight claim.'};}
export async function roleTravel(page){const key='east-roamer-7';await enter(page,'east');const before=await role(page,key),parkedAt=before.time;const out=await enter(page,'south');await resume(page);await waitSimulation(page,t=>__qa.game.time-t>.3,parkedAt,{seconds:1,label:'roles-ordinary-away-clock'});await paused(page);const away=await readState(page);const entry=await enter(page,'east');const restored=await role(page,key);assert.equal(restored.id,before.id);assert.equal(restored.moveSpeed,2.1);assert.equal(restored.completed,null);assert.equal(restored.swing,null);assert.equal(restored.hp,before.hp);if(Number.isFinite(before.wokeAt))assert(Math.abs(restored.wokeAt-before.wokeAt-(away.time-parkedAt))<1e-8);return{before,out,away,entry,restored,scope:'Actual travel cancels transient completion/swing, preserves role/HP/params and shifts wake epoch once through normal parked elapsed time.'};}
export async function stockyRecovery(page){const key='east-roamer-9';await enter(page,'east');const before=await role(page,key),entry=await near(page,key,before.radius+.4+.05);await resume(page);await aimAt(page,before.id);await page.keyboard.down('f');let first,second;try{const a=await waitSimulation(page,key=>{const q=__qa,e=q.game.enemies.find(e=>e.placementKey===key),s=e.swing;return s?.native?{time:q.game.time,start:s.start,end:s.end,timing:s.timing,clip:s.clip,damage:s.def.damage,ready:e.ready}:false;},key,{seconds:6,label:'stocky-real-first-bite'});first=await a.jsonValue();assert.deepEqual(first.timing,{windup:18,active:6,recovery:24});assert.equal(first.damage,8);assert(Math.abs(first.ready-first.end-.15)<1e-8);const b=await waitSimulation(page,({key,start})=>{const q=__qa,e=q.game.enemies.find(e=>e.placementKey===key),s=e.swing;return s?.native&&s.start>start?{time:q.game.time,start:s.start,end:s.end,ready:e.ready,clip:s.clip}:false;},{key,start:first.start},{seconds:3,label:'stocky-real-next-bite-cadence'});second=await b.jsonValue();assert(second.start>=first.ready-1e-8);assert(Math.abs(second.ready-second.end-.15)<1e-8);}catch(error){error.diagnostic={role:await role(page,key),before,first,second};throw error;}finally{await page.keyboard.up('f');}await paused(page);return{before,entry,first,second,after:await role(page,key),scope:'Actual native48-tick bite and subsequent start retain damage8 and add exactly.15 recovery once; cautious2.21 speed, no new lunge.'};}
export async function skitterRhythm(page){const key='south-roamer-2';await enter(page,'south');const before=await role(page,key),entry=await near(page,key,4);await resume(page);await aimAt(page,before.id);const handle=await waitSimulation(page,key=>{const q=__qa,e=q.game.enemies.find(e=>e.placementKey===key);if(!Number.isFinite(e.wokeAt))return false;const phase=(q.game.time-e.wokeAt)%.8,row={time:q.game.time,wokeAt:e.wokeAt,phase,pos:{...e.pos},swing:e.swing?{start:e.swing.start,end:e.swing.end,clip:e.swing.clip}:null,hurt:q.game.time<e.staggerUntil};const trace=window.__qaSkitterTrace??=[];if(!trace.length||trace.at(-1).time!==row.time)trace.push(row);if(q.game.time-e.wokeAt>2.2)return trace;return false;},key,{seconds:4,label:'skitter-actual-three-second-rhythm'});const trace=await handle.jsonValue();await paused(page);let moved=0,held=0,activeDuringPause=0;for(let i=1;i<trace.length;i++){const a=trace[i-1],b=trace[i],d=Math.hypot(b.pos.x-a.pos.x,b.pos.z-a.pos.z);if(!a.swing&&!b.swing&&!a.hurt&&!b.hurt&&a.phase<.4&&b.phase<.4&&b.phase>=a.phase&&d>.001)moved++;if(!a.swing&&!b.swing&&!a.hurt&&!b.hurt&&a.phase>.47&&b.phase>.47&&b.phase>=a.phase&&d<1e-8)held++;if(a.swing&&b.swing&&a.swing.start===b.swing.start&&b.phase>.45&&b.time>a.time)activeDuringPause++;}assert(moved>0&&held>0,'actual approach must move in burst and stay still in pause');const after=await role(page,key);assert.equal(after.wokeAt,trace[0].wokeAt);assert.equal(after.moveSpeed,1.9800000000000002);return{before,entry,trace,moved,held,activeDuringPause,after,scope:'Actual first wake epoch/1.98 movement and.45/.35 approach rhythm; native active-swing continuation reported only when sampled. Source actual-domain cancellation/swing guards separately verified.'};}
export async function ratNestTerritory(page){
 const key='south-roamer-3';await enter(page,'south');const before=await role(page,key);let entry,woke,returning,arrived;
 try{
  const setup=await page.evaluate(key=>{const q=__qa,g=q.game,e=g.enemies.find(e=>e.placementKey===key),p={x:e.home.x,z:e.home.z-3};if(!q.world.geometry.clear(p,g.player.radius)||!q.world.lineClear(e.pos,p)||g.enemies.some(o=>o!==e&&Math.hypot(p.x-o.pos.x,p.z-o.pos.z)<g.player.radius+o.radius+.02))throw Error('World South RatNest witness entry unavailable');const at=q.world.geometry.point(p);return{areaId:'south',entryPoint:{x:at.x,y:at.y}};},key);
  entry=await controlledEntry(page,setup);await resume(page);await aimAt(page,before.id);
  await waitSimulation(page,key=>__qa.game.enemies.find(e=>e.placementKey===key).alerted,key,{seconds:2,label:'ratnest-real-wake-within-four'});
  await waitSimulation(page,key=>{const e=__qa.game.enemies.find(e=>e.placementKey===key);return Math.hypot(e.pos.x-e.home.x,e.pos.z-e.home.z)>.5;},key,{seconds:2,label:'ratnest-actual-outbound-movement'});woke=await role(page,key);
  await page.keyboard.down('s');try{await waitSimulation(page,key=>{const q=__qa,e=q.game.enemies.find(e=>e.placementKey===key);return Math.hypot(q.game.player.pos.x-e.home.x,q.game.player.pos.z-e.home.z)>5.1;},key,{seconds:2,label:'ratnest-ordinary-player-outside-five'});}finally{await page.keyboard.up('s');}
  await waitSimulation(page,key=>!__qa.game.enemies.find(e=>e.placementKey===key).alerted,key,{seconds:2,label:'ratnest-clears-alert-and-native-return'});returning=await role(page,key);
  await waitSimulation(page,key=>{const e=__qa.game.enemies.find(e=>e.placementKey===key);return !e.returning&&!e.alerted&&Math.hypot(e.pos.x-e.home.x,e.pos.z-e.home.z)<.25;},key,{seconds:4,label:'ratnest-native-home-arrival'});await paused(page);arrived=await role(page,key);
  assert.equal(arrived.completed,null);assert.equal(arrived.wokeAt,null);assert.equal(arrived.hp,20);assert.equal(arrived.moveSpeed,2.1);assert(woke.homeDistance>arrived.homeDistance);
 }catch(error){error.diagnostic={before,entry,woke,returning,arrived,role:await role(page,key),world:await page.evaluate(key=>{const q=__qa,g=q.game,e=g.enemies.find(e=>e.placementKey===key),calf=g.ratContact?.calf(g,e),goal=calf??g.player.pos,dx=goal.x-e.pos.x,dz=goal.z-e.pos.z,n=Math.hypot(dx,dz);return{playerClear:q.world.geometry.clear(g.player.pos,g.player.radius),npcClear:q.world.geometry.clear(e.pos,e.radius),calfBand:q.actors.views.get(e.id)?.description.contact?.calfBand,lineClear:q.world.lineClear(e.pos,g.player.pos),calfLineClear:calf?q.world.lineClear(e.pos,calf):null,step:n?q.world.move(e.pos,{x:dx/n*e.moveSpeed/60,z:dz/n*e.moveSpeed/60},e.radius):null,peers:g.enemies.filter(o=>o!==e&&Math.hypot(o.pos.x-e.pos.x,o.pos.z-e.pos.z)<4).map(o=>({key:o.placementKey,pos:o.pos,radius:o.radius,hp:o.hp})),events:window.__qaEvents.slice(-30)};},key)};throw error;}
 return{before,entry,woke,returning,arrived,scope:'Actual within4 wake/outbound, ordinary player movement beyond5 clears alert and normal radius-aware return reaches home; no blocked-route/body relocation promise.'};
}
export async function rolesColdRetry(page){await page.reload();await page.tap('#enter');await page.waitForFunction(()=>window.__qa?.game&&document.getElementById('entry').hidden,null,{timeout:90000});await paused(page);await enter(page,'east');const cold=await role(page,'east-roamer-9');assert.equal(cold.moveSpeed,2.21);assert.equal(cold.recoveryDelay,.15);const snapshot=await readState(page);assert(!JSON.stringify(snapshot.saved).includes('completedAttack'));const fresh=await ordinaryInput(page,()=>page.click('#retry'),{reset:true,label:'roles-normal-retry-to-cycle-a'});await paused(page);const retry=await readState(page);assert.equal(retry.hp,150);assert.equal(retry.enemies.length,7);await enter(page,'east');const baseline=await role(page,'east-roamer-9'),sewer=await role(page,'east-roamer-7');assert.equal(baseline.role,undefined);assert.equal(baseline.moveSpeed,2.6);assert.equal(baseline.recoveryDelay,0);assert.equal(sewer.role.recipeId,'rat-sewer');return{cold,snapshot,fresh,retry,baseline,sewer,scope:'Existing normal coldB constructor applies params once; ordinary Retry A returns baselineStocky and retainedAB Sewer, no new saved clocks or alternatewriter.'};}
