import assert from 'node:assert/strict';import {controlledEntry,waitSimulation,readState,ordinaryInput,equipPistol,lowStrike,legal,aimAt,waitEvent,holsterPistol} from './scenarios.mjs';import {near,shootGaunt} from './gaunt.mjs';
export async function pause(page){if(await page.evaluate(()=>document.getElementById('menu').open))return;await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);}
export async function resume(page){return ordinaryInput(page,()=>page.click('#close-menu'),{label:'crown-resume'});}
export async function stash(page){await controlledEntry(page,{areaId:'westminster'});const entry=await page.evaluate(()=>{const q=__qa,p=q.game.pistol.pickupPos,a=q.world.geometry.point(p);return{areaId:'westminster',entryPoint:{x:a.x,y:a.y}};});await controlledEntry(page,entry);await resume(page);const equip=await equipPistol(page);await pause(page);return equip;}
export async function inspect(page,key){return page.evaluate(key=>{const q=__qa,g=q.game,e=[...g.enemies,...g.corpses].find(e=>e.placementKey===key),v=q.actors.views.get(e.id),part=v.model.getObjectByName('Prepared Split Crown');return{time:g.time,key,hp:e.hp,recipe:e.finisher,support:e.finisherSupport,partUntil:e.finisherPartsUntil??0,headUntil:e.finisherHeadUntil??0,stats:v.finisher?.stats(),age:v.finisherAge,pose:v.finisher?.pose(v.finisherAge??0),clip:(v.motion.native??v.motion).currentClip,restored:!!v.restoredCorpse,crown:part?{parent:part.parent?.name,halves:part.children.length,visible:part.visible,rotations:part.children.map(p=>p.rotation.z)}:null,live:g.enemies.map(e=>({key:e.placementKey,pos:{...e.pos},hp:e.hp,clip:(q.actors.views.get(e.id)?.motion?.native??q.actors.views.get(e.id)?.motion)?.currentClip})),player:{pos:{...g.player.pos},hp:g.player.hp},ledger:structuredClone(g.supplies),saved:JSON.parse(localStorage.getItem('armagedom:area1-run:v1'))};},key);}
// Proven Crown kill sequence, reused by subsequent cutting finishers.
export async function humanKillSetup(page,key,{meleeEntry:entry,settleMelee}={}){
 const gunEntry=await near(page,key,3.5);await resume(page);const shot=await shootGaunt(page,key,25);
 // Holster at the existing safe pistol entry before an NPC can hit during UI dispatch.
 const holster=await holsterPistol(page);assert.equal(holster.after.weapon,'knife');await pause(page);
 const meleeEntry=entry?await controlledEntry(page,typeof entry==='function'?await entry(page):entry):await near(page,key,1.4);await resume(page);
 const approach=settleMelee?await settleMelee(page,key):null;
 const first=await lowStrike(page,{targetKey:key,move:'light_right',damage:10});await legal(page);
 return{key,gunEntry,shot,meleeEntry,approach,holster,first};
}
export async function cuttingKill(page,key,options={}){
 const setup=await humanKillSetup(page,key,options),beforeLethal=options.beforeLethal;
 const lethalPrerequisite=beforeLethal?await beforeLethal(page,key):null;
 const before=await readState(page),id=before.enemies.find(e=>e.key===key).id,point=await aimAt(page,id);
 await page.mouse.click(point.x,point.y);await waitEvent(page,{type:'attack',actor:0,move:'light_left'},before.events.length);await waitEvent(page,{type:'hit',actor:id,move:'light_left',amount:10},before.events.length);
 const second=await readState(page);assert(!second.enemies.some(e=>e.id===id));
 return{...setup,lethalPrerequisite,second};
}
export async function crownKill(page,{screenshotPath,keys=['westminster-roamer-1','westminster-roamer-3'],beforeLethal,preserveViewport=false}={}){
 await pause(page);const equipped=await stash(page),kills=[];
 for(const [i,key]of keys.entries()){
  const kill=await cuttingKill(page,key,i===1?{beforeLethal}:{});
  if(i===1){await waitSimulation(page,key=>{const q=__qa,e=q.game.corpses.find(e=>e.placementKey===key);return e&&q.actors.views.get(e.id)?.finisher?.stats().crownActive;},key,{seconds:2,label:'crown-actual-presentation-start'});
   if(screenshotPath){await page.setViewportSize({width:393,height:852});await page.waitForFunction(()=>__qa.world.width===393&&__qa.world.height===852);await page.screenshot({path:screenshotPath});}}
  await pause(page);const corpse=await inspect(page,key);assert.equal(corpse.hp,0);kills.push({...kill,corpse});
  if(i===0){assert.equal(corpse.recipe.recipeId,'ordinary');await resume(page);await legal(page);await equipPistol(page);await pause(page);}
 }
 const result=kills[1].corpse;assert.equal(result.recipe.recipeId,'split-crown');assert.equal(result.recipe.seconds,1);assert.deepEqual(result.recipe.parts,['crown']);assert.equal(result.stats.crownActive,true);assert.equal(result.stats.detached,false);assert.equal(result.stats.lethalVertexCopies,0);assert.equal(result.stats.crownPreparationError,null);assert(result.partUntil>result.time);assert.equal(result.headUntil,0);assert.equal(result.pose.clip,'Death_SplitCrown');assert.equal(result.crown.parent,'Head');assert.equal(result.crown.halves,2);if(!preserveViewport)await page.setViewportSize({width:1180,height:744});
 return{equipped,kills,result,screenshotPath,scope:'Two genuine pistol25 and knife10/10 kills select Crown through existing ordinal; reused preparation for subsequent cutting finishers.'};
}
export async function crownRestoreExpiry(page){const key='westminster-roamer-3',before=await inspect(page,key);await controlledEntry(page,{areaId:'east'});await controlledEntry(page,{areaId:'westminster'});const restored=await inspect(page,key);assert(restored.restored&&restored.stats.crownActive);assert.equal(restored.recipe.recipeId,'split-crown');assert.equal(restored.headUntil,0);assert(restored.partUntil>restored.time);assert.equal(restored.crown.parent,'Head');const entry=await page.evaluate(()=>{const q=__qa,a=q.world.geometry.point(q.game.pistol.pickupPos);return{areaId:'westminster',entryPoint:{x:a.x,y:a.y}};});await controlledEntry(page,entry);await resume(page);const movementBefore=await inspect(page,key),t=movementBefore.time;await page.keyboard.down('d');try{await waitSimulation(page,t=>__qa.game.time-t>.25,t,{seconds:1,label:'crown-independent-player-movement'});}finally{await page.keyboard.up('d');}const continued=await inspect(page,key);assert(Math.hypot(continued.player.pos.x-movementBefore.player.pos.x,continued.player.pos.z-movementBefore.player.pos.z)>.01);assert(continued.live.some(e=>{const before=movementBefore.live.find(p=>p.key===e.key);return before&&Math.hypot(e.pos.x-before.pos.x,e.pos.z-before.pos.z)>.01;}));assert(continued.time>restored.time);await waitSimulation(page,()=>{const q=__qa,e=q.game.corpses.find(e=>e.placementKey==='westminster-roamer-3');return q.actors.views.get(e.id).finisher.stats().expired&&e.finisherPartsUntil===0;},null,{seconds:6,label:'crown-normal-six-second-expiry'});await pause(page);const expired=await inspect(page,key);assert.equal(expired.crown,null);assert.equal(expired.stats.expired,true);assert.equal(expired.partUntil,0);assert.equal(expired.headUntil,0);assert.deepEqual(expired.ledger.issued.sort(),before.ledger.issued.sort());return{before,restored,movementBefore,continued,expired,scope:'Actual live parked corpse reconstruction and aged native pose, ordinary player movement/other actors continue, attached group expires at6s/releasescost; no corpse save schema.'};}
export async function crownColdRetry(page){await page.reload();await page.tap('#enter');await page.waitForFunction(()=>window.__qa?.game&&document.getElementById('entry').hidden,null,{timeout:90000});await pause(page);const cold=await readState(page);assert(!cold.enemies.some(e=>['westminster-roamer-1','westminster-roamer-3'].includes(e.key)));assert(cold.saved.supplies.issued.includes('westminster-roamer-1')&&cold.saved.supplies.issued.includes('westminster-roamer-3'));assert(!JSON.stringify(cold.saved).includes('finisherPartsUntil'));const fresh=await ordinaryInput(page,()=>page.click('#retry'),{reset:true,label:'crown-retry'});await pause(page);const retry=await readState(page);assert.equal(retry.hp,150);assert.equal(retry.corpses.length,0);assert.equal(retry.enemies.length,7);assert.deepEqual(retry.supplies.issued,[]);const prepared=await inspect(page,'westminster-roamer-1');assert(prepared.stats.crownPrepared);assert(!prepared.stats.crownActive);return{cold,fresh,retry,prepared,scope:'Existing stable West death filter/coldammo save and normal Retry disposes old Crown and prepares fresh eligible humans; no new saved cosmetics.'};}
