import assert from 'node:assert/strict';
import {controlledEntry,waitSimulation,readState,ordinaryInput,legal} from './scenarios.mjs';
import {near,shootGaunt} from './gaunt.mjs';import {pause,resume,stash,crownKill} from './crown.mjs';import {openedCutting} from './opened.mjs';import {pausedWorldImage} from './drone-height.mjs';
async function fxState(page,key){return page.evaluate(key=>{const q=__qa,g=q.game,e=g.corpses.find(e=>e.placementKey===key),v=e&&q.actors.views.get(e.id),pool=q.world.scene.getObjectByName('Combat feedback pool'),mesh=q.world.scene.getObjectByName('Combat pooled particles');return{time:g.time,tick:g.tick,menuOpen:document.getElementById('menu').open,fx:pool.userData.finisherImpact(),material:{depthTest:mesh.material.depthTest,depthWrite:mesh.material.depthWrite,renderOrder:mesh.renderOrder,capacity:mesh.count},recipe:e?.finisher,requested:v?.finisherRequestedRecipeId,age:v?.finisherAge,anchors:v?.finisher?.impactAnchors(v.finisherAge),restored:v?.restoredCorpse,player:{pos:{...g.player.pos},hp:g.player.hp},live:g.enemies.map(e=>({id:e.id,pos:{...e.pos}})),particleMatrices:Array.from(mesh.instanceMatrix.array),particleColors:mesh.instanceColor?Array.from(mesh.instanceColor.array):null};},key);}
function armCapture(page,key,recipeId,{peakAfter=null}={}){return waitSimulation(page,({key,recipeId,peakAfter})=>{const q=__qa,g=q.game,e=g.corpses.find(e=>e.placementKey===key),v=e&&q.actors.views.get(e.id),s=q.world.scene.getObjectByName('Combat feedback pool').userData.finisherImpact(),effect=s.effects.find(x=>x.recipeId===recipeId);if(!e||e.finisher?.recipeId!==recipeId||!effect||!s.activeParticles||peakAfter!==null&&s.poolTime-effect.startedAt<peakAfter)return false;if(document.getElementById('menu').open)throw Error('Finisher capture requires live ordinary play');document.getElementById('menu-button').click();if(!document.getElementById('menu').open)throw Error('Actual Menu Pause did not acknowledge');return{time:g.time,tick:g.tick,key,recipeId,fx:s,age:v.finisherAge};},{key,recipeId,peakAfter},{seconds:4,label:peakAfter===null?'impact-real-onset-pause':'impact-real-peak-pause'});}
async function imagesAndSettle(page,key,recipeId,promise,path){const start=await promise;const onset=await start.jsonValue(),before=await fxState(page,key),onsetImage=await pausedWorldImage(page,path+'-onset.png'),after=await fxState(page,key);assert.deepEqual(after,before);assert.equal(before.recipe.recipeId,recipeId);assert.equal(before.material.depthWrite,false);assert.equal(before.material.depthTest,true);assert.equal(before.material.capacity,48);
 const peakPromise=armCapture(page,key,recipeId,{peakAfter:.10});await resume(page);const peakStart=await peakPromise;const peak=await peakStart.jsonValue(),peakBefore=await fxState(page,key),peakImage=await pausedWorldImage(page,path+'-peak.png');assert.deepEqual(await fxState(page,key),peakBefore);
 await resume(page);await waitSimulation(page,()=>__qa.world.scene.getObjectByName('Combat feedback pool').userData.finisherImpact().bursts===0,null,{seconds:3,label:'impact-ordinary-finite-settle'});await pause(page);const settled=await fxState(page,key);assert.equal(settled.fx.reservedParticles,0);assert.equal(settled.fx.reservedTrails,0);return{onset,before,onsetImage,peak,peakBefore,peakImage,settled,scope:'Actual onset/peak and particles frozen with normal Menu Pause; modal overlay suppressed only in stills; ordinary resume/finite settle. Paused appearance, no moving/phone claim.'};}
export async function impactPistolHead(page,{output}={}){await pause(page);const equipment=await stash(page);const kills=[];let captured;
 for(const[area,key]of [['westminster','westminster-roamer-1'],['east','east-roamer-1']]){await controlledEntry(page,{areaId:area});const entry=await near(page,key,3.5);await resume(page);const first=await shootGaunt(page,key,25);await waitSimulation(page,()=>__qa.game.time>=__qa.game.pistol.nextFireAt&&!__qa.game.player.swing,null,{seconds:3,label:'impact-proven-pistol-cadence'});let promise;if(area==='east')promise=armCapture(page,key,'pistol-decapitation').catch(error=>{throw error;});const second=await shootGaunt(page,key,15);if(area==='east')captured=await imagesAndSettle(page,key,'pistol-decapitation',promise,output+'/pistol-head');else{await pause(page);const ordinary=await fxState(page,key);assert.equal(ordinary.recipe.recipeId,'ordinary');assert.equal(ordinary.fx.bursts,0);kills.push({entry,first,second,ordinary});}if(area==='east')kills.push({entry,first,second});}
 return{equipment,kills,captured,scope:'Two genuine native pistol25/15 human deaths: ordinary first then actual pistol-head finisher; existing gun feedback shares48/16 with crimson; actual neck seam and component scalar limits. No forced kills/counters/HP.'};}
export async function impactCutting(page,{output}={}){await ordinaryInput(page,()=>page.click('#retry'),{reset:true,label:'impact-fresh-normal-retry'});let crownPromise;const crown=await crownKill(page,{preserveViewport:true,beforeLethal:async()=>{crownPromise=armCapture(page,'westminster-roamer-3','split-crown');return{armedActualOnset:true};}});const crownFrames=await imagesAndSettle(page,'westminster-roamer-3','split-crown',crownPromise,output+'/crown');let openedPromise;const opened=await openedCutting(page,{prerequisites:crown,beforeLethal:async()=>{openedPromise=armCapture(page,'south-roamer-4','opened');return{armedActualOnset:true};}});const openedFrames=await imagesAndSettle(page,'south-roamer-4','opened',openedPromise,output+'/opened');
 const beforeRestore=await fxState(page,'south-roamer-4');await controlledEntry(page,{areaId:'east'});await controlledEntry(page,{areaId:'south'});const restored=await fxState(page,'south-roamer-4');assert.equal(restored.restored,true);assert.equal(restored.fx.bursts,0);await resume(page);const movement=await readState(page);await page.keyboard.down('d');try{await waitSimulation(page,p=>Math.hypot(__qa.game.player.pos.x-p.x,__qa.game.player.pos.z-p.z)>.05,movement.pos,{seconds:2,label:'impact-normal-player-continuation'});}finally{await page.keyboard.up('d');}await pause(page);const continued=await fxState(page,'south-roamer-4');assert.equal(continued.fx.bursts,0);return{crown,crownFrames,opened,openedFrames,beforeRestore,restored,continued,scope:'Existing Crown→thirdSouthOpened real cutting sequences; actual posed cap/waist anchors and once-only finite impact, ordinary travel/restored no replay/player continuation. Previous anatomy/rig/floor/balance receipts reused.'};}
