import fs from 'node:fs';
import assert from 'node:assert/strict';
import {controlledEntry,waitSimulation,readState,ordinaryInput,legal} from './scenarios.mjs';
import {near,shootGaunt} from './gaunt.mjs';import {pause,resume,stash,crownKill} from './crown.mjs';import {openedCutting} from './opened.mjs';import {pausedWorldImage} from './drone-height.mjs';
async function fxState(page,key){return page.evaluate(key=>{const q=__qa,g=q.game,e=g.corpses.find(e=>e.placementKey===key),v=e&&q.actors.views.get(e.id),pool=q.world.scene.getObjectByName('Combat feedback pool'),mesh=q.world.scene.getObjectByName('Combat pooled particles');return{time:g.time,tick:g.tick,menuOpen:document.getElementById('menu').open,fx:pool.userData.finisherImpact(),material:{depthTest:mesh.material.depthTest,depthWrite:mesh.material.depthWrite,renderOrder:mesh.renderOrder,capacity:mesh.count},recipe:e?.finisher,flash:{life:v?.impactFlashLife??0,materials:(v?.flashMaterials??[]).filter(m=>m.emissive).map(m=>({name:m.material.name,color:m.material.color.getHex(),originalColor:m.color?.getHex(),emissive:m.material.emissive.getHex(),originalEmissive:m.emissive.getHex(),intensity:m.material.emissiveIntensity,originalIntensity:m.intensity}))},requested:v?.finisherRequestedRecipeId,age:v?.finisherAge,anchors:v?.finisher?.impactAnchors(v.finisherAge),restored:v?.restoredCorpse,player:{pos:{...g.player.pos},hp:g.player.hp},live:g.enemies.map(e=>({id:e.id,pos:{...e.pos}})),particleMatrices:Array.from(mesh.instanceMatrix.array),particleColors:mesh.instanceColor?Array.from(mesh.instanceColor.array):null};},key);}
async function armRenderedFrames(page,key,recipeId){
 await page.evaluate(({key,recipeId})=>{
  window.__qaFxMotion={key,recipeId,frames:[],started:false,done:false};
  window.__qaRecordRenderedMotion=(renderer,scene,camera,draw)=>{const c=window.__qaFxMotion;if(!c||c.done)return;const q=__qa,g=q.game,e=g.corpses.find(e=>e.placementKey===c.key),v=e&&q.actors.views.get(e.id),pool=scene.getObjectByName('Combat feedback pool'),fx=pool?.userData.finisherImpact?.();if(!fx||!e)return;const active=e.finisher?.recipeId===c.recipeId&&fx.effects.some(x=>x.recipeId===c.recipeId)&&fx.activeParticles>0;if(!c.started&&!active)return;c.started=true;if(active&&c.frames.length>=10)return;if(active&&c.frames.length&&fx.poolTime-c.frames.at(-1).pool.poolTime<.06)return;
   const mesh=scene.getObjectByName('Combat pooled particles'),head=scene.getObjectByName('Prepared detached Hollow head');
   const frame={time:g.time,tick:g.tick,wall:performance.now(),pool:fx,recipe:e.finisher,age:v.finisherAge,poseAge:v.finisherPoseAge,partUntil:e.finisherPartsUntil,anchors:v.finisher.impactAnchors(v.finisherAge),live:g.enemies.map(e=>({id:e.id,pos:{...e.pos}})),phase:(v.motion.native??v.motion)?.currentPhase,root:v.root.matrixWorld.toArray(),head:head?{position:head.position.toArray(),matrix:head.matrixWorld.toArray()}:null,player:{...g.player.pos},camera:{projection:camera.projectionMatrix.toArray(),world:camera.matrixWorld.toArray()},particles:{matrices:Array.from(mesh.instanceMatrix.array),colors:mesh.instanceColor?Array.from(mesh.instanceColor.array):null,depthTest:mesh.material.depthTest,depthWrite:mesh.material.depthWrite,renderOrder:mesh.renderOrder},image:null,draw,capture:{requested:performance.now()},width:renderer.domElement.width,height:renderer.domElement.height,settled:!active};c.frames.push(frame);renderer.domElement.toBlob(blob=>{frame.capture.blobReady=performance.now();if(!blob){c.error='Canvas snapshot returned null';return;}const reader=new FileReader();reader.onload=()=>{frame.image=reader.result;frame.capture.encoded=performance.now();};reader.onerror=()=>{c.error='Canvas snapshot encoding failed';};reader.readAsDataURL(blob);},'image/jpeg',.72);frame.capture.returned=performance.now();if(!active)c.done=true;
  };
 },{key,recipeId});return{key,recipeId};
}
async function movingFrames(page,key,recipeId,armed,path){
 await waitSimulation(page,()=>{const c=window.__qaFxMotion;if(c?.error)throw Error(c.error);return c?.done&&c.frames.every(f=>f.image);},null,{seconds:4,label:'impact-bound-unpaused-rendered-sequence'});
 const capture=await page.evaluate(()=>window.__qaFxMotion);const frames=capture.frames.map((frame,i)=>{const name=path+'-moving-'+String(i).padStart(2,'0')+'.jpg';assert(frame.image.startsWith('data:image/jpeg;base64,'));fs.writeFileSync(name,Buffer.from(frame.image.split(',')[1],'base64'));const{image,...bound}=frame;return{...bound,path:name};});fs.writeFileSync(path+'-moving.capture.json',JSON.stringify({key,recipeId,frames},null,2)+'\n');assert.equal(capture.key,key);assert.equal(capture.recipeId,recipeId);assert(capture.frames.length>=3&&capture.frames.at(-1).settled);assert(capture.frames.at(-1).time>capture.frames[0].time);assert(capture.frames.some(f=>f.pool.poolTime-capture.frames[0].pool.poolTime>=.1));for(const f of capture.frames){assert(Math.abs(f.poseAge-(f.age-.25*Math.min(.2,Math.max(0,f.age))))<1e-8,'Victim-only pose emphasis must match actual age');assert.equal(f.partUntil,f.age>=6?0:capture.frames[0].partUntil,'Original real presentation-age6 expiry must remain unchanged');}
 await pause(page);return{armed,frames,scope:'Successive actual unpaused GPU canvas snapshots requested immediately after the original renderer draw, asynchronously encoded as JPEG72 with that draw camera/clock/palette/matrices; HUD DOM excluded. No extra render or actor/time/HP writes. Recorded frame timing, not phone/smooth-FPS claim.'};
}
function armCapture(page,key,recipeId,{peakAfter=null}={}){return waitSimulation(page,({key,recipeId,peakAfter})=>{const q=__qa,g=q.game,e=g.corpses.find(e=>e.placementKey===key),v=e&&q.actors.views.get(e.id),s=q.world.scene.getObjectByName('Combat feedback pool').userData.finisherImpact(),effect=s.effects.find(x=>x.recipeId===recipeId);if(!e||e.finisher?.recipeId!==recipeId||!effect||!s.activeParticles||peakAfter!==null&&s.poolTime-effect.startedAt<peakAfter)return false;if(document.getElementById('menu').open)return false;const mesh=q.world.scene.getObjectByName('Combat pooled particles'),rendered={matrices:Array.from(mesh.instanceMatrix.array),colors:Array.from(mesh.instanceColor.array),depthTest:mesh.material.depthTest,depthWrite:mesh.material.depthWrite,renderOrder:mesh.renderOrder};document.getElementById('menu-button').click();if(!document.getElementById('menu').open)throw Error('Actual Menu Pause did not acknowledge');return{time:g.time,tick:g.tick,key,recipeId,fx:s,age:v.finisherAge,renderedBeforeMenu:rendered};},{key,recipeId,peakAfter},{seconds:4,label:peakAfter===null?'impact-real-onset-pause':'impact-real-peak-pause'});}
async function imagesAndSettle(page,key,recipeId,promise,path,{peakAfter=.10,contrastProof=false}={}){const start=await promise;const onset=await start.jsonValue(),before=await fxState(page,key),onsetImage=await pausedWorldImage(page,path+'-onset.png'),after=await fxState(page,key);assert.deepEqual(after,before);assert.equal(before.recipe.recipeId,recipeId);assert.equal(before.material.depthWrite,false);assert.equal(before.material.depthTest,true);assert.equal(before.material.capacity,48);
 const peakPromise=armCapture(page,key,recipeId,{peakAfter});let peakStart;try{await page.click('#close-menu');peakStart=await peakPromise;}catch(error){error.diagnostic={step:'peak',onset,before,after,current:await fxState(page,key)};throw error;}const peak=await peakStart.jsonValue();assert(peak.time>onset.time,'Ordinary Close advanced the game before the intentional peak Pause');const peakBefore=await fxState(page,key),peakImage=await pausedWorldImage(page,path+'-peak.png');assert.deepEqual(await fxState(page,key),peakBefore);if(contrastProof){assert(before.flash.life>0&&before.flash.materials.some(m=>m.color===0x831428&&m.emissive===0x831428&&m.intensity===.35),'actual sever onset must flash dark crimson');assert.equal(peakBefore.flash.life,0);assert(peakBefore.flash.materials.every(m=>m.color===m.originalColor),'victim colours restore while spurts remain');assert(peakBefore.fx.activeParticles>0);const d=peakBefore.recipe.impactDirection,n=Math.hypot(d.x,d.z),direction={x:d.x/n,z:-d.z/n},outward=[];for(let i=0;i<48;i++){const c=before.particleColors.slice(i*3,i*3+3),a=before.particleMatrices.slice(i*16,i*16+16),b=peakBefore.particleMatrices.slice(i*16,i*16+16);if(c[0]>c[1]*3&&c[0]>c[2]*2&&Math.hypot(a[0],a[1],a[2])>0&&Math.hypot(b[0],b[1],b[2])>0){const dot=(b[12]-a[12])*direction.x+(b[14]-a[14])*direction.z;assert(dot>0,'actual reserved droplets must move outward');outward.push({slot:i,dot});}}assert(outward.length>=14);before.outwardProof=outward;}
 await resume(page);await waitSimulation(page,()=>__qa.world.scene.getObjectByName('Combat feedback pool').userData.finisherImpact().bursts===0,null,{seconds:3,label:'impact-ordinary-finite-settle'});await pause(page);const settled=await fxState(page,key);assert.equal(settled.fx.reservedParticles,0);assert.equal(settled.fx.reservedTrails,0);if(contrastProof)assert(settled.flash.materials.every(m=>m.color===m.originalColor&&m.emissive===m.originalEmissive&&m.intensity===m.originalIntensity),'finite flash must restore original material values');return{onset,before,onsetImage,peak,peakBefore,peakImage,settled,scope:'Actual onset/peak and particles frozen with normal Menu Pause; modal overlay suppressed only in stills; ordinary resume/finite settle. Paused appearance, no moving/phone claim.'};}
export async function impactPistolHead(page,{output,motion=false}={}){await pause(page);const equipment=await stash(page);const kills=[];let captured;
 for(const[area,key]of [['westminster','westminster-roamer-1'],['east','east-roamer-1']]){await controlledEntry(page,{areaId:area});const entry=await near(page,key,3.5);await resume(page);const first=await shootGaunt(page,key,25);await waitSimulation(page,()=>__qa.game.time>=__qa.game.pistol.nextFireAt&&!__qa.game.player.swing,null,{seconds:3,label:'impact-proven-pistol-cadence'});let promise;if(area==='east')promise=motion?await armRenderedFrames(page,key,'pistol-decapitation'):armCapture(page,key,'pistol-decapitation');const second=await shootGaunt(page,key,15);if(area==='east')captured=motion?await movingFrames(page,key,'pistol-decapitation',promise,output+'/pistol-head'):await imagesAndSettle(page,key,'pistol-decapitation',promise,output+'/pistol-head');else{await pause(page);const ordinary=await fxState(page,key);assert.equal(ordinary.recipe.recipeId,'ordinary');assert.equal(ordinary.fx.bursts,0);kills.push({entry,first,second,ordinary});}if(area==='east')kills.push({entry,first,second});}
 return{equipment,kills,captured,scope:'Two genuine native pistol25/15 human deaths: ordinary first then actual pistol-head finisher; existing gun feedback shares48/16 with crimson; actual neck seam and component scalar limits. No forced kills/counters/HP.'};}
export async function impactCutting(page,{output,motion=false}={}){await pause(page);await ordinaryInput(page,()=>page.click('#retry'),{reset:true,label:'impact-fresh-normal-retry'});let crownPromise;const crown=await crownKill(page,{preserveViewport:true,beforeLethal:async()=>{crownPromise=motion?await armRenderedFrames(page,'westminster-roamer-3','split-crown'):armCapture(page,'westminster-roamer-3','split-crown');return{armedActualOnset:true};},afterLethal:motion?async()=>{crownPromise=await movingFrames(page,'westminster-roamer-3','split-crown',crownPromise,output+'/crown');}:undefined});const crownFrames=motion?crownPromise:await imagesAndSettle(page,'westminster-roamer-3','split-crown',crownPromise,output+'/crown');let openedPromise;const opened=await openedCutting(page,{prerequisites:crown,beforeLethal:async()=>{openedPromise=motion?await armRenderedFrames(page,'south-roamer-4','opened'):armCapture(page,'south-roamer-4','opened');return{armedActualOnset:true};},afterLethal:motion?async()=>{openedPromise=await movingFrames(page,'south-roamer-4','opened',openedPromise,output+'/opened');}:undefined});const openedFrames=motion?openedPromise:await imagesAndSettle(page,'south-roamer-4','opened',openedPromise,output+'/opened');
 const beforeRestore=await fxState(page,'south-roamer-4');await controlledEntry(page,{areaId:'east'});await controlledEntry(page,{areaId:'south'});const restored=await fxState(page,'south-roamer-4');assert.equal(restored.restored,true);assert.equal(restored.fx.bursts,0);await resume(page);const movement=await readState(page);await page.keyboard.down('d');try{await waitSimulation(page,p=>Math.hypot(__qa.game.player.pos.x-p.x,__qa.game.player.pos.z-p.z)>.05,movement.pos,{seconds:2,label:'impact-normal-player-continuation'});}finally{await page.keyboard.up('d');}await pause(page);const continued=await fxState(page,'south-roamer-4');assert.equal(continued.fx.bursts,0);return{crown,crownFrames,opened,openedFrames,beforeRestore,restored,continued,scope:'Existing Crown→thirdSouthOpened real cutting sequences; actual posed cap/waist anchors and once-only finite impact, ordinary travel/restored no replay/player continuation. Previous anatomy/rig/floor/balance receipts reused.'};}

export async function impactSeverContrast(page,{output}={}){await pause(page);let promise;const crown=await crownKill(page,{preserveViewport:true,beforeLethal:async()=>{promise=armCapture(page,'westminster-roamer-3','split-crown');return{armedActualOnset:true};}});const captures=await imagesAndSettle(page,'westminster-roamer-3','split-crown',promise,output+'/crimson-crown',{peakAfter:.25,contrastProof:true});const beforeRestore=await fxState(page,'westminster-roamer-3');await controlledEntry(page,{areaId:'east'});await controlledEntry(page,{areaId:'westminster'});const restored=await fxState(page,'westminster-roamer-3');assert(restored.restored&&restored.fx.bursts===0);await resume(page);const initial=await readState(page);await page.keyboard.down('d');try{await waitSimulation(page,p=>Math.hypot(__qa.game.player.pos.x-p.x,__qa.game.player.pos.z-p.z)>.1,initial.pos,{seconds:2,label:'sever-contrast-player-continuation'});}finally{await page.keyboard.up('d');}await pause(page);const continued=await fxState(page,'westminster-roamer-3');assert.equal(continued.fx.bursts,0);return{crown,captures,beforeRestore,restored,continued,scope:'Existing ordinary then Crown native sequence; actual crimson flash-on, original colours restored with outward blood still visible, finite zero, settled restore no replay/player continuation. Paused frame appearance only.'};}
