import {spawnSync} from 'node:child_process';import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';
import {verifyPackage,prepareObserver,preflightCompiled,evaluateInputReadiness,ordinaryInput,equipPistol,inputDiagnostic,stage} from './scenarios.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex'),root=new URL('../../qa/drone-height-079/pointer-fixed/hf/recovered/export/',import.meta.url).pathname,pkg=verifyPackage(root),file=pkg.release.files.find(f=>/^assets\/index-.*\.js$/.test(f.path)),bytes=fs.readFileSync(path.join(root,file.path)),url='http://fixture/'+file.path,opts={meleeTrace:true,packTrace:true};
function changed(text){const release=structuredClone(pkg.release),f=release.files.find(f=>f.path===file.path),body=Buffer.from(text);f.bytes=body.length;f.sha256=hash(body);return{body,release};}
test('exact released candidate preflight parses both legitimate probes and binds package plus module',()=>{const moduleHash=hash(fs.readFileSync(new URL('./scenarios.mjs',import.meta.url))),r=preflightCompiled(root,pkg.identity,{...opts,moduleHash});assert.equal(r.status,'PASS_COMPILED_PROBE_PREFLIGHT');assert.deepEqual(r.identity,pkg.identity);assert.equal(r.moduleHash,moduleHash);assert.equal(r.payloadSHA256,file.sha256);});
test('zero and duplicate physical probe matches fail explicitly',()=>{const code=bytes.toString(),m=[...code.matchAll(/hit:\(([\w$,]+)\)=>\{/g)].find(m=>m[1].split(',').length===5);assert(m);for(const [name,text]of [['zero',code.replace(m[0],m[0].replace('hit:','unsupportedHit:'))],['duplicate',code+';const duplicate={hit:(a,b,c,d,e)=>{}};']]){const c=changed(text);assert.throws(()=>prepareObserver(c.body,c.release,'http://fixture/',url,opts),e=>e.code==='QA_PROBE_COMPATIBILITY'&&/physical contact observer seam/.test(e.message),name);}});
test('duplicate main observation and missing travel marker are rejected before gameplay',()=>{const code=bytes.toString(),m=code.slice(code.lastIndexOf('getElementById("world")')).match(/area:([\w$]+)\.areaId,position:([\w$]+)\.player\.pos/);assert(m);for(const text of [code.replace(m[0],m[0]+','+m[0]),code.replace('console.info("ARMAGEDOM_TRAVEL"','console.info("UNSUPPORTED_TRAVEL"')]){const c=changed(text);assert.throws(()=>prepareObserver(c.body,c.release,'http://fixture/',url,opts),/QA_PROBE_COMPATIBILITY/);}});
test('wrong payload, package and observer-module identities reject despite valid seams',()=>{assert.throws(()=>prepareObserver(Buffer.concat([bytes,Buffer.from(' ')]),pkg.release,'http://fixture/',url,opts),/identity/);assert.throws(()=>preflightCompiled(root,{...pkg.identity,packageSha256:'0'.repeat(64)},opts));assert.throws(()=>preflightCompiled(root,pkg.identity,{...opts,moduleHash:'0'.repeat(64)}),/module identity/);});
const before={time:1,tick:60},normal={namespaceReady:true,time:1.1,tick:66,hp:150,finished:false,menuOpen:false,resetAcknowledged:false,area:'westminster',pistolPresent:true,collected:false,equipped:false,pickupArea:'westminster',pickupDistance:.9};
test('open menu, stale clock and unacknowledged reset cannot grant readiness',()=>{for(const n of [{...normal,menuOpen:true},{...normal,time:1,tick:60},{...normal,resetAcknowledged:true}])assert.equal(evaluateInputReadiness(before,n).ready,false);assert.equal(evaluateInputReadiness(before,{...normal,time:.1,tick:6,resetAcknowledged:false},{reset:true}).ready,false);assert.equal(evaluateInputReadiness(before,{...normal,time:.1,tick:6,resetAcknowledged:true},{reset:true}).ready,true);});
test('pickup availability and equip acknowledgement are separate; fatal runtime state is explicit',()=>{for(const n of [{...normal,area:'east'},{...normal,pickupDistance:5},{...normal,pistolPresent:false}]){const r=evaluateInputReadiness(before,n,{phase:'pickup'});assert.equal(r.fatal,true);assert.equal(r.classification,'setup');}assert.equal(evaluateInputReadiness(before,normal,{phase:'pickup'}).ready,true);assert.equal(evaluateInputReadiness(before,normal,{phase:'equip'}).reason,'pickup acknowledgement pending');assert.equal(evaluateInputReadiness(before,{...normal,collected:true},{phase:'equip'}).reason,'equip acknowledgement pending');assert.equal(evaluateInputReadiness(before,{...normal,collected:true,equipped:true},{phase:'equip'}).ready,true);assert.equal(evaluateInputReadiness(before,{...normal,hp:0}).classification,'runtime');});
function browserFixture(t,{distance=.9}={}){const prior={window:globalThis.window,document:globalThis.document,qa:globalThis.__qa};t.after(()=>{globalThis.window=prior.window;globalThis.document=prior.document;globalThis.__qa=prior.qa;});globalThis.window={};const menu={open:false};globalThis.document={visibilityState:'visible',body:{classList:{contains:()=>false}},getElementById:()=>menu};const g={time:1,tick:60,player:{hp:150,pos:{x:0,z:0},weapon:'knife'},pistol:{collected:false,equipped:false,pickupPos:{x:distance,z:0},pickupAreaId:'westminster'}};globalThis.__qa={game:g,world:{areaId:'westminster',scene:{getObjectByName:()=>null}}};let keyCount=0;
 const page={evaluate:async(fn,arg)=>fn(arg),keyboard:{press:async key=>{assert.equal(key,'g');keyCount++;g.pistol.collected=g.pistol.equipped=true;}},waitForFunction:async(fn,arg)=>{assert.equal(fn(arg),false,'Cannot acknowledge before real clock advances');g.time+=1/60;g.tick++;const result=fn(arg);if(!result)throw Error('Not ready');return{jsonValue:async()=>result};}};return{page,g,menu,keyCount:()=>keyCount};}
test('shared helper waits for advancement and acknowledges one ordinary equip action',async t=>{const f=browserFixture(t);const r=await equipPistol(f.page);assert.equal(r.snapshot.equipped,true);assert.equal(f.keyCount(),1);assert.equal(r.snapshot.tick,62);});
test('out-of-range pickup fails before sending G and retains first diagnostic',async t=>{const f=browserFixture(t,{distance:5});await assert.rejects(equipPistol(f.page),e=>/QA_INPUT_SETUP/.test(e.message)&&e.diagnostic.readiness.snapshot.pickupDistance===5);assert.equal(f.keyCount(),0);});
test('stage failure preserves readiness diagnostic in hashed raw receipt',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'armagedom-readiness-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const h='1'.repeat(64),context={identity:{source:'2'.repeat(40),fingerprint:h,packageSha256:h},stageHarnessHash:h,moduleHash:h,runnerHash:h,observerHash:h,dependencies:{},inputHash:h,environment:{},preconditions:{},receiptDir:dir,rawOutputPath:path.join(dir,'raw.json')};await assert.rejects(stage('input.failed',context,async()=>{const e=Error('pickup rejected');e.diagnostic={classification:'setup',equipped:false,cue:null};throw e;}));const raw=JSON.parse(fs.readFileSync(context.rawOutputPath)),record=JSON.parse(fs.readFileSync(path.join(dir,'input.failed.json')));assert.equal(record.status,'failed');assert.equal(raw.diagnostic.classification,'setup');assert.equal(record.rawOutputSha256,hash(fs.readFileSync(context.rawOutputPath)));});

test('standalone CLI returns nonzero and records actionable zero/duplicate/identity failures',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'armagedom-probe-cli-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const code=bytes.toString(),m=[...code.matchAll(/hit:\(([\w$,]+)\)=>\{/g)].find(m=>m[1].split(',').length===5);
 for(const [name,text]of [['zero',code.replace(m[0],m[0].replace('hit:','unsupportedHit:'))],['duplicate',code+';const duplicate={hit:(a,b,c,d,e)=>{}};'],['identity',code]]){const pkgDir=path.join(dir,name);fs.mkdirSync(path.join(pkgDir,'assets'),{recursive:true});const c=changed(text);c.release.files=c.release.files.filter(f=>f.path===file.path);fs.writeFileSync(path.join(pkgDir,file.path),c.body);const raw=JSON.stringify(c.release);fs.writeFileSync(path.join(pkgDir,'release.json'),raw);const config={packageRoot:pkgDir,expect:{source:c.release.sourceCommit,fingerprint:c.release.sourceFingerprint,packageSha256:name==='identity'?'0'.repeat(64):hash(raw)},meleeTrace:true,output:path.join(pkgDir,'results/browser')},configFile=path.join(pkgDir,'config.json');fs.writeFileSync(configFile,JSON.stringify(config));const result=spawnSync(process.execPath,[new URL('./preflight.mjs',import.meta.url).pathname,configFile],{encoding:'utf8'});assert.equal(result.status,1,name);const failure=JSON.parse(fs.readFileSync(path.join(pkgDir,'results/probe-preflight.json')));assert.equal(failure.status,'FAIL_COMPILED_PROBE_PREFLIGHT');assert.match(failure.error,name==='identity'?/packageSha256/:/QA_PROBE_COMPATIBILITY/);}
});

test('unavailable diagnostic never replaces the original failure',async()=>{const diagnostic=await inputDiagnostic({evaluate:async()=>{throw Error('browser context closed');}});assert.match(diagnostic.unavailable,/browser context closed/);});
