import assert from 'node:assert/strict';
import {controlledEntry,waitSimulation,readState,ordinaryInput,equipPistol,legal} from './scenarios.mjs';
import {crownKill,cuttingKill,pause,resume} from './crown.mjs';
const key='south-roamer-4';
async function inspect(page,targetKey=key,{floor=false}={}){return page.evaluate(({key,floor})=>{
 const q=__qa,g=q.game,e=[...g.enemies,...g.corpses].find(e=>e.placementKey===key),v=q.actors.views.get(e.id),part=v.root.getObjectByName('Prepared Opened');
 let floors=null;if(floor&&part){part.updateWorldMatrix(true,true);floors=part.children.map(half=>{let minimum=Infinity,vertices=0;half.traverse(n=>{if(!n.isMesh)return;const p=n.geometry.attributes.position,m=n.matrixWorld.elements,index=n.geometry.index;for(let i=0;i<(index?.count??p.count);i++){const j=index?index.getX(i):i;minimum=Math.min(minimum,m[1]*p.getX(j)+m[5]*p.getY(j)+m[9]*p.getZ(j)+m[13]);vertices++;}});return{name:half.name,minimum,vertices};});}
 return{time:g.time,key,hp:e.hp,recipe:e.finisher,requested:v.finisherRequestedRecipeId,age:v.finisherAge,retainedAge:e.finisherPresentationAge,response:e.response,partUntil:e.finisherPartsUntil??0,headUntil:e.finisherHeadUntil??0,stats:v.finisher?.stats(),pose:v.finisher?.pose(v.finisherAge??0),clip:(v.motion.native??v.motion).currentClip,restored:!!v.restoredCorpse,root:v.root.position.toArray(),spaceClear:v.finisher?.stats().openedPrepared?q.world.geometry.clear(e.pos,v.finisher.stats().opened.envelopeRadius*v.root.scale.x):null,part:part?{parent:part.parent===v.root,visible:part.visible,groups:part.children.map(n=>n.name)}:null,floors,kits:[...q.actors.views].flatMap(([id,v])=>v.finisher?.stats().openedPrepared?[{id,key:[...g.enemies,...g.corpses].find(e=>e.id===id)?.placementKey,stats:v.finisher.stats()}]:[]),player:{pos:{...g.player.pos},hp:g.player.hp},live:g.enemies.map(e=>({key:e.placementKey,pos:{...e.pos}})),finishers:g.finishers,ledger:structuredClone(g.supplies),saved:JSON.parse(localStorage.getItem('armagedom:area1-run:v1'))};
 },{key:targetKey,floor});}
async function southEntry(page){return page.evaluate(key=>{const q=__qa,e=q.game.enemies.find(e=>e.placementKey===key),p={x:e.pos.x,z:e.pos.z+1.4};if(!q.world.geometry.clear(p,q.game.player.radius)||!q.world.lineClear(p,e.pos))throw Error('Registered South melee entry unavailable');const a=q.world.geometry.point(p);return{areaId:'south',entryPoint:{x:a.x,y:a.y}};},key);}
export async function openedCutting(page,{screenshotPath}={}){
 const prerequisites=await crownKill(page);await resume(page);await legal(page);const equipped=await equipPistol(page);await pause(page);await controlledEntry(page,{areaId:'south'});
 const prepared=await inspect(page);assert.deepEqual(prepared.kits.map(e=>e.key),[key]);assert(prepared.stats.openedPrepared);assert.equal(prepared.stats.openedPreparationError,null);
 const kill=await cuttingKill(page,key,{meleeEntry:southEntry});
 await waitSimulation(page,()=>{const q=__qa,e=q.game.corpses.find(e=>e.placementKey==='south-roamer-4'),v=e&&q.actors.views.get(e.id);return v?.finisher.stats().openedActive&&v.root.getObjectByName('Prepared Opened')?.visible;},null,{seconds:2,label:'opened-actual-presentation-start'});
 const rendered=await inspect(page,key,{floor:true});assert.equal(rendered.requested,'opened');assert.equal(rendered.recipe.recipeId,'opened');assert.equal(rendered.recipe.seconds,1);assert.equal(rendered.recipe.cost,1);assert.deepEqual(rendered.recipe.parts,['upper-body']);assert.equal(rendered.stats.activePartCost,1);assert.equal(rendered.stats.lethalVertexCopies,0);assert.equal(rendered.stats.opened.ownedTextures,0);assert.equal(rendered.stats.opened.floorTableEntries,363);assert.equal(rendered.headUntil,0);assert(rendered.partUntil>rendered.time);assert.equal(rendered.part.parent,true);assert.equal(rendered.part.groups.length,3);assert(rendered.floors.every(p=>p.vertices>0&&p.minimum>=-.0001));assert(rendered.player.hp>0&&rendered.live.length>0);
 await page.setViewportSize({width:393,height:852});await page.waitForFunction(()=>__qa.world.width===393&&__qa.world.height===852);await page.screenshot({path:screenshotPath});await pause(page);await page.setViewportSize({width:1180,height:744});
 return{prerequisites,equipped,prepared,kill,rendered,screenshotPath,scope:'Genuine third cutting kill/one prepared South kit/native1s actual body parts/floor and free player; component anatomy/geometry proof reused, no phone or all-finisher claim.'};
}
export async function openedLifecycle(page){
 const before=await inspect(page);await controlledEntry(page,{areaId:'east'});await controlledEntry(page,{areaId:'south'});const restored=await inspect(page);assert(restored.restored);assert.equal(restored.recipe.recipeId,'opened');assert(restored.age>=before.age);assert.equal(restored.age,restored.retainedAge);
 await resume(page);const movementBefore=await inspect(page),t=movementBefore.time;await page.keyboard.down('d');try{await waitSimulation(page,t=>__qa.game.time-t>.25,t,{seconds:1,label:'opened-free-player-movement'});}finally{await page.keyboard.up('d');}
 const continued=await inspect(page);assert(Math.hypot(continued.player.pos.x-movementBefore.player.pos.x,continued.player.pos.z-movementBefore.player.pos.z)>.01);assert(continued.live.some(e=>{const b=movementBefore.live.find(p=>p.key===e.key);return b&&Math.hypot(e.pos.x-b.pos.x,e.pos.z-b.pos.z)>.01;}));
 await waitSimulation(page,()=>{const q=__qa,e=q.game.corpses.find(e=>e.placementKey==='south-roamer-4');return q.actors.views.get(e.id).finisher.stats().expired&&e.finisherPartsUntil===0;},null,{seconds:6,label:'opened-six-second-expiry'});await pause(page);const expired=await inspect(page);assert.equal(expired.part,null);assert.equal(expired.stats.activePartCost,0);assert.equal(expired.pose.clip,'Death');assert.equal(expired.clip,'Death');assert(expired.age>=6);assert.deepEqual(expired.ledger.issued.sort(),before.ledger.issued.sort());
 await controlledEntry(page,{areaId:'east'});await controlledEntry(page,{areaId:'south'});const expiredReturn=await inspect(page);assert(expiredReturn.age>=expired.age);assert.equal(expiredReturn.part,null);assert.equal(expiredReturn.stats.activePartCost,0);assert.equal(expiredReturn.pose.clip,'Death');
 await page.reload();await page.tap('#enter');await page.waitForFunction(()=>window.__qa?.game&&document.getElementById('entry').hidden,null,{timeout:90000});await pause(page);const cold=await readState(page);assert(!cold.enemies.some(e=>['westminster-roamer-1','westminster-roamer-3'].includes(e.key)));assert(!JSON.stringify(cold.saved).includes('finisherPresentationAge'));assert.equal(cold.saved.pistol.magazine,3);
 const fresh=await ordinaryInput(page,()=>page.click('#retry'),{reset:true,label:'opened-retry'});await pause(page);const retry=await readState(page);assert.equal(retry.hp,150);assert.equal(retry.enemies.length,7);assert.equal(retry.corpses.length,0);assert.deepEqual(retry.supplies.issued,[]);const west=await inspect(page,'westminster-roamer-3');assert.deepEqual(west.kits.map(e=>e.key),['westminster-roamer-3']);assert.equal(west.stats.openedActive,false);
 return{before,restored,movementBefore,continued,expired,expiredReturn,cold,fresh,retry,west,scope:'Actual parked corpse presentation age never rewinds; normal expiry restores body/releases cost, expired return does not resurrect parts; existing cold West deaths/ammo and actual Retry, no saved cosmetic state.'};
}
export async function openedFallback(page){
 await resume(page);const prerequisites=await crownKill(page,{keys:['westminster-roamer-1','westminster-roamer-5']});await resume(page);await legal(page);const equipped=await equipPistol(page);await pause(page);const prepared=await inspect(page,'westminster-roamer-3');assert(prepared.stats.openedPrepared);
 const kill=await cuttingKill(page,'westminster-roamer-3');await waitSimulation(page,()=>{const q=__qa,e=q.game.corpses.find(e=>e.placementKey==='westminster-roamer-3');return e&&q.actors.views.get(e.id)?.finisherStarted;},null,{seconds:2,label:'opened-real-space-fallback'});await pause(page);const corpse=await inspect(page,'westminster-roamer-3');assert.equal(corpse.requested,'opened');assert.equal(corpse.spaceClear,false);assert.equal(corpse.recipe.recipeId,'ordinary');assert.equal(corpse.recipe.cost,0);assert.deepEqual(corpse.recipe.parts,[]);assert.equal(corpse.partUntil,0);assert.equal(corpse.headUntil,0);assert.equal(corpse.stats.activePartCost,0);assert.equal(corpse.part,null);assert.equal(corpse.finishers.recentRecipeId,'ordinary');assert.equal(corpse.finishers.kills,3);assert.equal(corpse.ledger.issued.filter(k=>k==='westminster-roamer-3').length,1);return{prerequisites,equipped,prepared,kill,corpse,scope:'Actual requested third Opened rejected by registered static space; ordinary presentation metadata/cost/recent selection and once-only supply remain aligned, no artificial blocker.'};
}
