// Scoped 078 native encounter. Only ordinary inputs, registered travel setup and observations.
import assert from 'node:assert/strict';
import {controlledEntry,waitSimulation,pistolKill,readState} from './scenarios.mjs';
const PACK='east-roamer-4',ALLY='east-roamer-9';
async function pause(page){await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);}
async function resume(page){const pausedTime=await page.evaluate(()=>__qa.game.time);await page.click('#close-menu');await waitSimulation(page,time=>!document.getElementById('menu').open&&__qa.game.time>time,pausedTime,{seconds:3,label:'pack-resume'});}
async function entry(page,mode){const destination=await page.evaluate(mode=>{const q=__qa,g=q.game,w=q.world,e=g.enemies.find(e=>e.placementKey==='east-roamer-4'),a=g.enemies.find(e=>e.placementKey==='east-roamer-9');let candidates=[];for(let i=0;i<72;i++){const angle=i*Math.PI/36,r=mode==='paired'?2.2:mode==='kill'?3.8:mode==='withdraw'?1.95:2.1,actor=['paired','kill'].includes(mode)?a:e,p={x:actor.pos.x+r*Math.cos(angle),z:actor.pos.z+r*Math.sin(angle)},packGap=Math.hypot(p.x-e.pos.x,p.z-e.pos.z);if(!w.geometry.clear(p,.4)||!w.lineClear(p,actor.pos)||g.enemies.some(o=>Math.hypot(p.x-o.pos.x,p.z-o.pos.z)<.4+o.radius+.001))continue;if(mode==='paired'&&(packGap<=2.5||packGap>6||!w.lineClear(e.pos,p)||!w.lineClear(e.pos,a.pos)||Math.hypot(e.pos.x-a.pos.x,e.pos.z-a.pos.z)>6))continue;if(mode==='kill'&&packGap<=6.1)continue;const away={x:(e.pos.x-p.x)/packGap,z:(e.pos.z-p.z)/packGap},next=w.move(e.pos,{x:away.x*.05,z:away.z*.05},e.radius);if(mode==='withdraw'&&(Math.hypot(next.x-e.pos.x,next.z-e.pos.z)<.03||!w.lineClear(e.pos,next)))continue;candidates.push({p,packGap,score:mode==='kill'?-packGap:packGap});}candidates.sort((a,b)=>a.score-b.score);if(!candidates.length)throw Error('No clear registered '+mode+' setup');const chosen=candidates[0],point=w.geometry.point(chosen.p);return{areaId:'east',entryPoint:{x:point.x,y:point.y},chosen};},mode);const{chosen,...travel}=destination;return{chosen,travel:await controlledEntry(page,travel)};}
async function startCapture(page){await page.evaluate(()=>{window.__qaPack=[];let active=true;window.__qaStopPack=()=>{active=false;window.__qaPackTick=null;};const capture=()=>{if(!active)return;const q=__qa,g=q.game,e=g.enemies.find(e=>e.placementKey==='east-roamer-4'),a=g.enemies.find(e=>e.placementKey==='east-roamer-9');if(e&&window.__qaPack.at(-1)?.tick!==g.tick&&__qaPack.length<1000){__qaPack.push({tick:g.tick,time:g.time,player:{...g.player.pos},playerHP:g.player.hp,pack:{id:e.id,pos:{...e.pos},home:{...e.home},hp:e.hp,alerted:e.alerted,companions:structuredClone(e.packCompanions),movement:e.packMovement,swing:e.swing?{clip:e.swing.clip,age:e.swing.ageTicks}:null,recoverUntil:e.recoverUntil,staggerUntil:e.staggerUntil},ally:a?{id:a.id,pos:{...a.pos},hp:a.hp,alerted:a.alerted}:null,pairGap:a?Math.hypot(e.pos.x-a.pos.x,e.pos.z-a.pos.z):null,pairLOS:a?q.world.lineClear(e.pos,a.pos):false,playerLOS:q.world.lineClear(e.pos,g.player.pos),playerGap:Math.hypot(e.pos.x-g.player.pos.x,e.pos.z-g.player.pos.z),otherActors:g.enemies.filter(o=>o!==e&&o!==a).map(o=>({key:o.placementKey,rig:o.rig,hp:o.hp,alerted:o.alerted,gap:Math.hypot(o.pos.x-e.pos.x,o.pos.z-e.pos.z)}))});}};window.__qaPackTick=capture;});}
async function finishCapture(page){return page.evaluate(()=>{__qaStopPack();return structuredClone(__qaPack)});}
export async function packPaired(page){await pause(page);await controlledEntry(page,{areaId:'east'});const before=await readState(page);assert.equal(before.enemies.length,10);const rows=await page.evaluate(()=>__qa.game.enemies.map(e=>({key:e.placementKey,recipe:e.animalRecipe,intent:!!e.residentIntent,moveSpeed:e.moveSpeed,recoveryDelay:e.recoveryDelay,radius:e.radius,hp:e.hp,home:{...e.home}})));assert.deepEqual(rows.filter(e=>e.intent).map(e=>e.key),[PACK]);const setup=await entry(page,'paired');await startCapture(page);await resume(page);await waitSimulation(page,()=>__qaPack.some(s=>s.pack.alerted&&s.pack.movement==='native'&&s.pack.companions?.eligibleCompanionAlerted&&s.playerGap>2.5),null,{seconds:2,label:'pack-ally-wake'});const time=await page.evaluate(()=>__qa.game.time);await waitSimulation(page,time=>__qa.game.time-time>.4,time,{seconds:1,label:'pack-native-pursuit'});await pause(page);const samples=await finishCapture(page),paired=samples.find(s=>s.pack.alerted&&s.pack.movement==='native'&&s.playerGap>2.5&&s.pack.companions?.eligibleCompanionAlerted);assert(paired&&paired.pairLOS&&paired.playerLOS&&paired.pairGap<=6);assert(samples.some(s=>Math.hypot(s.pack.pos.x-paired.pack.pos.x,s.pack.pos.z-paired.pack.pos.z)>.1));return{before,rows,setup,samples,after:await readState(page),scope:'Registered controlled entry, actual East9 baseline wake plus Pack assisted native pursuit; no actor/time writes or phone claim'};}
export async function packIsolated(page){
 // Two explicit menu Retries return A and reset positions/health through the production path.
 for(let i=0;i<2;i++){await page.click('#retry');await waitSimulation(page,()=>!document.getElementById('menu').open&&__qa.game.time>0,null,{seconds:3,label:'pack-reset'});await pause(page);}
 assert.equal(await page.evaluate(()=>__qa.game.animalCycle),'A');await resume(page);await page.keyboard.press('g');await waitSimulation(page,()=>__qa.game.pistol.equipped,null,{seconds:3,label:'pack-ordinary-equip'});await pause(page);await controlledEntry(page,{areaId:'east'});const killSetup=await entry(page,'kill');await resume(page);const kill=await pistolKill(page,{targetKey:ALLY,damageSteps:[25,5],expectedClip:'dog_death'});await pause(page);const holdSetup=await entry(page,'hold');await startCapture(page);await resume(page);await waitSimulation(page,()=>__qaPack.some(s=>s.pack.alerted&&s.pack.movement==='hold'&&!s.pack.companions?.hasEligibleCompanion&&s.playerGap>=2),null,{seconds:2,label:'pack-isolated-hold'});await pause(page);const hold=await finishCapture(page);const withdrawSetup=await entry(page,'withdraw');await startCapture(page);await resume(page);await waitSimulation(page,()=>__qaPack.some(s=>s.pack.movement==='withdraw'&&s.playerGap<2),null,{seconds:2,label:'pack-isolated-withdraw'});await waitSimulation(page,()=>__qaPack.some(s=>s.pack.movement==='hold'&&s.playerGap>=2),null,{seconds:2,label:'pack-retreat-to-hold'});await pause(page);const withdraw=await finishCapture(page);assert(withdraw.some((s,i)=>i&&Math.hypot(s.pack.pos.x-s.player.x,s.pack.pos.z-s.player.z)>Math.hypot(withdraw[i-1].pack.pos.x-s.player.x,withdraw[i-1].pack.pos.z-s.player.z)+.001));assert(withdraw.every(s=>!s.pack.swing));return{killSetup,kill,holdSetup,hold,withdrawSetup,withdraw,after:await readState(page),scope:'Ordinary pistol removes East9, other actors retained, actual isolated hold/withdraw through collision movement; no actor writes'};
}
