import assert from 'node:assert/strict';
import {readState,aimAt,waitEvent,waitSimulation,controlledEntry,equipPistol,legal} from './scenarios.mjs';
import {humanKillSetup,pause,resume,stash,crownColdRetry} from './crown.mjs';
const target='westminster-roamer-3';
async function inspect(page,key=target,{floor=false}={}){return page.evaluate(({key,floor})=>{const q=__qa,g=q.game,e=[...g.enemies,...g.corpses].find(e=>e.placementKey===key),v=q.actors.views.get(e.id),pose=v.finisher.pose(v.finisherAge??0);let minimum=null,vertices=0;if(floor){v.root.updateWorldMatrix(true,true);v.model.traverse(n=>{if(n.skeleton)n.skeleton.update();});const point=v.root.position.clone();minimum=Infinity;v.model.traverse(n=>{if(!n.isMesh)return;for(let p=n;p&&p!==v.root;p=p.parent)if(!p.visible)return;const index=n.geometry.index,p=n.geometry.attributes.position;for(let i=0;i<(index?.count??p.count);i++){n.getVertexPosition(index?index.getX(i):i,point).applyMatrix4(n.matrixWorld);minimum=Math.min(minimum,point.y);vertices++;}});}return{key,time:g.time,kills:g.kills,hp:e.hp,recipe:e.finisher,age:v.finisherAge,retainedAge:e.finisherPresentationAge,stats:v.finisher.stats(),pose,clip:(v.motion.native??v.motion).currentClip,root:v.root.position.toArray(),entityPos:{...e.pos},shadow:v.shadow.position.toArray(),partUntil:e.finisherPartsUntil??0,headUntil:e.finisherHeadUntil??0,minimum,vertices,restored:!!v.restoredCorpse,player:{pos:{...g.player.pos},hp:g.player.hp},live:g.enemies.map(e=>({key:e.placementKey,pos:{...e.pos}})),ledger:structuredClone(g.supplies)};},{key,floor});}
async function piercingKill(page,key){const setup=await humanKillSetup(page,key);await waitSimulation(page,()=>{const g=__qa.game,p=g.player;return !document.getElementById('menu').open&&!p.swing&&g.time>=p.ready&&g.time>=p.hurtUntil&&g.time>=p.dodgeUntil&&p.stamina>=14;},null,{seconds:3,label:'actual-native-thrust-readiness'});const before=await readState(page),e=before.enemies.find(e=>e.key===key);assert.equal(before.weapon,'knife');assert.equal(e.hp,5);const point=await aimAt(page,e.id);await page.mouse.click(point.x,point.y,{button:'right'});await waitEvent(page,{type:'attack',actor:0,move:'thrust'},before.events.length);await waitEvent(page,{type:'hit',actor:e.id,move:'thrust',amount:9},before.events.length);await waitEvent(page,{type:'death',actor:e.id,move:'thrust'},before.events.length);return{setup,before,after:await readState(page)};}
export async function runThroughKills(page,{screenshotPath}={}){
 await pause(page);const equipped=await stash(page),kills=[];
 for(const [i,key]of ['westminster-roamer-1',target].entries()){const kill=await piercingKill(page,key),corpse=await inspect(page,key,{floor:i===1});assert.equal(corpse.hp,0);assert.equal(corpse.recipe.damageType,'piercing');assert.equal(corpse.recipe.cost,0);assert.deepEqual(corpse.recipe.parts,[]);assert.equal(corpse.partUntil,0);assert.equal(corpse.headUntil,0);if(i===0)assert.equal(corpse.recipe.recipeId,'ordinary');else{assert.equal(corpse.recipe.recipeId,'run-through');assert.equal(corpse.recipe.clip,'Death_RunThrough');assert.equal(corpse.recipe.seconds,1);assert.equal(corpse.clip,'Death_RunThrough');assert.equal(corpse.stats.runPreparationError,null);assert.equal(corpse.stats.runGrounding.bytes,484);assert.equal(corpse.stats.runGrounding.samples,121);assert.equal(corpse.stats.activePartCost,0);assert.equal(corpse.stats.detached,false);assert.equal(corpse.stats.lethalVertexCopies,0);assert(corpse.minimum>=-.0001&&corpse.vertices>0);assert(Math.abs(corpse.root[1]-corpse.pose.groundLift)<1e-8);}await pause(page);kills.push({key,kill,corpse});if(i===0){await resume(page);await legal(page);await equipPistol(page);await pause(page);}}
 await resume(page);await waitSimulation(page,()=>{const q=__qa,e=q.game.corpses.find(e=>e.placementKey==='westminster-roamer-3');return q.actors.views.get(e.id).finisherAge>=1;},null,{seconds:2,label:'native-one-second-victim-completion'});await pause(page);const completed=await inspect(page,target,{floor:true});assert.equal(completed.pose.phase,.999999);assert(completed.minimum>=-.0001);assert(Math.abs(completed.root[1]-completed.pose.groundLift)<1e-8);await page.setViewportSize({width:393,height:852});await page.waitForFunction(()=>__qa.world.width===393&&__qa.world.height===852);await resume(page);await page.screenshot({path:screenshotPath});await pause(page);await page.setViewportSize({width:1180,height:744});return{equipped,kills,completed,screenshotPath,scope:'Two genuine piercing kills: ordinary then native1s RunThrough; actual indexed victim floor/one fresh dead-root lift, zero parts/cost/lethal geometry scans. Component phase/anatomy/grounding proof reused; no attacker choreography or phone acceptance.'};
}
export async function runThroughLifecycle(page){const before=await inspect(page);await controlledEntry(page,{areaId:'east'});await controlledEntry(page,{areaId:'westminster'});const restored=await inspect(page,target,{floor:true});assert(restored.restored&&restored.age>=before.age);assert.equal(restored.recipe.recipeId,'run-through');assert.equal(restored.pose.phase,.999999);assert(restored.minimum>=-.0001);assert(Math.abs(restored.root[1]-restored.pose.groundLift)<1e-8);await resume(page);const movementBefore=await inspect(page),t=movementBefore.time;await page.keyboard.down('d');try{await waitSimulation(page,t=>__qa.game.time-t>.25,t,{seconds:1,label:'runthrough-independent-player-movement'});}finally{await page.keyboard.up('d');}await pause(page);const continued=await inspect(page,target,{floor:true});assert(Math.hypot(continued.player.pos.x-movementBefore.player.pos.x,continued.player.pos.z-movementBefore.player.pos.z)>.01);assert(continued.live.some(e=>{const b=movementBefore.live.find(x=>x.key===e.key);return b&&Math.hypot(e.pos.x-b.pos.x,e.pos.z-b.pos.z)>.01;}));assert(Math.abs(continued.root[1]-continued.pose.groundLift)<1e-8);assert(continued.minimum>=-.0001);assert.deepEqual(continued.entityPos,before.entityPos);assert.deepEqual(continued.ledger.issued.sort(),before.ledger.issued.sort());const coldRetry=await crownColdRetry(page);return{before,restored,movementBefore,continued,coldRetry,scope:'Normal travel reconstructs grounded native corpse/age without accumulated root lift or entity movement; player and survivors continue, same ledger/cold West deaths and ordinary Retry helper.'};}
