// Invoke on the existing VPS against an already frozen/exported package.
const {chromium}=await import(process.env.PLAYWRIGHT_ENTRY??'/opt/frankendom-shadow/repo/node_modules/playwright/index.mjs');
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createHash}from'node:crypto';
import {verifyPackage,installObserver,readState,stage,codeDigest,camera,hudMultitouch,controlledEntry,waitSimulation,incomingBite,lowStrike,pistolKill,pauseAndRetry,pistolBodyCue,finisherPrepared,animalAppearanceRows,droneEncounter,animalCycleRows,portraitDodge,droneMeleeInput,dronePistolControl}from'./scenarios.mjs';
import {packPaired,packIsolated} from './pack-chaser.mjs';
const config=JSON.parse(fs.readFileSync(process.argv[2]));for(const key of ['source','fingerprint','packageSha256'])assert(config.expect?.[key],'missing exact expected '+key);const output=path.resolve(config.output??'results/browser'),pkg=verifyPackage(config.packageRoot,config.expect),browser=await chromium.launch({headless:true,...(process.env.QA_SOFTWARE_WEBGL==='1'?{args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']}: {})}),page=await browser.newPage({viewport:config.viewport??{width:1180,height:744},isMobile:!config.desktop,hasTouch:!config.desktop}),errors=[],probes=[],hash=x=>createHash('sha256').update(x).digest('hex');fs.mkdirSync(output,{recursive:true});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await installObserver(page,pkg.release,config.baseURL,probes,{meleeTrace:config.meleeTrace,packTrace:config.profile==='pack-chaser'});
const runStage=async(name,fn,options={})=>{const before=await readState(page),target=before.enemies.find(e=>e.key===options.targetKey);return stage(name,{identity:pkg.identity,stageHarnessHash:codeDigest(fn),inputHash:hash(JSON.stringify(options)),moduleHash:hash(fs.readFileSync(new URL('./scenarios.mjs',import.meta.url))),runnerHash:hash(fs.readFileSync(new URL('./run.mjs',import.meta.url))),observerHash:hash(JSON.stringify(probes)),dependencies:{payloads:hash(JSON.stringify(pkg.release.files))},environment:{browser:'Chromium',version:browser.version(),viewport:{width:before.width,height:before.height},isMobile:!config.desktop,hasTouch:!config.desktop},preconditions:{area:before.area,pos:before.pos,weapon:before.weapon,alive:before.hp>0,targetKey:target?.key??null,targetHP:target?.hp??null},receiptDir:path.join(output,'stages'),rawOutputPath:path.join(output,name+'.raw.json')},async()=>{const observations=await fn(page,options);if(errors.length)throw Error(errors.join('\n'));observations.observerHashes=probes;return observations;});};
try{
 await page.goto(config.baseURL+'?touch=1');if(config.desktop)await page.click('#enter');else await page.tap('#enter');await page.waitForFunction(()=>window.__qa?.game&&document.getElementById('entry').hidden,null,{timeout:90000});
 if(config.profile==='pack-chaser'){await runStage('pack.paired',packPaired);await runStage('pack.isolated',packIsolated);}
 else if(config.profile==='drone-melee'){for(const c of config.meleeCases??[])await runStage('drone.melee_'+c.action+'_'+(c.gap>3?'far':'near'),droneMeleeInput,c);if(config.pistolControl)await runStage('drone.pistol_retained',dronePistolControl);}
 else if(config.profile==='portrait-dodge')await runStage('portrait.dodge_size_layout_roll',portraitDodge,config.dodge);
 else if(config.profile==='animal-cycle'){
  await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);
  for(const cycle of (config.resumeCycle==='B'?['B']:['A','B'])){if(cycle==='B'){await page.click('#retry');await waitSimulation(page,()=>__qa.game.animalCycle==='B',null,{seconds:3,label:'explicit-retry-cycle-b'});await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);}
   for(const [i,areaId]of ['westminster','east','south','westminster'].entries()){await runStage('cycle.'+cycle.toLowerCase()+'.entry_'+areaId+'_'+i,controlledEntry,{areaId});await runStage('cycle.'+cycle.toLowerCase()+'.rows_'+areaId+'_'+i,animalCycleRows,{cycle,...config.cycles[cycle]});}
  }
  await page.reload();await page.click('#enter');await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);await runStage('cycle.b.cold_refresh',animalCycleRows,{cycle:'B',...config.cycles.B});await page.click('#retry');await waitSimulation(page,()=>__qa.game.animalCycle==='A',null,{seconds:3,label:'explicit-retry-cycle-a'});await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);await runStage('cycle.a.reset_return',animalCycleRows,{cycle:'A',...config.cycles.A});
 }
 else if(config.profile==='drone'){await page.keyboard.press('g');await waitSimulation(page,()=>__qa.game.pistol.equipped,null,{seconds:3,label:'drone-quiet-equip'});await runStage('drone.controlled_entry',controlledEntry,config.entry);await runStage('drone.encounter_persistence',droneEncounter,config.drone);}
 else if(config.profile==='animal-appearance'){for(const [i,areaId]of ['westminster','south','east','westminster'].entries()){await runStage('appearance.entry_'+areaId+'_'+i,controlledEntry,{areaId});await runStage('appearance.rows_'+areaId+'_'+i,animalAppearanceRows,config.appearance);}}
 else if(config.profile==='finisher-presentation'){const bundle=pkg.release.files.find(f=>/^assets\/index-.*\.js$/.test(f.path)),code=fs.readFileSync(path.join(config.packageRoot,bundle.path),'utf8');assert(/\.set\([\w$]+\.x\*1\.6,1\.8,-[\w$]+\.z\*1\.6\)/.test(code),'compiled finisher launch constants');await runStage('finisher.prepared_boundary',finisherPrepared,config.finisher);}
 else if(config.profile==='pistol-cue'){await page.keyboard.press('g');await waitSimulation(page,()=>__qa.game.pistol.equipped,null,{seconds:3,label:'quiet-equip'});await runStage('setup.controlled_entry',controlledEntry,config.entry);await runStage('pistol.body_edge_cue',pistolBodyCue,config.cue);}
 else if(config.profile==='camera')await runStage('camera.orientation',camera,config.camera);
 else if(config.profile==='hud'){await runStage('hud.multitouch',hudMultitouch);await runStage('hud.pause_retry',pauseAndRetry,config.retry);}
 else if(config.profile==='weapon'||config.profile==='animal'){
  await page.keyboard.press('g');await waitSimulation(page,()=>__qa.game.pistol.collected,null,{seconds:3,label:'quiet-collect'});if(config.entry)await runStage('setup.controlled_entry',controlledEntry,config.entry);
  if(config.profile==='animal'&&config.boundary!=='pistol'){
   await page.tap('#heavy');await waitSimulation(page,()=>__qa.game.player.weapon==='knife',null,{seconds:3,label:'ordinary-holster'});if(config.boundary==='bite')await runStage('animal.incoming',incomingBite,config.animal);else if(config.boundary==='low')await runStage('animal.low',lowStrike,config.animal);else throw Error('animal boundary must be bite, low or pistol; do not improvise combined fight');
  }else{await runStage('weapon.pistol_death',pistolKill,config.weapon);await runStage('weapon.pause_retry',pauseAndRetry,config.retry);}
 }else throw Error('unknown profile');
}finally{fs.writeFileSync(path.join(output,'wrapper.json'),JSON.stringify({identity:pkg.identity,profile:config.profile,scope:'Stage receipts govern observations; wrapper exit remains process exit; physical device and cross-stage combined fight unproved.',errors,observerHashes:probes},null,2)+'\n');await browser.close();}
