// Invoke on the existing VPS against an already frozen/exported package.
import {chromium} from '/opt/frankendom-shadow/repo/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createHash}from'node:crypto';
import {verifyPackage,installObserver,readState,stage,codeDigest,camera,hudMultitouch,controlledEntry,incomingBite,lowStrike,pistolKill,pauseAndRetry}from'./scenarios.mjs';
const config=JSON.parse(fs.readFileSync(process.argv[2]));for(const key of ['source','fingerprint','packageSha256'])assert(config.expect?.[key],'missing exact expected '+key);const output=path.resolve(config.output??'results'),pkg=verifyPackage(config.packageRoot,config.expect),browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:config.viewport??{width:1180,height:744},isMobile:true,hasTouch:true}),errors=[],probes=[],hash=x=>createHash('sha256').update(x).digest('hex');fs.mkdirSync(output,{recursive:true});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await installObserver(page,pkg.release,config.baseURL,probes);
const runStage=async(name,fn,options={})=>{const before=await readState(page),target=before.enemies.find(e=>e.key===options.targetKey);return stage(name,{identity:pkg.identity,stageHarnessHash:codeDigest(fn),inputHash:hash(JSON.stringify(options)),harnessFileSHA256:hash(fs.readFileSync(new URL('./scenarios.mjs',import.meta.url))),environment:{browser:'Chromium',version:browser.version(),viewport:{width:before.width,height:before.height},isMobile:true,hasTouch:true},preconditions:{area:before.area,pos:before.pos,weapon:before.weapon,alive:before.hp>0,targetKey:target?.key??null,targetHP:target?.hp??null},receiptDir:path.join(output,'stages'),rawOutputPath:path.join(output,name+'.raw.json')},async()=>{const observations=await fn(page,options);if(errors.length)throw Error(errors.join('\n'));observations.observerHashes=probes;return observations;});};
try{
 await page.goto(config.baseURL+'?touch=1');await page.tap('#enter');await page.waitForFunction(()=>window.__qa?.game&&document.getElementById('entry').hidden,null,{timeout:90000});
 if(config.profile==='camera')await runStage('camera.orientation',camera,config.camera);
 else if(config.profile==='hud'){await runStage('hud.multitouch',hudMultitouch);await runStage('hud.pause_retry',pauseAndRetry,config.retry);}
 else if(config.profile==='weapon'||config.profile==='animal'){
  await page.keyboard.press('g');await page.waitForFunction(()=>__qa.game.pistol.collected);if(config.entry)await runStage('setup.controlled_entry',controlledEntry,config.entry);
  if(config.profile==='animal'&&config.boundary!=='pistol'){
   await page.tap('#heavy');await page.waitForFunction(()=>__qa.game.player.weapon==='knife');if(config.boundary==='bite')await runStage('animal.incoming',incomingBite,config.animal);else if(config.boundary==='low')await runStage('animal.low',lowStrike,config.animal);else throw Error('animal boundary must be bite, low or pistol; do not improvise combined fight');
  }else{await runStage('weapon.pistol_death',pistolKill,config.weapon);await runStage('weapon.pause_retry',pauseAndRetry,config.retry);}
 }else throw Error('unknown profile');
}finally{fs.writeFileSync(path.join(output,'wrapper.json'),JSON.stringify({identity:pkg.identity,profile:config.profile,scope:'Stage receipts govern observations; wrapper exit remains process exit; physical device and cross-stage combined fight unproved.',errors,observerHashes:probes},null,2)+'\n');await browser.close();}
