import {openedCutting,openedLifecycle,openedFallback} from './opened.mjs';
import {crownKill,crownRestoreExpiry,crownColdRetry} from './crown.mjs';
import {territoryRoute,territoryBiteHurt,territoryDeath,territoryColdRetry} from './roach-territory.mjs';
// Invoke on the existing VPS against an already frozen/exported package.
const {chromium}=await import(process.env.PLAYWRIGHT_ENTRY??'/opt/frankendom-shadow/repo/node_modules/playwright/index.mjs');
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createHash}from'node:crypto';
import {verifyPackage,installObserver,readState,stage,codeDigest,camera,hudMultitouch,controlledEntry,waitSimulation,incomingBite,lowStrike,pistolKill,pauseAndRetry,pistolBodyCue,finisherPrepared,animalAppearanceRows,droneEncounter,animalCycleRows,portraitDodge,droneMeleeInput,dronePistolControl,preflightCompiled,equipPistol,inputDiagnostic,inputReadinessScenario,ordinaryInput}from'./scenarios.mjs';
import {gauntRows,gauntEncounter,gauntSupplier,gauntColdRetry,gauntCorpseReturn,gauntRestoreSetup} from './gaunt.mjs';
import {droneHeightView} from './drone-height.mjs';
import {packPaired,packIsolated} from './pack-chaser.mjs';
const config=JSON.parse(fs.readFileSync(process.argv[2]));for(const key of ['source','fingerprint','packageSha256'])assert(config.expect?.[key],'missing exact expected '+key);if(config.resumeRun)assert.equal(createHash('sha256').update(JSON.stringify(config.resumeRun)).digest('hex'),config.resumeRunSHA,'Captured run fixture digest mismatch');const output=path.resolve(config.output??'results/browser'),pkg=verifyPackage(config.packageRoot,config.expect),compatibility=preflightCompiled(config.packageRoot,config.expect,{meleeTrace:config.meleeTrace,packTrace:['pack-chaser','roach-territory'].includes(config.profile),moduleHash:config.observerModuleHash}),browser=await chromium.launch({headless:true,...(process.env.QA_SOFTWARE_WEBGL==='1'?{args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']}: {})}),page=await browser.newPage({viewport:config.viewport??{width:1180,height:744},isMobile:!config.desktop,hasTouch:!config.desktop,...(config.resumeRun?{storageState:{cookies:[],origins:[{origin:new URL(config.baseURL).origin,localStorage:[{name:'armagedom:area1-run:v1',value:JSON.stringify(config.resumeRun)}]}]}}:{})}),errors=[],probes=[],hash=x=>createHash('sha256').update(x).digest('hex');fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'probe-preflight.json'),JSON.stringify(compatibility,null,2)+'\n');page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await installObserver(page,pkg.release,config.baseURL,probes,{meleeTrace:config.meleeTrace,packTrace:['pack-chaser','roach-territory'].includes(config.profile)});
const runStage=async(name,fn,options={})=>{const before=await readState(page),target=before.enemies.find(e=>e.key===options.targetKey);return stage(name,{identity:pkg.identity,stageHarnessHash:codeDigest(fn),inputHash:hash(JSON.stringify(options)),moduleHash:hash(fs.readFileSync(new URL('./scenarios.mjs',import.meta.url))),runnerHash:hash(fs.readFileSync(new URL('./run.mjs',import.meta.url))),observerHash:hash(JSON.stringify(probes)),dependencies:{...(config.profile==='opened'?{openedModuleHash:hash(fs.readFileSync(new URL('./opened.mjs',import.meta.url)))}:{}),payloads:hash(JSON.stringify(pkg.release.files)),...(['split-crown','opened'].includes(config.profile)?{crownModuleHash:hash(fs.readFileSync(new URL('./crown.mjs',import.meta.url))),gauntModuleHash:hash(fs.readFileSync(new URL('./gaunt.mjs',import.meta.url)))}:{}),...(config.profile==='roach-territory'?{territoryModuleHash:hash(fs.readFileSync(new URL('./roach-territory.mjs',import.meta.url)))}:{}),...(config.profile==='gaunt-body'?{gauntModuleHash:hash(fs.readFileSync(new URL('./gaunt.mjs',import.meta.url)))}:{}),...(config.heightView?{heightModuleHash:hash(fs.readFileSync(new URL('./drone-height.mjs',import.meta.url)))}:{}),...(config.profile==='pack-chaser'?{packModuleHash:hash(fs.readFileSync(new URL('./pack-chaser.mjs',import.meta.url)))}:{})},environment:{browser:'Chromium',version:browser.version(),viewport:{width:before.width,height:before.height},isMobile:!config.desktop,hasTouch:!config.desktop},preconditions:{...(config.resumeRun?{fixture:{kind:'Captured genuine native-encounter run DTO, restored by normal cold-load',recordSHA:config.resumeRunSHA,sourceRawSHA:config.resumeRunSourceRawSHA}}:{}),area:before.area,pos:before.pos,weapon:before.weapon,alive:before.hp>0,targetKey:target?.key??null,targetHP:target?.hp??null},receiptDir:path.join(output,'stages'),rawOutputPath:path.join(output,name+'.raw.json')},async()=>{try{const observations=await fn(page,options);if(errors.length)throw Error(errors.join('\n'));observations.observerHashes=probes;return observations;}catch(error){error.diagnostic??=await inputDiagnostic(page);throw error;}});};
try{
 await page.goto(config.baseURL+'?touch=1');if(config.desktop)await page.click('#enter');else await page.tap('#enter');await page.waitForFunction(()=>window.__qa?.game&&document.getElementById('entry').hidden,null,{timeout:90000});
 if(config.profile==='opened'){if(config.fallbackOnly)await runStage('opened.narrow_space_fallback',openedFallback);else{await runStage('opened.native_cutting',openedCutting,{screenshotPath:path.join(output,'opened-portrait.png')});await runStage('opened.restore_expiry_cold_retry',openedLifecycle);await runStage('opened.narrow_space_fallback',openedFallback);}}
 else if(config.profile==='split-crown'){await runStage('crown.native_cutting',crownKill,{screenshotPath:path.join(output,'crown-portrait.png')});await runStage('crown.restore_expiry_continuation',crownRestoreExpiry);await runStage('crown.cold_retry',crownColdRetry);}
 else if(config.profile==='roach-territory'){if(config.territoryColdOnly)await runStage('territory.cold_retry',territoryColdRetry);else{if(!config.territoryMissingOnly)await runStage('territory.wake_chase_return',territoryRoute);else{await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);await controlledEntry(page,{areaId:'east'});}await runStage('territory.native_bite_hurt',territoryBiteHurt,{screenshotPath:path.join(output,'territory-landscape.png'),hurtOnly:!!config.territoryHurtOnly});await runStage('territory.death',territoryDeath);await runStage('territory.cold_retry',territoryColdRetry);}}
 else if(config.profile==='gaunt-body'){await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);if(!config.gauntMissingOnly)for(const cycle of ['A','B']){if(cycle==='B'){await ordinaryInput(page,()=>page.click('#retry'),{reset:true,label:'gaunt-cycle-b'});await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);}for(const [i,areaId]of ['westminster','east','south','westminster'].entries()){await runStage('gaunt.'+cycle.toLowerCase()+'.entry_'+areaId+'_'+i,controlledEntry,{areaId});await runStage('gaunt.'+cycle.toLowerCase()+'.rows_'+areaId+'_'+i,gauntRows,{cycle});}}if(!config.gauntMissingOnly)await runStage('gaunt.native_encounter',gauntEncounter,{screenshotPath:path.join(output,'gaunt-portrait.png')});await runStage('gaunt.supplier',gauntSupplier);if(config.gauntMissingOnly)await runStage('gaunt.restore_setup',gauntRestoreSetup);await runStage('gaunt.corpse_return',gauntCorpseReturn);await runStage('gaunt.cold_retry',gauntColdRetry);}
 else if(config.profile==='qa-readiness')await runStage('qa.hardened_input_adoption',inputReadinessScenario);
 else if(config.profile==='pack-chaser'){if(!config.isolatedOnly)await runStage('pack.paired',packPaired);else{await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);}await runStage(config.blockedOnly?'pack.blocked':'pack.isolated',packIsolated,{blockedOnly:!!config.blockedOnly});}
 else if(config.profile==='drone-melee'){for(const c of config.meleeCases??[])await runStage('drone.melee_'+c.action+'_'+(c.gap>3?'far':'near'),droneMeleeInput,c);if(config.heightView)await runStage('drone.raised_body_aim_bolt_pistol',droneHeightView,{hoverHeight:config.heightView.hoverHeight,screenshotPath:path.join(output,'raised-drone-portrait.png')});if(config.pistolControl)await runStage('drone.pistol_retained',dronePistolControl);}
 else if(config.profile==='portrait-dodge')await runStage('portrait.dodge_size_layout_roll',portraitDodge,config.dodge);
 else if(config.profile==='animal-cycle'){
  await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);
  for(const cycle of (config.resumeCycle==='B'?['B']:['A','B'])){if(cycle==='B'){await page.click('#retry');await waitSimulation(page,()=>__qa.game.animalCycle==='B',null,{seconds:3,label:'explicit-retry-cycle-b'});await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);}
   for(const [i,areaId]of ['westminster','east','south','westminster'].entries()){await runStage('cycle.'+cycle.toLowerCase()+'.entry_'+areaId+'_'+i,controlledEntry,{areaId});await runStage('cycle.'+cycle.toLowerCase()+'.rows_'+areaId+'_'+i,animalCycleRows,{cycle,...config.cycles[cycle]});}
  }
  await page.reload();await page.click('#enter');await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);await runStage('cycle.b.cold_refresh',animalCycleRows,{cycle:'B',...config.cycles.B});await page.click('#retry');await waitSimulation(page,()=>__qa.game.animalCycle==='A',null,{seconds:3,label:'explicit-retry-cycle-a'});await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);await runStage('cycle.a.reset_return',animalCycleRows,{cycle:'A',...config.cycles.A});
 }
 else if(config.profile==='drone'){await equipPistol(page);await runStage('drone.controlled_entry',controlledEntry,config.entry);await runStage('drone.encounter_persistence',droneEncounter,config.drone);}
 else if(config.profile==='animal-appearance'){for(const [i,areaId]of ['westminster','south','east','westminster'].entries()){await runStage('appearance.entry_'+areaId+'_'+i,controlledEntry,{areaId});await runStage('appearance.rows_'+areaId+'_'+i,animalAppearanceRows,config.appearance);}}
 else if(config.profile==='finisher-presentation'){const bundle=pkg.release.files.find(f=>/^assets\/index-.*\.js$/.test(f.path)),code=fs.readFileSync(path.join(config.packageRoot,bundle.path),'utf8');assert(/\.set\([\w$]+\.x\*1\.6,1\.8,-[\w$]+\.z\*1\.6\)/.test(code),'compiled finisher launch constants');await runStage('finisher.prepared_boundary',finisherPrepared,config.finisher);}
 else if(config.profile==='pistol-cue'){await equipPistol(page);await runStage('setup.controlled_entry',controlledEntry,config.entry);await runStage('pistol.body_edge_cue',pistolBodyCue,config.cue);}
 else if(config.profile==='camera')await runStage('camera.orientation',camera,config.camera);
 else if(config.profile==='hud'){await runStage('hud.multitouch',hudMultitouch);await runStage('hud.pause_retry',pauseAndRetry,config.retry);}
 else if(config.profile==='weapon'||config.profile==='animal'){
  await equipPistol(page);if(config.entry)await runStage('setup.controlled_entry',controlledEntry,config.entry);
  if(config.profile==='animal'&&config.boundary!=='pistol'){
   await page.tap('#heavy');await waitSimulation(page,()=>__qa.game.player.weapon==='knife',null,{seconds:3,label:'ordinary-holster'});if(config.boundary==='bite')await runStage('animal.incoming',incomingBite,config.animal);else if(config.boundary==='low')await runStage('animal.low',lowStrike,config.animal);else throw Error('animal boundary must be bite, low or pistol; do not improvise combined fight');
  }else{await runStage('weapon.pistol_death',pistolKill,config.weapon);await runStage('weapon.pause_retry',pauseAndRetry,config.retry);}
 }else throw Error('unknown profile');
}finally{fs.writeFileSync(path.join(output,'wrapper.json'),JSON.stringify({identity:pkg.identity,profile:config.profile,scope:'Stage receipts govern observations; wrapper exit remains process exit; physical device and cross-stage combined fight unproved.',errors,observerHashes:probes},null,2)+'\n');await browser.close();}
