// QA only: ordinary input and read-only observations, never game-field writes.
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const stable=value=>JSON.stringify(value&&typeof value==='object'?Array.isArray(value)?value.map(v=>JSON.parse(stable(v))):Object.fromEntries(Object.keys(value).sort().map(k=>[k,JSON.parse(stable(value[k]))])):value);
export function verifyPackage(root,expected={}){
 const bytes=fs.readFileSync(path.join(root,'release.json')),release=JSON.parse(bytes),identity={source:release.sourceCommit,fingerprint:release.sourceFingerprint,packageSha256:sha(bytes)};
 for(const [key,value]of Object.entries(expected))assert.equal(identity[key],value,key);
 for(const f of release.files){const resolved=path.resolve(root,f.path);assert(resolved.startsWith(path.resolve(root)+path.sep),'package path outside export');const raw=fs.readFileSync(resolved);assert.equal(raw.length,f.bytes,f.path);assert.equal(sha(raw),f.sha256,f.path);}
 return{identity,release};
}
export function codeDigest(scenario){return sha([scenario.toString(),installObserver.toString(),stage.toString(),readState.toString(),aimAt.toString(),legal.toString(),waitEvent.toString()].join('\n'));}
export function reuseMatches(receipt,current){
 return receipt.status==='passed'&&['identity','stageHarnessHash','inputHash','environment','preconditions'].every(k=>stable(receipt[k])===stable(current[k]))&&fs.existsSync(receipt.rawOutputPath)&&sha(fs.readFileSync(receipt.rawOutputPath))===receipt.rawOutputSha256;
}
export async function stage(name,context,run){
 assert(/^[a-z0-9_.-]+$/i.test(name),'unsafe stage name');for(const key of ['identity','stageHarnessHash','inputHash','environment','preconditions','rawOutputPath','receiptDir'])assert(context[key]!==undefined,'missing '+key);
 for(const key of ['stageHarnessHash','inputHash'])assert(/^[a-f0-9]{64}$/.test(context[key]),'invalid '+key);assert(/^[a-f0-9]{40}$/.test(context.identity.source),'exact source SHA required');for(const key of ['fingerprint','packageSha256'])assert(/^[a-f0-9]{64}$/.test(context.identity[key]),'invalid package '+key);
 const record={name,...context,startedUTC:new Date().toISOString()};let failure;
 try{record.observations=await run();assert(record.observations&&typeof record.observations==='object','stage requires observed data');record.status='passed';}catch(error){record.status='failed';record.error=String(error.stack??error);failure=error;}
 record.completedUTC=new Date().toISOString();fs.mkdirSync(path.dirname(context.rawOutputPath),{recursive:true});fs.writeFileSync(context.rawOutputPath,JSON.stringify({observations:record.observations,error:record.error},null,2)+'\n');record.rawOutputSha256=sha(fs.readFileSync(context.rawOutputPath));fs.mkdirSync(context.receiptDir,{recursive:true});const destination=path.join(context.receiptDir,name+'.json'),temporary=destination+'.tmp';fs.writeFileSync(temporary,JSON.stringify(record,null,2)+'\n');fs.renameSync(temporary,destination);if(failure)throw failure;return record;
}
export function installObserver(page,release,base,probes=[]){
 return page.route(/\/assets\/index-[^/]+\.js$/,async route=>{const response=await route.fetch(),body=await response.body(),code=body.toString(),f=release.files.find(f=>new URL(f.path,base).href===route.request().url());assert(f);assert.equal(sha(body),f.sha256);const tail=code.slice(code.lastIndexOf('getElementById("world")')),m=tail.match(/area:([\w$]+)\.areaId,position:([\w$]+)\.player\.pos/),actor=tail.match(/([\w$]+)\.views\.get\(0\)/);assert(m&&actor,'main observation seam changed');const anchor=code.indexOf('console.info("ARMAGEDOM_TRAVEL"'),travel=[...code.slice(0,anchor).matchAll(/async function ([\w$]+)\(([\w$]+)\)\{/g)].at(-1);assert(anchor>0&&travel,'existing travel seam changed');const events=[...code.matchAll(/function ([\w$]+)\(([\w$]+),([\w$]+),([\w$]+)=\{\}\)\{\2\.events\.push\(\{type:\3,\.\.\.\4\}\)\}/g)];assert.equal(events.length,1,'event observation seam changed');const [fn,G,T,D]=[events[0][0],events[0][2],events[0][3],events[0][4]],probe=';if(globalThis.__qaEvents&&__qaEvents.length<2000)__qaEvents.push({type:'+T+',tick:'+G+'.tick,time:'+G+'.time,actor:'+D+'.actor?.id,key:'+D+'.actor?.placementKey,attacker:'+D+'.attackerId,move:'+D+'.moveId,clip:'+D+'.clip,amount:'+D+'.amount,weapon:'+D+'.weapon,recipe:'+D+'.actor?.finisher?.recipeId,goal:'+D+'.actor?.swing?.calfGoal,footY:'+D+'.actor?.swing?.footGoalY})';const suffix='\nwindow.__qa={get world(){return '+m[1]+'},get game(){return '+m[2]+'},get actors(){return '+actor[1]+'},get crossArea(){return '+travel[1]+'}};window.__qaEvents=[];';const observed=code.replace(fn,fn.slice(0,-1)+probe+'}')+suffix;probes.push({payloadSHA256:f.sha256,observerSHA256:sha(observed)});await route.fulfill({response,body:observed});});
}
export function readState(page){return page.evaluate(()=>{const q=__qa,g=q.game,p=g.player,w=q.world,rect=id=>{const r=document.getElementById(id).getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}},foot=w.toRender(p.pos).project(w.camera),head=w.toRender(p.pos,2*w.actorScale).project(w.camera);return{area:w.areaId,time:g.time,tick:g.tick,hp:p.hp,pos:{...p.pos},weapon:p.weapon,stamina:p.stamina,swing:p.swing?{move:p.swing.moveId,age:p.swing.ageTicks}:null,guard:p.guarding,width:innerWidth,height:innerHeight,scale:visualViewport?.scale,offsetLeft:visualViewport?.offsetLeft,offsetTop:visualViewport?.offsetTop,pixels:Math.abs(head.y-foot.y)*innerHeight/2,move:rect('move'),actions:rect('action-cluster'),pistol:{...g.pistol},supplies:structuredClone(g.supplies),saved:JSON.parse(localStorage.getItem('armagedom:area1-run:v1')),enemies:g.enemies.map(e=>({id:e.id,key:e.placementKey,rig:e.rig,hp:e.hp,pos:{...e.pos},radius:e.radius,swing:e.swing?{age:e.swing.ageTicks,move:e.swing.moveId}:null})),corpses:g.corpses.map(e=>({key:e.placementKey,finisher:e.finisher,clip:(q.actors.views.get(e.id)?.motion.native??q.actors.views.get(e.id)?.motion)?.currentClip,renderedFinisher:q.actors.views.get(e.id)?.finisher?.stats()})),events:structuredClone(__qaEvents),heads:w.scene.children.filter(o=>o.name==='Prepared detached Hollow head').length};});}
async function aimAt(page,id){const point=await page.evaluate(id=>{const q=__qa,e=q.game.enemies.find(e=>e.id===id);if(!e)throw Error('target missing');const p=q.world.toRender(e.pos).project(q.world.camera);return{x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2};},id);await page.mouse.move(point.x,point.y);return point;}
async function legal(page){await page.waitForFunction(()=>{const g=__qa.game,p=g.player;if(p.hp<=0)throw Error('player dead');return !g.finished&&!p.swing&&g.time>=p.ready&&g.time>=p.hurtUntil&&g.time>=p.dodgeUntil;},null,{timeout:8000});}
async function waitEvent(page,expected){return page.waitForFunction(expected=>{if(__qa.game.player.hp<=0)throw Error('player dead');return __qaEvents.find(e=>Object.entries(expected).every(([k,v])=>e[k]===v));},expected,{timeout:8000});}
export async function controlledEntry(page,entry){await page.evaluate(entry=>__qa.crossArea(entry),entry);await page.waitForFunction(area=>__qa.world.areaId===area,entry.areaId);return{controlledEntry:entry,walkedRoute:false,state:await readState(page)};}
export async function camera(page,{landscape={width:1180,height:744},portrait={width:820,height:1104}}={}){
 await page.setViewportSize(landscape);await page.waitForFunction(size=>__qa.world.width===size.width&&__qa.world.height===size.height,landscape);const before=await readState(page);await page.setViewportSize(portrait);await page.waitForFunction(size=>__qa.world.width===size.width&&__qa.world.height===size.height,portrait);const upright=await readState(page);await page.setViewportSize(landscape);await page.waitForFunction(size=>__qa.world.width===size.width&&__qa.world.height===size.height,landscape);const after=await readState(page);assert.deepEqual(after.pos,before.pos,'camera comparison requires identical player position');assert(Math.abs(after.pixels-before.pixels)<1e-8);for(const key of ['move','actions'])assert.deepEqual(after[key],before[key]);for(const s of [before,upright,after]){assert.equal(s.scale,1);for(const key of ['move','actions']){const r=s[key];assert(r.x>=0&&r.y>=0&&r.right<=s.width+1&&r.bottom<=s.height+1);}}return{before,portrait:upright,after,scope:'orientation pixel/geometry only; no physical-device gesture proof'};
}
export async function hudMultitouch(page){
 const cdp=await page.context().newCDPSession(page),send=(type,touchPoints)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints}),center=async id=>{const r=await page.locator('#'+id).boundingBox();return{x:r.x+r.width/2,y:r.y+r.height/2}},origin=await center('move'),slash=await center('slash'),guard=await center('guard'),move={id:41,...origin},shift={...move,x:move.x+30,y:move.y-20},before=await readState(page);try{await send('touchStart',[move]);await send('touchMove',[shift]);await send('touchStart',[shift,{id:42,...slash}]);await page.waitForFunction(()=>!!__qa.game.player.swing);const slashState=await readState(page);assert(Math.hypot(slashState.pos.x-before.pos.x,slashState.pos.z-before.pos.z)>.01);await send('touchEnd',[shift]);await send('touchEnd',[]);await legal(page);await send('touchStart',[move]);await send('touchMove',[shift]);await send('touchStart',[shift,{id:43,...guard}]);await page.waitForFunction(()=>__qa.game.player.guarding);const guardState=await readState(page);await send('touchCancel',[]);await page.waitForFunction(()=>!__qa.game.player.guarding);return{before,slashState,guardState,cancelled:await readState(page),scope:'trusted Chromium native touch; not physical Safari'};}finally{await send('touchCancel',[]).catch(()=>{});}
}
export async function incomingBite(page,{targetKey,damage,move}){
 const before=await readState(page),target=before.enemies.find(e=>e.key===targetKey);assert(target);assert.equal(before.weapon,'knife','setup must use ordinary holster before this stage');await aimAt(page,target.id);await waitEvent(page,{type:'hit',actor:0,attacker:target.id,amount:damage,move});return{before,after:await readState(page)};
}
export async function lowStrike(page,{targetKey,move,damage=10}){
 const before=await readState(page),target=before.enemies.find(e=>e.key===targetKey);assert(target);assert.equal(before.weapon,'knife');const point=await aimAt(page,target.id);await page.keyboard.down('f');let decision;try{decision=await page.waitForFunction(id=>{const g=__qa.game,p=g.player,e=g.enemies.find(e=>e.id===id),s=e?.swing;if(p.hp<=0)throw Error('player dead');const first=s?.def.windupTicks+s?.def.activeTicks;if(p.guarding&&!p.swing&&g.time>=p.ready&&g.time>=p.hurtUntil&&p.stamina>=18&&s?.ageTicks>=first&&s.ageTicks<=first+4)return{tick:g.tick,age:s.ageTicks,first};return false;},target.id,{timeout:15000});await page.mouse.click(point.x,point.y);}finally{await page.keyboard.up('f');}await waitEvent(page,{type:'hit',actor:target.id,move,amount:damage});const after=await readState(page),accepted=after.events.find(e=>e.type==='attack'&&e.actor===0&&e.move===move),prior=after.events.filter(e=>e.type==='enemy-attack'&&e.actor===target.id&&e.tick<=accepted.tick).at(-1);assert.equal(after.enemies.find(e=>e.id===target.id).hp,target.hp-damage);return{before,after,decision:await decision.jsonValue(),acceptedTick:accepted.tick,relativeToEnemyStart:accepted.tick-prior.tick};
}
export async function pistolKill(page,{targetKey,damageSteps,expectedRecipe='ordinary',expectedClip}){
 const before=await readState(page),target=before.enemies.find(e=>e.key===targetKey);assert(target);assert.equal(before.weapon,'pistol','gun-first setup must already be equipped through ordinary input');const counts=before.events.filter(e=>e.type==='hit'&&e.actor===target.id&&e.weapon==='pistol').length,shots=[];for(let n=0;n<damageSteps.length;n++){await aimAt(page,target.id);await page.waitForFunction(id=>{const m=__qa.world.scene.getObjectByName('Pistol aim marker');return m.userData.targetId===id&&m.userData.ready;},target.id,{timeout:8000});await page.mouse.down();try{await page.waitForFunction(({id,count})=>__qaEvents.filter(e=>e.type==='hit'&&e.actor===id&&e.weapon==='pistol').length>count,{id:target.id,count:counts+n},{timeout:8000});}finally{await page.mouse.up();}shots.push(await readState(page));}if(expectedClip)await page.waitForFunction(({key,clip})=>{const q=__qa,e=q.game.corpses.find(e=>e.placementKey===key),v=e&&q.actors.views.get(e.id);return (v?.motion.native??v?.motion)?.currentClip===clip;},{key:targetKey,clip:expectedClip},{timeout:8000});const after=await readState(page),hits=after.events.filter(e=>e.type==='hit'&&e.actor===target.id&&e.weapon==='pistol').slice(counts),corpse=after.corpses.find(e=>e.key===targetKey);assert.deepEqual(hits.map(e=>e.amount),damageSteps);assert(corpse);assert.equal(corpse.finisher.recipeId,expectedRecipe);assert.equal(after.pistol.magazine,before.pistol.magazine-damageSteps.length);assert.equal(after.saved.pistol.magazine,after.pistol.magazine);assert.equal(after.saved.hp,after.hp);return{before,shots,after,heldUntilActualShotAcknowledgement:true};
}
export async function pauseAndRetry(page,{area='westminster',enemyCount=6}={}){
 await page.tap('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);const paused=await readState(page);await page.waitForTimeout(200);const pausedLater=await readState(page);assert.equal(pausedLater.time,paused.time);await page.tap('#close-menu');await page.waitForFunction(time=>!document.getElementById('menu').open&&__qa.game.time>time,paused.time);const resumed=await readState(page);await page.keyboard.press('r');await page.waitForFunction(({area,enemyCount})=>__qa.world.areaId===area&&__qa.game.enemies.length===enemyCount&&__qa.game.corpses.length===0&&__qa.game.player.hp===150,{area,enemyCount});const retry=await readState(page);assert.equal(retry.pistol.collected,false);assert.deepEqual(retry.supplies.issued,[]);assert.equal(retry.heads,0);return{paused,pausedLater,resumed,retry};
}
