// QA only: ordinary input and read-only observations, never game-field writes.
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const stable=value=>JSON.stringify(value&&typeof value==='object'?Array.isArray(value)?value.map(v=>JSON.parse(stable(v))):Object.fromEntries(Object.keys(value).sort().map(k=>[k,JSON.parse(stable(value[k]))])):value);
export function verifyPackage(root,expected={}){
 const bytes=fs.readFileSync(path.join(root,'release.json')),release=JSON.parse(bytes),identity={source:release.sourceCommit,fingerprint:release.sourceFingerprint,packageSha256:sha(bytes)};
 for(const [key,value]of Object.entries(expected))assert.equal(identity[key],value,key);
 for(const f of release.files){const resolved=path.resolve(root,f.path);assert(resolved.startsWith(path.resolve(root)+path.sep),'package path outside export');const raw=fs.readFileSync(resolved);assert.equal(raw.length,f.bytes,f.path);assert.equal(sha(raw),f.sha256,f.path);}
 return{identity,release};
}
// Gameplay waits follow the unmodified game clock, with an independent wall cap.
export function evaluateSimulationWait(start,now,{seconds=6,wallMs=90000}={},check){
 if(now.wall-start.wall>=wallMs)throw Error('Gameplay wait wall cap exceeded '+JSON.stringify(now));
 const result=check();if(result)return result;
 if(now.time-start.time>=seconds)throw Error('Gameplay wait simulation deadline exceeded '+JSON.stringify(now));
 return false;
}
export async function waitSimulation(page,predicate,arg=null,{seconds=6,wallMs=90000,label='gameplay'}={}){
 assert(Number.isFinite(seconds)&&seconds>0&&Number.isFinite(wallMs)&&wallMs>0,'finite wait limits required');
 const start=await page.evaluate(label=>{const g=__qa.game,record={label,start:{time:g.time,tick:g.tick,wall:performance.now()},trace:[]};(window.__qaWaits??=[]).push(record);return record.start;},label);
 const expression=`cfg=>{const g=__qa.game,f=window.__qaFrames,now={time:g.time,tick:g.tick,wall:performance.now(),frames:f?.count??null,meanFrameMs:f?.times?.length>1?(f.times.at(-1)-f.times[0])/(f.times.length-1):null,visibility:document.visibilityState,menuOpen:!!document.getElementById('menu')?.open},record=window.__qaWaits.at(-1);if(!record.trace.length||now.wall-record.trace.at(-1).wall>=1000){record.trace.push(now);if(record.trace.length>100)record.trace.shift();}return (${evaluateSimulationWait.toString()})(cfg.start,now,cfg.limits,()=>(${predicate.toString()})(cfg.arg));}`;
 const callback=new Function('cfg','return ('+expression+')(cfg)');
 return page.waitForFunction(callback,{start,limits:{seconds,wallMs},arg},{timeout:wallMs+1000,polling:100});
}
export function evaluateInputReadiness(before,now,{reset=false,phase='resume'}={}){
 if(!now.namespaceReady)return{ready:false,reason:'game observation unavailable'};
 if(!Number.isFinite(now.time)||!Number.isInteger(now.tick))return{ready:false,fatal:true,classification:'runtime',reason:'invalid simulation clock'};
 if(!(now.hp>0)||now.finished)return{ready:false,fatal:true,classification:'runtime',reason:'player not alive or run finished'};
 if(now.menuOpen)return{ready:false,reason:'menu still open'};
 const advanced=reset?now.resetAcknowledged&&now.time>0&&now.tick>0:!now.resetAcknowledged&&now.time>before.time&&now.tick>before.tick;
 if(!advanced)return{ready:false,reason:reset?'fresh reset not acknowledged and advanced':'simulation has not advanced after action'};
 if(!['resume','pickup','equip'].includes(phase))throw Error('Unknown input readiness phase');
 if(phase!=='resume'&&!now.pistolPresent)return{ready:false,fatal:true,classification:'setup',reason:'pistol unavailable'};
 if(phase==='pickup'&&!now.collected&&(now.area!==now.pickupArea||!Number.isFinite(now.pickupDistance)||now.pickupDistance>1.3))return{ready:false,fatal:true,classification:'setup',reason:'registered pistol pickup unavailable or out of range'};
 if(phase==='equip'&&(!now.collected||!now.equipped))return{ready:false,reason:now.collected?'equip acknowledgement pending':'pickup acknowledgement pending'};
 return{ready:true,phase};
}
export function inputReadinessSnapshot(){
 const q=globalThis.__qa,g=q?.game,p=g?.player,s=g?.pistol,m=q?.world?.scene?.getObjectByName('Pistol aim marker');
 return{namespaceReady:!!g,time:g?.time,tick:g?.tick,hp:p?.hp,finished:g?.finished,menuOpen:!!document.getElementById('menu')?.open,resetAcknowledged:g!==window.__qaInputBefore,area:q?.world?.areaId,position:p?.pos?{...p.pos}:null,weapon:p?.weapon,pistol:s?{...s}:null,hurtUntil:p?.hurtUntil,readyAt:p?.ready,playerSwing:p?.swing?{move:p.swing.moveId,age:p.swing.ageTicks}:null,pistolPresent:!!s,collected:!!s?.collected,equipped:!!s?.equipped,pickupArea:s?.pickupAreaId,pickupDistance:s&&p?Math.hypot(p.pos.x-s.pickupPos.x,p.pos.z-s.pickupPos.z):null,inputMode:{touch:document.body.classList.contains('touch'),mobileAiming:!!g?.mobileAiming,userFacing:g?.pistolUserFacing?{...g.pistolUserFacing}:null},cue:{visible:!!m?.visible,target:m?.userData.targetId??null,ready:!!m?.userData.ready}};
}
export async function ordinaryInput(page,action,{reset=false,phase='resume',label='ordinary-input'}={}){
 const before=await page.evaluate(()=>{window.__qaInputBefore=__qa.game;return{time:__qa.game.time,tick:__qa.game.tick};});await action();
 const predicate=new Function('cfg',`const snapshot=(${inputReadinessSnapshot.toString()})(),result=(${evaluateInputReadiness.toString()})(cfg.before,snapshot,cfg.options);(window.__qaInputChecks??=[]).push({snapshot,result});if(window.__qaInputChecks.length>100)window.__qaInputChecks.shift();if(result.fatal)throw Error('QA_INPUT_'+result.classification.toUpperCase()+': '+result.reason+' '+JSON.stringify(snapshot));return result.ready?{snapshot,result}:false;`);
 try{const handle=await waitSimulation(page,predicate,{before,options:{reset,phase}},{seconds:3,label});return await handle.jsonValue();}catch(error){error.diagnostic=await inputDiagnostic(page);throw error;}
}
export async function inputDiagnostic(page){
 try{const callback=new Function(`return{state:(${inputReadinessSnapshot.toString()})(),readiness:window.__qaInputChecks?.at(-1),waits:window.__qaWaits?.at(-1)};`);return await page.evaluate(callback);}catch(error){return{unavailable:String(error)};}
}
export async function equipPistol(page){
 const collected=await page.evaluate(()=>!!__qa.game.pistol?.collected);const ready=await ordinaryInput(page,async()=>{},{phase:collected?'resume':'pickup',label:'pistol-pickup-prerequisite'});if(ready.snapshot.collected&&ready.snapshot.equipped)return ready;
 return ordinaryInput(page,()=>page.keyboard.press('g'),{phase:'equip',label:'ordinary-equip-acknowledgement'});
}
export async function holsterPistol(page){
 const before=await readState(page);await legal(page);
 if(before.weapon==='pistol')await ordinaryInput(page,()=>page.tap('#heavy'),{label:'ordinary-visible-holster'});
 else await ordinaryInput(page,async()=>{},{label:'already-holstered-clock'});
 await waitSimulation(page,()=>__qa.game.player.weapon==='knife'&&!__qa.game.pistol.equipped,null,{seconds:3,label:'ordinary-holster-acknowledgement'});
 return{before,after:await readState(page)};
}
export function codeDigest(scenario){return sha([scenario.toString(),verifyCamera.toString(),installObserver.toString(),stage.toString(),readState.toString(),aimAt.toString(),legal.toString(),waitEvent.toString(),waitSimulation.toString(),evaluateSimulationWait.toString(),evaluateInputReadiness.toString(),inputReadinessSnapshot.toString(),ordinaryInput.toString(),equipPistol.toString()].join('\n'));}
export function reuseMatches(receipt,current){
 return receipt.status==='passed'&&['identity','stageHarnessHash','moduleHash','runnerHash','observerHash','dependencies','inputHash','environment','preconditions'].every(k=>receipt[k]!==undefined&&current[k]!==undefined&&stable(receipt[k])===stable(current[k]))&&fs.existsSync(receipt.rawOutputPath)&&sha(fs.readFileSync(receipt.rawOutputPath))===receipt.rawOutputSha256;
}
export async function stage(name,context,run){
 assert(/^[a-z0-9_.-]+$/i.test(name),'unsafe stage name');for(const key of ['identity','stageHarnessHash','moduleHash','runnerHash','observerHash','dependencies','inputHash','environment','preconditions','rawOutputPath','receiptDir'])assert(context[key]!==undefined,'missing '+key);
 for(const key of ['stageHarnessHash','moduleHash','runnerHash','observerHash','inputHash'])assert(/^[a-f0-9]{64}$/.test(context[key]),'invalid '+key);assert(/^[a-f0-9]{40}$/.test(context.identity.source),'exact source SHA required');for(const key of ['fingerprint','packageSha256'])assert(/^[a-f0-9]{64}$/.test(context.identity[key]),'invalid package '+key);
 const finalReceipt=path.join(context.receiptDir,name+'.json');assert(!fs.existsSync(context.rawOutputPath)&&!fs.existsSync(finalReceipt),'attempt paths already exist; use a new attempt directory');
 const record={name,...context,startedUTC:new Date().toISOString()};let failure;
 try{record.observations=await run();assert(record.observations&&typeof record.observations==='object','stage requires observed data');record.status='passed';}catch(error){record.status='failed';record.error=String(error.stack??error);failure=error;record.diagnostic=error.diagnostic;}
 record.completedUTC=new Date().toISOString();fs.mkdirSync(path.dirname(context.rawOutputPath),{recursive:true});fs.writeFileSync(context.rawOutputPath,JSON.stringify({observations:record.observations,error:record.error,diagnostic:record.diagnostic},null,2)+'\n');record.rawOutputSha256=sha(fs.readFileSync(context.rawOutputPath));fs.mkdirSync(context.receiptDir,{recursive:true});const destination=path.join(context.receiptDir,name+'.json'),temporary=destination+'.tmp';fs.writeFileSync(temporary,JSON.stringify(record,null,2)+'\n');fs.renameSync(temporary,destination);if(failure)throw failure;return record;
}
function meleeProbe(code){
 const matches=[...code.matchAll(/hit:\(([\w$,]+)\)=>\{/g)].filter(m=>m[1].split(',').length===5);assert.equal(matches.length,1,'physical contact observer seam');const m=matches[0],open=code.indexOf('{',m.index);let depth=1,end=open+1,quote=null;for(;end<code.length&&depth;end++){const c=code[end];if(quote){if(c==='\\')end++;else if(c===quote)quote=null;}else if(c==='"'||c==="'")quote=c;else if(c==='{')depth++;else if(c==='}')depth--;}
 const body=code.slice(open+1,end-1),[a,d,s,before,after]=m[1].split(','),blade=body.match(/([\w$]+)\(([\w$]+)\.clip==="DogMidSlash"\?([\w$]+):([\w$]+),\2\.ageTicks\/60,([\w$]+)\.playerRoot\)/);assert(blade&&body.includes('ARM_Drone_Rigid_Frame'),'native Low/frame seam');
 const probe=`const __qaContactResult=(()=>{${body}})();if(globalThis.__qaMelee&&${d}.rig==="low-hover-drone"&&__qaMelee.length<160){const __qaV=${after}?.rats?.get(${d}.id)?.view,__qaF=__qaV?.model.getObjectByName("ARM_Drone_Rigid_Frame");__qaMelee.push({action:${s}.action,move:${s}.moveId,clip:${s}.clip,age:${s}.ageTicks,lowTargetId:${s}.lowTargetId??null,actor:${a}.id,target:${d}.id,hp:${d}.hp,gap:Math.hypot(${a}.pos.x-${d}.pos.x,${a}.pos.z-${d}.pos.z),ratLow:!!${s}.def.ratLow,result:__qaContactResult,playerRoot:${after}.playerRoot.toArray(),blade:${s}.def.ratLow?${blade[0]}:null,frame:__qaF?{name:__qaF.name,index:__qaF.geometry.index.count,matrix:__qaF.matrixWorld.toArray()}:null});}return __qaContactResult;`;
 return code.slice(0,open+1)+probe+code.slice(end-1);
}
function packProbe(code){
 const anchors=[...code.matchAll(/([\w$]+)\.packMovement="native"/g)];assert.equal(anchors.length,1,'Pack native observer seam');const anchor=anchors[0],m=[...code.slice(0,anchor.index).matchAll(/function ([\w$]+)\(([\w$]+),([\w$]+),([\w$]+)\)\{/g)].at(-1);assert(m&&m[3]===anchor[1],'Pack actor observer binding');const open=code.indexOf('{',m.index);let depth=1,end=open+1,quote=null;for(;end<code.length&&depth;end++){const c=code[end];if(quote){if(c==='\\')end++;else if(c===quote)quote=null;}else if(c==='"'||c==="'")quote=c;else if(c==='{')depth++;else if(c==='}')depth--;}
 return code.slice(0,open+1)+'try{'+code.slice(open+1,end-1)+'}finally{if('+m[3]+'.residentIntent)globalThis.__qaPackTick?.();}'+code.slice(end-1);
}
export function prepareObserver(body,release,base,url,options={}){
 body=Buffer.from(body);try{
 const code=body.toString(),f=release.files.find(f=>new URL(f.path,base).href===url);assert(f,'compiled payload not listed');assert.equal(body.length,f.bytes,'compiled payload byte identity');assert.equal(sha(body),f.sha256,'compiled payload SHA identity');const tail=code.slice(code.lastIndexOf('getElementById("world")')),mainMatches=[...tail.matchAll(/area:([\w$]+)\.areaId,position:([\w$]+)\.player\.pos/g)],actorMatches=[...tail.matchAll(/([\w$]+)\.views\.get\(0\)/g)];assert.equal(mainMatches.length,1,'main observation seam expected exactly one');assert.equal(actorMatches.length,1,'actor observation seam expected exactly one');const m=mainMatches[0],actor=actorMatches[0];assert.equal([...code.matchAll(/console\.info\("ARMAGEDOM_TRAVEL"/g)].length,1,'travel observation anchor expected exactly one');const anchor=code.indexOf('console.info("ARMAGEDOM_TRAVEL"'),travel=[...code.slice(0,anchor).matchAll(/async function ([\w$]+)\(([\w$]+)\)\{/g)].at(-1);assert(anchor>0&&travel,'existing travel seam changed');const events=[...code.matchAll(/function ([\w$]+)\(([\w$]+),([\w$]+),([\w$]+)=\{\}\)\{\2\.events\.push\(\{type:\3,\.\.\.\4\}\)\}/g)];assert.equal(events.length,1,'event observation seam changed');const [fn,G,T,D]=[events[0][0],events[0][2],events[0][3],events[0][4]],probe=';if(globalThis.__qaEvents&&__qaEvents.length<2000)__qaEvents.push({type:'+T+',tick:'+G+'.tick,time:'+G+'.time,actor:'+D+'.actor?.id,key:'+D+'.actor?.placementKey,attacker:'+D+'.attackerId,move:'+D+'.moveId,clip:'+D+'.clip,amount:'+D+'.amount,weapon:'+D+'.weapon,recipe:'+D+'.actor?.finisher?.recipeId,bolt:'+T+'==="enemy-attack"&&'+D+'.moveId==="drone_bolt"?structuredClone('+G+'.bolts.at(-1)):null,goal:'+D+'.actor?.swing?.calfGoal,footY:'+D+'.actor?.swing?.footGoalY})';const suffix='\nwindow.__qa={get world(){return '+m[1]+'},get game(){return '+m[2]+'},get actors(){return '+actor[1]+'},get crossArea(){return '+travel[1]+'}};window.__qaEvents=[];';let observed=code.replace(fn,fn.slice(0,-1)+probe+'}')+suffix;if(options.meleeTrace)observed=meleeProbe(observed)+'\nwindow.__qaMelee=[];';if(options.packTrace)observed=packProbe(observed);return{observed,probe:{payloadSHA256:f.sha256,observerSHA256:sha(observed)}};
 }catch(error){const failure=new Error('QA_PROBE_COMPATIBILITY: '+error.message+'; payload='+sha(body)+'; module='+sha(fs.readFileSync(new URL('./scenarios.mjs',import.meta.url))),{cause:error});failure.code='QA_PROBE_COMPATIBILITY';throw failure;}
}
export function preflightCompiled(root,expected,options={}){
 const moduleHash=sha(fs.readFileSync(new URL('./scenarios.mjs',import.meta.url)));if(options.moduleHash!==undefined)assert.equal(moduleHash,options.moduleHash,'observer module identity mismatch');const pkg=verifyPackage(root,expected),bundles=pkg.release.files.filter(f=>/^assets\/index-.*\.js$/.test(f.path));assert.equal(bundles.length,1,'Expected one exact compiled main bundle');const f=bundles[0],base='http://qa-preflight/',prepared=prepareObserver(fs.readFileSync(path.join(root,f.path)),pkg.release,base,new URL(f.path,base).href,options),dir=fs.mkdtempSync(path.join(os.tmpdir(),'armagedom-probe-'));
 try{const file=path.join(dir,'observed.mjs');fs.writeFileSync(file,prepared.observed);const result=spawnSync(process.execPath,['--check',file],{encoding:'utf8'});if(result.error)throw result.error;if(result.status!==0)throw Error('QA_PROBE_SYNTAX: '+result.stderr);}finally{fs.rmSync(dir,{recursive:true,force:true});}
 return{status:'PASS_COMPILED_PROBE_PREFLIGHT',identity:pkg.identity,...prepared.probe,moduleHash,options};
}
export async function installObserver(page,release,base,probes=[],options={}){
 await page.addInitScript(()=>{window.__qaFrames={count:0,times:[]};const request=window.requestAnimationFrame.bind(window);window.requestAnimationFrame=callback=>request(ms=>{const f=window.__qaFrames;if(f.times.at(-1)!==ms){f.count++;f.times.push(ms);if(f.times.length>180)f.times.shift();}callback(ms);});});
 return page.route(/\/assets\/index-[^/]+\.js$/,async route=>{const response=await route.fetch(),prepared=prepareObserver(await response.body(),release,base,route.request().url(),options);probes.push(prepared.probe);await route.fulfill({response,body:prepared.observed});});
}
export function readState(page){return page.evaluate(()=>{const q=__qa,g=q.game,p=g.player,w=q.world,rect=id=>{const r=document.getElementById(id).getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}},foot=w.toRender(p.pos).project(w.camera),head=w.toRender(p.pos,2*w.actorScale).project(w.camera);return{area:w.areaId,time:g.time,tick:g.tick,hp:p.hp,pos:{...p.pos},weapon:p.weapon,stamina:p.stamina,swing:p.swing?{move:p.swing.moveId,age:p.swing.ageTicks}:null,guard:p.guarding,width:innerWidth,height:innerHeight,scale:visualViewport?.scale,offsetLeft:visualViewport?.offsetLeft,offsetTop:visualViewport?.offsetTop,pixels:Math.abs(head.y-foot.y)*innerHeight/2,follow:{center:{...w.center},velocity:{...w.velocity}},matrix:[...w.camera.projectionMatrix.elements],move:rect('move'),actions:rect('action-cluster'),pistol:{...g.pistol},supplies:structuredClone(g.supplies),saved:JSON.parse(localStorage.getItem('armagedom:area1-run:v1')),enemies:g.enemies.map(e=>({id:e.id,key:e.placementKey,rig:e.rig,hp:e.hp,pos:{...e.pos},radius:e.radius,swing:e.swing?{age:e.swing.ageTicks,move:e.swing.moveId}:null})),corpses:g.corpses.map(e=>({key:e.placementKey,finisher:e.finisher,clip:(q.actors.views.get(e.id)?.motion?.native??q.actors.views.get(e.id)?.motion)?.currentClip,renderedFinisher:q.actors.views.get(e.id)?.finisher?.stats()})),events:structuredClone(__qaEvents),waitDiagnostics:structuredClone(window.__qaWaits??[]),heads:w.scene.children.filter(o=>o.name==='Prepared detached Hollow head').length};});}
export async function aimAt(page,id){const point=await page.evaluate(id=>{const q=__qa,e=q.game.enemies.find(e=>e.id===id);if(!e)throw Error('target missing');const p=q.world.toRender(e.pos).project(q.world.camera);return{x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2};},id);await page.mouse.move(point.x,point.y);return point;}
export async function legal(page){await waitSimulation(page,()=>{const g=__qa.game,p=g.player;if(p.hp<=0)throw Error('player dead');return !g.finished&&!p.swing&&g.time>=p.ready&&g.time>=p.hurtUntil&&g.time>=p.dodgeUntil;},null,{seconds:6,wallMs:90000,label:'legal-or-event'});}
export async function waitEvent(page,expected,cursor){assert(Number.isInteger(cursor)&&cursor>=0,'fresh event cursor required');return waitSimulation(page,({expected,cursor})=>{if(__qa.game.player.hp<=0)throw Error('player dead');return __qaEvents.slice(cursor).find(e=>Object.entries(expected).every(([k,v])=>e[k]===v));},{expected,cursor},{seconds:6,wallMs:90000,label:'legal-or-event'});}
export async function controlledEntry(page,entry){if(entry.entryPoint)assert(['x','y'].every(k=>Number.isFinite(entry.entryPoint[k])&&entry.entryPoint[k]>=0&&entry.entryPoint[k]<=1),'entryPoint requires normalized artwork x/y');const result=await page.evaluate(async entry=>{const accepted=await __qa.crossArea(entry),q=__qa;return{accepted,pos:{...q.game.player.pos},expected:q.world.geometry.ground(entry.entryPoint??q.world.manifest.entries[entry.areaId])};},entry);assert.equal(result.accepted,true,'travel callback rejected entry');assert(Math.hypot(result.pos.x-result.expected.x,result.pos.z-result.expected.z)<1e-8,'travel destination position mismatch');await page.waitForFunction(area=>__qa.world.areaId===area,entry.areaId);return{controlledEntry:entry,walkedRoute:false,verifiedDestination:result,state:await readState(page)};}
export function verifyCamera(before,portrait,after,reference,{fullMatrix=false}={}){
 assert.equal(before.area,reference.area);assert.deepEqual(before.pos,reference.pos);assert.deepEqual(portrait.pos,before.pos);assert.equal(portrait.area,before.area);assert.equal(after.area,before.area);assert.deepEqual(after.pos,before.pos,'camera equality requires identical position');for(const k of ['width','height']){assert.equal(before[k],reference.landscape[k]);assert.equal(portrait[k],reference.portrait[k]);assert.equal(after[k],before[k]);}
 for(const [state,baseline,factor]of [[before,reference.landscape,reference.landscapeFactor],[portrait,reference.portrait,reference.portraitFactor],[after,reference.landscape,reference.landscapeFactor]]){assert(Number.isFinite(baseline.pixels)&&baseline.pixels>0);assert(Number.isFinite(factor)&&factor>0);assert(Math.abs(state.pixels/baseline.pixels-factor)<1e-8,'wrong orientation zoom factor');}
 if(fullMatrix){assert.deepEqual(after.follow,before.follow,'full matrix requires identical follow state');assert.deepEqual(after.matrix,before.matrix);}
 for(const key of ['move','actions'])assert.deepEqual(after[key],before[key]);for(const state of [before,portrait,after]){assert.equal(state.scale,1);for(const key of ['move','actions']){const r=state[key];assert(r.x>=0&&r.y>=0&&r.right<=state.width+1&&r.bottom<=state.height+1);}}
}
export async function camera(page,{comparator,comparatorSha256,fullMatrix=false}={}){
 assert(comparator&&/^[a-f0-9]{64}$/.test(comparatorSha256),'pinned camera comparator required');const bytes=fs.readFileSync(comparator);assert.equal(sha(bytes),comparatorSha256,'camera comparator changed');const reference=JSON.parse(bytes);assert(/^[a-f0-9]{40}$/.test(reference.source));const landscape={width:reference.landscape.width,height:reference.landscape.height},portrait={width:reference.portrait.width,height:reference.portrait.height};
 await page.setViewportSize(landscape);await page.waitForFunction(size=>__qa.world.width===size.width&&__qa.world.height===size.height,landscape);const before=await readState(page);await page.setViewportSize(portrait);await page.waitForFunction(size=>__qa.world.width===size.width&&__qa.world.height===size.height,portrait);const upright=await readState(page);await page.setViewportSize(landscape);await page.waitForFunction(size=>__qa.world.width===size.width&&__qa.world.height===size.height,landscape);const after=await readState(page);verifyCamera(before,upright,after,reference,{fullMatrix});return{before,portrait:upright,after,comparatorSha256,reference,scope:'orientation scale/geometry; full matrix only with identical follow state; before any action; no physical-device gesture proof'};
}
export async function hudMultitouch(page){
 const cdp=await page.context().newCDPSession(page),send=(type,touchPoints)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints}),center=async id=>{const r=await page.locator('#'+id).boundingBox();return{x:r.x+r.width/2,y:r.y+r.height/2}},origin=await center('move'),slash=await center('slash'),guard=await center('guard'),move={id:41,...origin},shift={...move,x:move.x+30,y:move.y-20},before=await readState(page);try{await send('touchStart',[move]);await send('touchMove',[shift]);await send('touchStart',[shift,{id:42,...slash}]);await waitSimulation(page,()=>!!__qa.game.player.swing,null,{seconds:3,label:'touch-swing'});const slashState=await readState(page);assert(Math.hypot(slashState.pos.x-before.pos.x,slashState.pos.z-before.pos.z)>.01);await send('touchEnd',[shift]);await send('touchEnd',[]);await legal(page);await send('touchStart',[move]);await send('touchMove',[shift]);await send('touchStart',[shift,{id:43,...guard}]);await waitSimulation(page,()=>__qa.game.player.guarding,null,{seconds:3,label:'guard'});const guardState=await readState(page);await send('touchCancel',[]);await waitSimulation(page,()=>!__qa.game.player.guarding,null,{seconds:3,label:'guard-cancel'});return{before,slashState,guardState,cancelled:await readState(page),scope:'trusted Chromium native touch; not physical Safari'};}finally{await send('touchCancel',[]).catch(()=>{});}
}
export async function incomingBite(page,{targetKey,damage,move}){
 const before=await readState(page),target=before.enemies.find(e=>e.key===targetKey);assert(target);assert.equal(before.weapon,'knife','setup must use ordinary holster before this stage');await aimAt(page,target.id);await waitEvent(page,{type:'hit',actor:0,attacker:target.id,amount:damage,move},before.events.length);return{before,after:await readState(page)};
}
export async function lowStrike(page,{targetKey,move,damage=10}){
 const before=await readState(page),target=before.enemies.find(e=>e.key===targetKey);assert(target);assert.equal(before.weapon,'knife');const point=await aimAt(page,target.id);await page.keyboard.down('f');let decision;try{decision=await waitSimulation(page,id=>{const g=__qa.game,p=g.player,e=g.enemies.find(e=>e.id===id),s=e?.swing;if(p.hp<=0)throw Error('player dead');const first=s?.def.windupTicks+s?.def.activeTicks;if(p.guarding&&!p.swing&&g.time>=p.ready&&g.time>=p.hurtUntil&&p.stamina>=18&&s?.ageTicks>=first&&s.ageTicks<=first+4)return{tick:g.tick,age:s.ageTicks,first};return false;},target.id,{seconds:6,wallMs:90000,label:'counter-ready'});await page.mouse.click(point.x,point.y);}finally{await page.keyboard.up('f');}await waitEvent(page,{type:'hit',actor:target.id,move,amount:damage},before.events.length);const after=await readState(page),accepted=after.events.slice(before.events.length).find(e=>e.type==='attack'&&e.actor===0&&e.move===move),prior=after.events.filter(e=>e.type==='enemy-attack'&&e.actor===target.id&&e.tick<=accepted.tick).at(-1);assert.equal(after.enemies.find(e=>e.id===target.id).hp,target.hp-damage);return{before,after,decision:await decision.jsonValue(),acceptedTick:accepted.tick,relativeToEnemyStart:accepted.tick-prior.tick};
}
export async function pistolKill(page,{targetKey,damageSteps,expectedRecipe='ordinary',expectedClip}){
 const before=await readState(page),target=before.enemies.find(e=>e.key===targetKey);assert(target);assert.equal(before.weapon,'pistol','gun-first setup must already be equipped through ordinary input');const counts=before.events.filter(e=>e.type==='hit'&&e.actor===target.id&&e.weapon==='pistol').length,shots=[];for(let n=0;n<damageSteps.length;n++){await aimAt(page,target.id);await waitSimulation(page,id=>{const m=__qa.world.scene.getObjectByName('Pistol aim marker');return m.userData.targetId===id&&m.userData.ready;},target.id,{seconds:6,wallMs:90000,label:'pistol-ready-hit-death'});await page.mouse.down();try{await waitSimulation(page,({id,count})=>__qaEvents.filter(e=>e.type==='hit'&&e.actor===id&&e.weapon==='pistol').length>count,{id:target.id,count:counts+n},{seconds:6,wallMs:90000,label:'pistol-ready-hit-death'});}finally{await page.mouse.up();}shots.push(await readState(page));}if(expectedClip)await waitSimulation(page,({key,clip})=>{const q=__qa,e=q.game.corpses.find(e=>e.placementKey===key),v=e&&q.actors.views.get(e.id);return (v?.motion?.native??v?.motion)?.currentClip===clip;},{key:targetKey,clip:expectedClip},{seconds:6,wallMs:90000,label:'pistol-ready-hit-death'});const after=await readState(page),hits=after.events.filter(e=>e.type==='hit'&&e.actor===target.id&&e.weapon==='pistol').slice(counts),corpse=after.corpses.find(e=>e.key===targetKey);assert.deepEqual(hits.map(e=>e.amount),damageSteps);assert(corpse);assert.equal(corpse.finisher.recipeId,expectedRecipe);assert.equal(after.pistol.magazine,before.pistol.magazine-damageSteps.length);assert.equal(after.saved.pistol.magazine,after.pistol.magazine);assert.equal(after.saved.hp,after.hp);return{before,shots,after,heldUntilActualShotAcknowledgement:true};
}
export async function pauseAndRetry(page,{area='westminster',enemyCount=6}={}){
 const press=await page.evaluate(()=>navigator.maxTouchPoints>0)?id=>page.tap(id):id=>page.click(id);
 await press('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);const paused=await readState(page);await page.waitForTimeout(200);const pausedLater=await readState(page);assert.equal(pausedLater.time,paused.time);await press('#close-menu');await page.waitForFunction(time=>!document.getElementById('menu').open&&__qa.game.time>time,paused.time);const resumed=await readState(page);await page.keyboard.press('r');await page.waitForFunction(({area,enemyCount})=>__qa.world.areaId===area&&__qa.game.enemies.length===enemyCount&&__qa.game.corpses.length===0&&__qa.game.player.hp===150,{area,enemyCount});const retry=await readState(page);assert.equal(retry.pistol.collected,false);assert.deepEqual(retry.supplies.issued,[]);assert.equal(retry.heads,0);return{paused,pausedLater,resumed,retry};
}
export async function pistolBodyCue(page,{targetKey,offsetDegrees=20}){
 const before=await readState(page),target=before.enemies.find(e=>e.key===targetKey);assert(target);assert.equal(before.weapon,'pistol');
 const point=await page.evaluate(({key,angle})=>{const q=__qa,p=q.game.player.pos,e=q.game.enemies.find(e=>e.placementKey===key),dx=e.pos.x-p.x,dz=e.pos.z-p.z,c=Math.cos(angle),s=Math.sin(angle),v=q.world.toRender({x:p.x+dx*c-dz*s,z:p.z+dx*s+dz*c}).project(q.world.camera);return{x:(v.x+1)*innerWidth/2,y:(1-v.y)*innerHeight/2};},{key:targetKey,angle:offsetDegrees*Math.PI/180});await page.mouse.move(point.x,point.y);
 const handle=await waitSimulation(page,key=>{const q=__qa,g=q.game,e=g.enemies.find(e=>e.placementKey===key),p=g.player,m=q.world.scene.getObjectByName('Pistol aim marker'),aim=g.pistolUserFacing??p.facing,dx=e.pos.x-p.pos.x,dz=e.pos.z-p.pos.z,angle=Math.abs(Math.atan2(aim.x*dz-aim.z*dx,aim.x*dx+aim.z*dz))*180/Math.PI;return !g.mobileAiming&&angle>12&&m.userData.targetId===e.id&&m.userData.ready?{time:g.time,tick:g.tick,angle,aim:{...aim},player:{...p.pos},target:{...e.pos},targetId:e.id,markerTarget:m.userData.targetId,mobileAiming:g.mobileAiming}:false;},targetKey,{seconds:3,label:'desktop-body-edge-cue'});const observed=await handle.jsonValue();
 const fresh=await page.evaluate(key=>{const q=__qa,g=q.game,e=g.enemies.find(e=>e.placementKey===key),p=g.player,m=q.world.scene.getObjectByName('Pistol aim marker'),a=g.pistolUserFacing??p.facing,dx=e.pos.x-p.pos.x,dz=e.pos.z-p.pos.z;return{cursor:__qaEvents.length,tick:g.tick,time:g.time,angle:Math.abs(Math.atan2(a.x*dz-a.z*dx,a.x*dx+a.z*dz))*180/Math.PI,targetId:e.id,markerTarget:m.userData.targetId,ready:m.userData.ready,mobileAiming:g.mobileAiming};},targetKey);assert(fresh.angle>12&&fresh.markerTarget===target.id&&fresh.ready&&!fresh.mobileAiming,'fresh desktop bodyedge cue precondition');
 await page.mouse.down();try{await waitEvent(page,{type:'hit',actor:target.id,weapon:'pistol'},fresh.cursor);}finally{await page.mouse.up();}const after=await readState(page),hit=after.events.slice(fresh.cursor).find(e=>e.type==='hit'&&e.actor===target.id&&e.weapon==='pistol');assert(hit);assert.equal(after.pistol.magazine,before.pistol.magazine-1);return{before,observed,fresh,hit,after,scope:'desktop bodyedge outside12degree centrecone; ordinary Fire agrees with rendered cue; no mobile acquisition/contact claim'};
}
export async function finisherPrepared(page,{targetKey}){
 const s=await page.evaluate(key=>{const q=__qa,e=q.game.enemies.find(e=>e.placementKey===key),v=e&&q.actors.views.get(e.id);if(!v?.finisher)throw Error('Existing compiled finisher handle missing');return{key:e.placementKey,rig:e.rig,hp:e.hp,rootScale:v.root.scale.toArray(),stats:v.finisher.stats(),support:v.finisher.support,scope:'Live compiled preparation boundary only; detached motion/native kills reused from matched component receipts'};},targetKey);
 assert(s.stats.prepared);assert.equal(s.stats.preparationError,null);assert.equal(s.stats.detached,false);assert(s.support.some(r=>r.id==='decapitation'));return s;
}
export async function animalAppearanceRows(page,{assignments}){
 await page.waitForFunction(()=>__qa.game.enemies.every(e=>__qa.actors.views.has(e.id)),null,{timeout:60000});
 const s=await page.evaluate(()=>{const q=__qa;return{area:q.world.areaId,actors:q.game.enemies.filter(e=>['original-rat','original-dog','original-roach'].includes(e.rig)).map(e=>{const v=q.actors.views.get(e.id),meshes=[],bones=[];v.model.traverse(o=>{if(o.isBone)bones.push(o.name);if(o.isSkinnedMesh)meshes.push({geometry:o.geometry.uuid,positions:o.geometry.attributes.position.count,colorAttribute:!!o.geometry.attributes.color,material:o.material.name,vertexColors:o.material.vertexColors,tint:o.material.color.toArray()});});return{key:e.placementKey,rig:e.rig,appearance:v.animalAppearanceId??null,factor:v.description.scale,root:v.root.scale.toArray(),hp:e.hp,radius:e.radius,bones:bones.length,meshes};})};});
 for(const e of s.actors){assert.equal(e.appearance,assignments[e.key]??null);assert.equal(e.factor,e.rig==='original-dog'?2:3);assert(Math.abs(e.root[0]-1.6729625*e.factor)<1e-9);assert.equal(e.bones,e.rig==='original-dog'?25:e.rig==='original-rat'?24:27);if(e.appearance?.startsWith('dog-'))assert(e.meshes.some(m=>m.vertexColors&&m.colorAttribute));}
 return s;
}

export async function droneEncounter(page,{targetKey='westminster-drone-1'}={}){
 const before=await readState(page),target=before.enemies.find(e=>e.key===targetKey);assert(target);assert.equal(before.enemies.length,7);
 const alert=await waitSimulation(page,key=>{const q=__qa,g=q.game,e=g.enemies.find(e=>e.placementKey===key),v=e&&q.actors.views.get(e.id);return e?.droneState.warning&&v?.drone.stats().state==='alert'?{time:g.time,tick:g.tick,warning:structuredClone(e.droneState.warning),root:v.root.scale.toArray(),frame:v.model.getObjectByName('ARM_Drone_Rigid_Frame').geometry.index.count}:false;},targetKey,{seconds:4,label:'drone-real-warning'});
 const warning=await alert.jsonValue();assert.deepEqual(warning.root,[1,1,1]);assert(warning.frame>0);
 await waitEvent(page,{type:'hit',actor:0,amount:6},before.events.length);const incoming=await readState(page);assert.equal(incoming.hp,before.hp-6);assert(incoming.events.slice(before.events.length).some(e=>e.type==='enemy-attack'&&e.actor===target.id&&e.move==='drone_bolt'));
 await legal(page);await aimAt(page,target.id);const cursor=(await readState(page)).events.length;await page.mouse.down();try{await waitEvent(page,{type:'hit',actor:target.id,weapon:'pistol'},cursor);}finally{await page.mouse.up();}
 const killed=await readState(page);assert.equal(killed.enemies.some(e=>e.key===targetKey),false);assert(killed.saved.droneDeaths.includes(targetKey));assert.equal(killed.pistol.magazine,before.pistol.magazine-1);assert.equal(killed.corpses.find(e=>e.key===targetKey).finisher,undefined);
 const corpse=await page.evaluate(key=>{const q=__qa,e=q.game.corpses.find(e=>e.placementKey===key),v=q.actors.views.get(e.id);return{clip:e.response.clip,state:v.drone.stats().state,scale:v.root.scale.toArray()};},targetKey);assert.equal(corpse.clip,'drone_death');
 for(const [areaId,count]of [['east',10],['south',10],['westminster',6]]){await controlledEntry(page,{areaId});const s=await readState(page);assert.equal(s.enemies.length,count);assert.equal(s.enemies.filter(e=>e.rig==='low-hover-drone').length,areaId==='westminster'?0:1);}
 await page.reload();await page.click('#enter');await page.waitForFunction(()=>window.__qa?.game&&document.getElementById('entry').hidden,null,{timeout:90000});const refreshed=await readState(page);assert.equal(refreshed.enemies.length,6);assert(refreshed.saved.droneDeaths.includes(targetKey));
 const reset=await pauseAndRetry(page,{enemyCount:7});assert.deepEqual(reset.retry.saved.droneDeaths,[]);
 return{before,warning,incoming,killed,corpse,refreshed,reset,scope:'One controlled West native warning/bolt/player hit/pistol kill, all-area counts/return, cold refresh and Retry. Actual Low rigid contact reused from component and source integration; no walked route or physical-phone claim.'};
}

export async function animalCycleRows(page,{cycle,assignments,offsets={}}){
 const rows=await page.evaluate(()=>{const q=__qa,g=q.game;return{cycle:g.animalCycle,savedCycle:JSON.parse(localStorage.getItem('armagedom:area1-run:v1')).animalCycle,area:q.world.areaId,hp:g.player.hp,count:g.enemies.length,actors:g.enemies.filter(e=>e.animalRecipe).map(e=>{const v=q.actors.views.get(e.id),meshes=[],bones=new Set();v.model.traverse(m=>{if(m.skeleton)for(const b of m.skeleton.bones)bones.add(b);if(m.isSkinnedMesh){const p=m.geometry.attributes.position;let min=Infinity,max=-Infinity;for(let i=0;i<p.count;i++){min=Math.min(min,p.getX(i));max=Math.max(max,p.getX(i));}meshes.push({name:m.name,positions:p.count,width:max-min,vertexColors:m.material.vertexColors,tint:m.material.color.toArray()});}});return{key:e.placementKey,rig:e.rig,recipe:e.animalRecipe,appearance:v.animalAppearanceId,root:v.root.scale.toArray(),bones:bones.size,bodyShape:v.bodyShape?.recipe??null,home:{...e.home},patrol:e.patrol.map(p=>({...p})),meshes};})};});
 assert.equal(rows.cycle,cycle);assert.equal(rows.savedCycle,cycle);assert.equal(rows.count,rows.area==='westminster'?7:10);assert.equal(rows.hp,150);
 for(const e of rows.actors){assert.equal(e.recipe,assignments[e.key]);assert.equal(e.appearance,e.recipe);const dog=e.rig==='original-dog';assert(Math.abs(e.root[0]-1.6729625*(dog?2:3))<1e-9);assert.equal(e.bones,dog?25:e.rig==='original-rat'?24:27);if(['dog-gaunt-hound','dog-stocky-yard'].includes(e.recipe))assert.equal(e.bodyShape.id,e.recipe);if(offsets[e.key])for(const axis of ['x','z'])assert(Math.abs(e.home[axis]-offsets[e.key][axis])<1e-8);}
 return rows;
}

export async function portraitDodge(page,{baselineCSSPath='qa-baseline.css',screenshotPath='/work/results/browser/portrait.png'}={}){
 const rects=()=>page.evaluate(()=>Object.fromEntries(['move','action-cluster','slash','stab','heavy','dodge','guard','pistol-interact'].map(id=>{const e=document.getElementById(id),r=e.getBoundingClientRect(),s=getComputedStyle(e);return[id,{x:r.x,y:r.y,width:r.width,height:r.height,font:s.fontSize,hidden:e.hidden}];})));
 const baselineCSS=fs.readFileSync(baselineCSSPath,'utf8'),landscape=[];
 for(const size of [{width:852,height:393},{width:1180,height:744}]){await page.setViewportSize(size);await page.waitForFunction(size=>__qa.world.width===size.width&&__qa.world.height===size.height,size);const candidate=await rects(),tag=await page.addStyleTag({content:baselineCSS}),baseline=await rects();assert.deepEqual(candidate,baseline,'landscape controls must be identical');await tag.evaluate(e=>e.remove());landscape.push({size,candidate,baseline});}
 const portrait=[];
 for(const size of [{width:320,height:568},{width:280,height:568},{width:393,height:852}]){await page.setViewportSize(size);await page.waitForFunction(size=>__qa.world.width===size.width&&__qa.world.height===size.height,size);const candidate=await rects(),tag=await page.addStyleTag({content:baselineCSS}),baseline=await rects();await tag.evaluate(e=>e.remove());assert.equal(candidate.dodge.width,candidate.slash.width);assert.equal(candidate.dodge.height,candidate.slash.height);assert.equal(candidate.dodge.font,candidate.slash.font);for(const axis of ['x','y'])assert.equal(candidate.dodge[axis]+candidate.dodge[axis==='x'?'width':'height']/2,baseline.dodge[axis]+baseline.dodge[axis==='x'?'width':'height']/2,'keep existing portrait centre');for(const[id,r]of Object.entries(candidate)){assert(r.x>=0&&r.y>=0&&r.x+r.width<=size.width&&r.y+r.height<=size.height,'visible '+id);if(['slash','stab','heavy','guard'].includes(id)){const d=candidate.dodge,gap=Math.hypot(r.x+r.width/2-d.x-d.width/2,r.y+r.height/2-d.y-d.height/2)-(r.width+d.width)/2;assert(gap>0,'combat circles overlap '+id);}}portrait.push({size,candidate,baseline});}
 const safe=await page.addStyleTag({content:':root{--safe-l:20px;--safe-r:20px;--safe-b:34px}'}),safeRects=await rects();assert(safeRects.dodge.y+safeRects.dodge.height<852-34);assert(safeRects.guard.y+safeRects.guard.height<852-34);await safe.evaluate(e=>e.remove());
 await page.screenshot({path:screenshotPath});const before=await readState(page);await page.tap('#dodge');await waitEvent(page,{type:'dodge',actor:0},before.events.length);const after=await readState(page);assert(after.stamina<=before.stamina-30+1e-8);return{landscape,portrait,safeRects,before,after,baselineCSSSHA256:sha(baselineCSS),screenshotPath,scope:'Only portrait Dodge60/font10, original centre preserved, min280/320/393 and safe-area margins, identical landscape rects, one ordinary touch Roll/cost30; not physical Safari'};
}

export async function droneMeleeInput(page,{action='slash',expectedDamage=10,gap=.95,counterAfterBolt=false}={}){
 await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);await ordinaryInput(page,()=>page.click('#retry'),{reset:true,label:'fresh-melee-retry'});await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);
 const entry=await page.evaluate(gap=>{const q=__qa,e=q.game.enemies.find(e=>e.rig==='low-hover-drone'),p={x:e.pos.x-gap,z:e.pos.z};if(!q.world.geometry.clear(p,.4)||!q.world.lineClear(p,e.pos))throw Error('Requested ordinary melee setup not clear');const at=q.world.geometry.point(p);return{areaId:'westminster',entryPoint:{x:at.x,y:at.y}};},gap);await controlledEntry(page,entry);await ordinaryInput(page,()=>page.click('#close-menu'),{label:'resume-melee'});
 if(counterAfterBolt){const at=await readState(page);await waitEvent(page,{type:'hit',actor:0,amount:6},at.events.length);await legal(page);}
 const before=await readState(page),target=before.enemies.find(e=>e.rig==='low-hover-drone'),cursor=await page.evaluate(()=>__qaMelee.length);await page.tap('#'+action);const accepted=await waitEvent(page,{type:'attack',actor:0},before.events.length);const decision=await accepted.jsonValue();let hit=null;
 if(expectedDamage){const receipt=await waitSimulation(page,({id,cursor})=>{const e=__qaEvents.slice(cursor).find(e=>e.type==='hit'&&e.actor===id);if(!e)return false;const g=__qa.game,m=document.getElementById('hit-marker');return{event:e,hp:g.enemies.find(e=>e.id===id)?.hp,marker:{hidden:m.hidden,text:m.textContent},swing:g.player.swing?{action:g.player.swing.action,lowTargetId:g.player.swing.lowTargetId,timing:g.player.swing.timing}:null};},{id:target.id,cursor:before.events.length},{seconds:2,label:'real-melee-damage'});hit=await receipt.jsonValue();assert.equal(hit.event.amount,expectedDamage);assert.equal(hit.hp,20-expectedDamage);}
 await legal(page);const after=await readState(page),trace=await page.evaluate(cursor=>__qaMelee.slice(cursor),cursor);assert.equal(after.enemies.find(e=>e.id===target.id).hp,20-expectedDamage);if(expectedDamage)assert(trace.some(t=>t.result===true&&t.lowTargetId===target.id&&t.frame?.index===2664&&t.blade));else assert(!trace.some(t=>t.result===true));return{before,decision,hit,after,trace,requestedGap:gap,expectedDamage,scope:expectedDamage?'Actual ordinary input→locked native blade→current displayed root/blade/rigid frame→HP':'Recorded ordinary action with no physical damage; far control or known non-Low rejection, not a successful melee baseline'};
}
export async function dronePistolControl(page){
 await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);await ordinaryInput(page,()=>page.click('#retry'),{reset:true,label:'fresh-pistol-retry'});await equipPistol(page);await controlledEntry(page,{areaId:'westminster',entryPoint:{x:.65,y:.713}});const before=await readState(page),e=before.enemies.find(e=>e.rig==='low-hover-drone');await aimAt(page,e.id);await page.mouse.down();try{await waitEvent(page,{type:'hit',actor:e.id,weapon:'pistol'},before.events.length);}finally{await page.mouse.up();}const after=await readState(page);assert(!after.enemies.some(x=>x.id===e.id));assert(after.saved.droneDeaths.includes(e.key));assert.equal(after.pistol.magazine,before.pistol.magazine-1);return{before,after};
}
export async function inputReadinessScenario(page){
 await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);
 const entry=await page.evaluate(()=>{const q=__qa,p=q.game.pistol.pickupPos;if(!q.world.geometry.clear(p,.4))throw Error('Registered pickup entry blocked');const at=q.world.geometry.point(p);return{areaId:'westminster',entryPoint:{x:at.x,y:at.y}};});await controlledEntry(page,entry);
 const fresh=await ordinaryInput(page,()=>page.click('#retry'),{reset:true,phase:'pickup',label:'hardened-fresh-pickup'});assert.equal(fresh.snapshot.collected,false);const equipped=await equipPistol(page);assert(equipped.snapshot.collected&&equipped.snapshot.equipped);await page.click('#menu-button');await page.waitForFunction(()=>document.getElementById('menu').open);const resumed=await ordinaryInput(page,()=>page.click('#close-menu'),{label:'hardened-menu-resume'});return{entry,fresh,equipped,resumed,scope:'Actual current compiled client: reset generation and clock advancement, registered pickup prerequisite, ordinary G acknowledgement and menu resume; no game/HP/weapon writes, combat or release recheck'};
}
