import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import{createHash}from'node:crypto';import{stage,reuseMatches,verifyPackage,installObserver,codeDigest,camera,waitEvent,verifyCamera,controlledEntry}from'./scenarios.mjs';
const hash='1'.repeat(64),identity={source:'2'.repeat(40),fingerprint:hash,packageSha256:hash};
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'armagedom-qa-stage-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return{identity,stageHarnessHash:hash,moduleHash:hash,runnerHash:hash,observerHash:hash,dependencies:{asset:hash},inputHash:hash,environment:{browser:'fixture'},preconditions:{area:'south',weapon:'pistol',hp:30},receiptDir:dir,rawOutputPath:path.join(dir,'raw.json')};}
test('completed stage is bound to inputs and tamper rejects reuse',async t=>{const c=fixture(t),r=await stage('pistol.kill',c,async()=>({hits:[25,5]}));assert.equal(reuseMatches(r,c),true);for(const k of ['identity','stageHarnessHash','moduleHash','runnerHash','observerHash','dependencies','inputHash','environment','preconditions']){const different=structuredClone(c);different[k]=typeof c[k]==='string'?'3'.repeat(64):{...c[k],different:true};assert.equal(reuseMatches(r,different),false,k);}fs.writeFileSync(c.rawOutputPath,'tampered');assert.equal(reuseMatches(r,c),false);});
test('failed stage receipt survives and never becomes reusable',async t=>{const c=fixture(t);await assert.rejects(stage('pistol.kill',c,async()=>{throw Error('no shot observed');}),/no shot observed/);const r=JSON.parse(fs.readFileSync(path.join(c.receiptDir,'pistol.kill.json')));assert.equal(r.status,'failed');assert.equal(reuseMatches(r,c),false);assert.match(r.error,/no shot observed/);});
test('unsafe receipt path and missing observations fail closed',async t=>{const c=fixture(t);await assert.rejects(stage('../escape',c,async()=>({})),/unsafe/);await assert.rejects(stage('camera',c,async()=>undefined),/observed data/);assert.equal(JSON.parse(fs.readFileSync(path.join(c.receiptDir,'camera.json'))).status,'failed');assert.equal(codeDigest(camera).length,64);});
test('known exact060 and061 compiled bundles accept only hash-matched readonly observer',async()=>{for(const version of ['ipad-060','portrait-061']){const root=new URL('../../qa/'+version+'/recovered/export/',import.meta.url),verified=verifyPackage(root.pathname),base='http://qa/',bundle=verified.release.files.find(f=>/^assets\/index-.*\.js$/.test(f.path)),bytes=fs.readFileSync(new URL(bundle.path,root)),probes=[];let callback,body;await installObserver({route:async(_pattern,handler)=>{callback=handler;}},verified.release,base,probes);await callback({request:()=>({url:()=>new URL(bundle.path,base).href}),fetch:async()=>({body:async()=>bytes}),fulfill:async out=>{body=out.body;}});assert.match(body,/get game\(\)/);assert.match(body,/get crossArea\(\)/);assert.equal(probes[0].payloadSHA256,bundle.sha256);assert.equal(probes[0].observerSHA256,createHash('sha256').update(body).digest('hex'));await assert.rejects(callback({request:()=>({url:()=>new URL(bundle.path,base).href}),fetch:async()=>({body:async()=>Buffer.from('bad')}),fulfill:async()=>{}}));}});

test('failed attempt retry cannot overwrite raw or receipt before execution',async t=>{const c=fixture(t);await assert.rejects(stage('attempt',c,async()=>{throw Error('original failure');}));const raw=fs.readFileSync(c.rawOutputPath),receipt=fs.readFileSync(path.join(c.receiptDir,'attempt.json'));let executed=false;await assert.rejects(stage('attempt',c,async()=>{executed=true;return{new:true};}),/already exist/);assert.equal(executed,false);assert.deepEqual(fs.readFileSync(c.rawOutputPath),raw);assert.deepEqual(fs.readFileSync(path.join(c.receiptDir,'attempt.json')),receipt);});
test('fresh event cursor rejects an older matching hit',async t=>{const oldQa=globalThis.__qa,oldEvents=globalThis.__qaEvents;t.after(()=>{globalThis.__qa=oldQa;globalThis.__qaEvents=oldEvents;});globalThis.__qa={game:{player:{hp:150}}};globalThis.__qaEvents=[{type:'hit',actor:14,amount:10,tick:100}];const page={waitForFunction:async(fn,args)=>fn(args)};assert.equal(await waitEvent(page,{type:'hit',actor:14,amount:10},1),undefined);globalThis.__qaEvents.push({type:'hit',actor:14,amount:10,tick:200});assert.equal((await waitEvent(page,{type:'hit',actor:14,amount:10},1)).tick,200);await assert.rejects(waitEvent(page,{type:'hit'}),/cursor required/);});
test('061 moved-player and wrong zoom fail while pinned same-position scale checks pass',()=>{const raw=JSON.parse(fs.readFileSync(new URL('../../qa/portrait-061/recovered/results/orientation.json',import.meta.url))),before={...raw.landscape,area:'westminster',follow:{center:.5,velocity:0}},upright={...raw.portrait,area:'westminster'},reference={source:'9fe56cd5b9ce4dbfaf50155e2e596402e5ce2e73',area:'westminster',pos:before.pos,landscape:{width:1180,height:744,pixels:85.77371128981689},portrait:{width:820,height:1104,pixels:87.02205487662607},landscapeFactor:1,portraitFactor:1.05};verifyCamera(before,upright,before,reference);assert.throws(()=>verifyCamera(before,upright,{...raw.landscapeReturn,area:'westminster'},reference),/position|Expected/);assert.throws(()=>verifyCamera(before,{...upright,pixels:reference.portrait.pixels*1.1},before,reference),/zoom factor/);assert.throws(()=>verifyCamera(before,upright,{...before,follow:{center:.6,velocity:1}},reference,{fullMatrix:true}),/follow state/);});

test('legacy receipts missing new identity fields cannot match a legacy-shaped context',async t=>{const c=fixture(t),r=await stage('legacy',c,async()=>({actual:'data'}));const legacy=structuredClone(r),oldContext=structuredClone(c);for(const k of ['moduleHash','runnerHash','observerHash','dependencies']){delete legacy[k];delete oldContext[k];}assert.equal(reuseMatches(legacy,oldContext),false);});

test('controlled travel rejects world x/z before calling the browser',async()=>{let called=false;await assert.rejects(controlledEntry({evaluate:()=>{called=true;}},{areaId:'westminster',entryPoint:{x:17.79336,z:6.86608}}),/artwork x\/y/);assert.equal(called,false);});
test('controlled same-area travel requires accepted callback and actual destination',async()=>{const entry={areaId:'westminster',entryPoint:{x:.8251892425072958,y:.4835856015160479}};for(const [accepted,pos,message]of [[false,{x:0,z:-6},/rejected/],[true,{x:0,z:-6},/destination/]]){const page={evaluate:async()=>({accepted,pos,expected:{x:17.79336,z:6.86608}}),waitForFunction:()=>assert.fail('must reject before same-area wait')};await assert.rejects(controlledEntry(page,entry),message);}});
