// Separate CPU derivative. Native rig/binds and all combat clips are preserved.
import fs from 'node:fs';import path from 'node:path';import * as T from '../../Web/node_modules/three/build/three.module.js';
import {decode,sha} from '../donor/probe.mjs';
const source='Web/public/assets/donor/warrior.glb',original=fs.readFileSync(source),{doc,bin}=decode(original);
if(sha(original)!=='d8aeb2ae0eb5c4b8b9dfa0813d04a41f17623d3d85b5702cd9494967b7fe9769')throw Error('Pinned normalized donor changed');
const chunks=[bin];let size=bin.length;
function append(data,type,component,count,min,max){const buffer=Buffer.from(data.buffer,data.byteOffset,data.byteLength),padding=(4-size%4)%4;if(padding){chunks.push(Buffer.alloc(padding));size+=padding;}const view=doc.bufferViews.length;doc.bufferViews.push({buffer:0,byteOffset:size,byteLength:buffer.length});chunks.push(buffer);size+=buffer.length;const id=doc.accessors.length;doc.accessors.push({bufferView:view,componentType:component,count,type,...(min?{min,max}:{})});return id;}
function values(id){const a=doc.accessors[id],v=doc.bufferViews[a.bufferView],count={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16}[a.type],width={5121:1,5123:2,5125:4,5126:4}[a.componentType],start=(v.byteOffset??0)+(a.byteOffset??0);return Array.from({length:a.count},(_,i)=>Array.from({length:count},(_,j)=>{const p=start+i*(v.byteStride??count*width)+j*width;return a.componentType===5126?bin.readFloatLE(p):a.componentType===5125?bin.readUInt32LE(p):a.componentType===5123?bin.readUInt16LE(p):bin.readUInt8(p);}));}
const matte=(name,color)=>{const id=doc.materials.length;doc.materials.push({name,pbrMetallicRoughness:{baseColorFactor:[...color,1],metallicFactor:0,roughnessFactor:.94},doubleSided:true});return id;};
const skinMat=matte('Ash-grey affected skin',[.48,.43,.36]),jacketMat=matte('Torn charcoal canvas jacket',[.14,.17,.16]),trouserMat=matte('Worn tobacco trousers',[.22,.20,.16]),bootMat=matte('Dirty black work boots',[.07,.065,.055]);
// Retain complete skin, fitted jacket torso, source face and work-boot soles.
const keep=new Set(['Skin','Gambeson','Leather.Boots','Photo','PhotoEyes','PhotoTeeth']);
for(const node of doc.nodes)if(node.mesh!==undefined&&!keep.has(node.name)){delete node.mesh;delete node.skin;}
const skinNode=doc.nodes.find(n=>n.name==='Skin'),primitive=doc.meshes[skinNode.mesh].primitives[0],p=values(primitive.attributes.POSITION),joints=values(primitive.attributes.JOINTS_0),weights=values(primitive.attributes.WEIGHTS_0),indices=values(primitive.indices).flat(),skin=doc.skins[skinNode.skin];
const names=skin.joints.map(id=>doc.nodes[id].name),groups=new Map([[skinMat,[]],[jacketMat,[]],[trouserMat,[]],[bootMat,[]]]);
for(let i=0;i<indices.length;i+=3){const ids=indices.slice(i,i+3),y=ids.reduce((s,id)=>s+p[id][1],0)/3;
 let sleeve=0,hand=0;for(const id of ids)for(let k=0;k<4;k++){const name=names[joints[id][k]]??'';if(/upperarm|lowerarm|clavicle/.test(name))sleeve+=weights[id][k]/3;if(/hand|index|middle|ring|pinky|thumb/.test(name))hand+=weights[id][k]/3;}
 const material=y<.14?bootMat:y<.87?trouserMat:sleeve>.45&&hand<.35?jacketMat:skinMat;groups.get(material).push(...ids);
}
const colors=new Float32Array(p.length*4);for(let i=0;i<p.length;i++){const [x,y,z]=p[i],dust=.7+.25*((Math.sin(x*51+y*27+z*35)*43758.5453)%1+1)/2;colors.set([dust,dust,dust,1],i*4);}const colorId=append(colors,'VEC4',5126,p.length);
doc.meshes[skinNode.mesh].primitives=[...groups].filter(([,ids])=>ids.length).map(([material,ids])=>({mode:4,attributes:{POSITION:primitive.attributes.POSITION,NORMAL:primitive.attributes.NORMAL,JOINTS_0:primitive.attributes.JOINTS_0,WEIGHTS_0:primitive.attributes.WEIGHTS_0,COLOR_0:colorId},indices:append(new Uint32Array(ids),'SCALAR',5125,ids.length,[Math.min(...ids)],[Math.max(...ids)]),material}));
skinNode.name='Hollow body and worn trousers';
const jacket=doc.nodes.find(n=>n.name==='Gambeson'),jp=doc.meshes[jacket.mesh].primitives[0],positions=values(jp.attributes.POSITION),ji=values(jp.indices).flat();
// Irregular open hem/cuffs; keep the original weighted torso and seams.
const kept=[];for(let i=0;i<ji.length;i+=3){const ids=ji.slice(i,i+3),y=ids.reduce((s,id)=>s+positions[id][1],0)/3,x=ids.reduce((s,id)=>s+positions[id][0],0)/3;if(y<.946&&Math.sin(x*87)>0.2)continue;kept.push(...ids);}jp.indices=append(new Uint32Array(kept),'SCALAR',5125,kept.length,[Math.min(...kept)],[Math.max(...kept)]);jp.material=jacketMat;delete jp.attributes.TEXCOORD_0;delete jp.attributes.TEXCOORD_1;jacket.name='Torn modern canvas jacket';
doc.meshes[doc.nodes.find(n=>n.name==='Leather.Boots').mesh].primitives.forEach(p=>p.material=bootMat);
for(const name of ['Photo','PhotoEyes','PhotoTeeth']){const node=doc.nodes.find(n=>n.name===name);for(const primitive of doc.meshes[node.mesh].primitives){const m=doc.materials[primitive.material];if(name==='Photo')m.pbrMetallicRoughness.baseColorFactor=[.83,.82,.73,1];}}
// New idle/gait only: spinal slump, head nod. Legs and combat clips stay native.
for(const [name,base] of [['HollowIdle','Armed'],['HollowWalk','ArmedWalk'],['HollowRun','Run']]){
 const clip=structuredClone(doc.animations.find(a=>a.name===base));clip.name=name;
 for(const channel of clip.channels){const bone=doc.nodes[channel.target.node].name;if(channel.target.path!=='rotation'||!['spine_01','spine_02','neck_01'].includes(bone))continue;const sampler=clip.samplers[channel.sampler],q=values(sampler.output),time=values(sampler.input).flat(),data=new Float32Array(q.length*4);for(let i=0;i<q.length;i++){const angle=bone==='neck_01'?.10+Math.sin(time[i]*3.5)*.025:bone==='spine_01'?.075:.055;const rotation=new T.Quaternion(...q[i]).multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),angle)).normalize();data.set(rotation.toArray(),i*4);}const bounds=[0,1,2,3].map(j=>q.map((_,i)=>data[i*4+j]));sampler.output=append(data,'VEC4',5126,q.length,bounds.map(v=>Math.min(...v)),bounds.map(v=>Math.max(...v)));}
 doc.animations.push(clip);
}
// Use the affected gait for Run as well; original native Run remains stored as SourceRun.
doc.animations.find(a=>a.name==='Run').name='SourceRun';doc.animations.find(a=>a.name==='HollowRun').name='Run';
function remap(items,used){const map=new Map(),result=[];for(const id of [...used].sort((a,b)=>a-b)){map.set(id,result.length);result.push(items[id]);}return {map,result};}
const mesh=remap(doc.meshes,new Set(doc.nodes.filter(n=>n.mesh!==undefined).map(n=>n.mesh)));doc.meshes=mesh.result;for(const n of doc.nodes)if(n.mesh!==undefined)n.mesh=mesh.map.get(n.mesh);
const mat=remap(doc.materials,new Set(doc.meshes.flatMap(m=>m.primitives.map(p=>p.material))));doc.materials=mat.result;for(const m of doc.meshes)for(const p of m.primitives)p.material=mat.map.get(p.material);
const textures=new Set();for(const m of doc.materials){for(const info of [m.pbrMetallicRoughness?.baseColorTexture,m.pbrMetallicRoughness?.metallicRoughnessTexture,m.normalTexture,m.occlusionTexture,m.emissiveTexture])if(info)textures.add(info.index);}
const tex=remap(doc.textures,textures);doc.textures=tex.result;for(const m of doc.materials)for(const info of [m.pbrMetallicRoughness?.baseColorTexture,m.pbrMetallicRoughness?.metallicRoughnessTexture,m.normalTexture,m.occlusionTexture,m.emissiveTexture])if(info)info.index=tex.map.get(info.index);
const image=remap(doc.images,new Set(doc.textures.map(t=>t.source)));doc.images=image.result;for(const t of doc.textures)t.source=image.map.get(t.source);
const used=new Set();for(const m of doc.meshes)for(const p of m.primitives){Object.values(p.attributes).forEach(id=>used.add(id));if(p.indices!==undefined)used.add(p.indices);}for(const s of doc.skins)used.add(s.inverseBindMatrices);for(const a of doc.animations)for(const s of a.samplers){used.add(s.input);used.add(s.output);}
const acc=remap(doc.accessors,used);doc.accessors=acc.result;for(const m of doc.meshes)for(const p of m.primitives){for(const k in p.attributes)p.attributes[k]=acc.map.get(p.attributes[k]);p.indices=acc.map.get(p.indices);}for(const s of doc.skins)s.inverseBindMatrices=acc.map.get(s.inverseBindMatrices);for(const a of doc.animations)for(const s of a.samplers){s.input=acc.map.get(s.input);s.output=acc.map.get(s.output);}
const all=Buffer.concat(chunks),views=remap(doc.bufferViews,new Set([...doc.accessors.map(a=>a.bufferView),...doc.images.map(i=>i.bufferView)]));const compact=[];let offset=0;for(const v of views.result){const pad=(4-offset%4)%4;if(pad){compact.push(Buffer.alloc(pad));offset+=pad;}compact.push(all.subarray(v.byteOffset??0,(v.byteOffset??0)+v.byteLength));v.byteOffset=offset;v.buffer=0;offset+=v.byteLength;}doc.bufferViews=views.result;for(const a of doc.accessors)a.bufferView=views.map.get(a.bufferView);for(const i of doc.images)i.bufferView=views.map.get(i.bufferView);
let buffer=Buffer.concat(compact);if(buffer.length%4)buffer=Buffer.concat([buffer,Buffer.alloc(4-buffer.length%4)]);doc.buffers=[{byteLength:buffer.length}];
const json=Buffer.from(JSON.stringify(doc)),padding=Buffer.alloc(Math.ceil(json.length/4)*4,32);json.copy(padding);const header=Buffer.alloc(20),bh=Buffer.alloc(8);header.writeUInt32LE(0x46546c67,0);header.writeUInt32LE(2,4);header.writeUInt32LE(28+padding.length+buffer.length,8);header.writeUInt32LE(padding.length,12);header.writeUInt32LE(0x4e4f534a,16);bh.writeUInt32LE(buffer.length,0);bh.writeUInt32LE(0x004e4942,4);
const output='Web/public/assets/hollow-scavenger';fs.mkdirSync(output,{recursive:true});const bytes=Buffer.concat([header,padding,bh,buffer]);fs.writeFileSync(output+'/hollow-scavenger.glb',bytes);fs.copyFileSync('Web/public/assets/donor/knife.glb',output+'/knife.glb');
const donorManifest=JSON.parse(fs.readFileSync('Web/public/assets/donor/manifest.json')),description=structuredClone(donorManifest.models.vagrant);description.url='hollow-scavenger.glb';description.rig='hollow-scavenger';description.contactRig='hero';description.bodyScale=1;description.bones=doc.skins[skinNode.skin].joints.map(id=>doc.nodes[id].name);description.clipDurations=Object.fromEntries(doc.animations.map(a=>[a.name,Math.max(...a.samplers.map(s=>doc.accessors[s.input].max?.[0]??0))]));description.units='metres';description.forward='+Z';description.unavailableClips=[];description.clips.idle='HollowIdle';description.clips.walk='HollowWalk';description.sha256=sha(bytes);description.bytes=bytes.length;description.name='Hollow Scavenger';description.modularMeshNames=doc.nodes.filter(n=>n.mesh!==undefined).map(n=>n.name);description.provenance={source,sourceSha256:sha(original),revision:donorManifest.revision,edits:'Separate material/coverage derivative, retained native combat clips and knife; only new idle/walk/run spine/neck samples.'};
fs.writeFileSync(output+'/manifest.json',JSON.stringify({version:1,status:'CPU-validated art pilot; isolated London motion captured; group and phone review pending',units:'metres',forward:'+Z',actorVisualScale:1.3225,characterScale:1.265,cameraZoom:1.3365,models:{'hollow-scavenger':description}},null,2)+'\n');console.log('Candidate',bytes.length,sha(bytes));
