import {createCombatImpact} from './combat-impact.js';
import {createDonorAudio} from './donor-audio.js';
import * as THREE from 'three';
import {pistolCue} from './pistol-targeting.js';
const colors={slash:0xe3e9ec,stab:0xe3e9ec,heavy:0xffa64c,special:0xe8bc65};
export function createEffects(scene,world,pistolAsset=null,getMuzzle=()=>null,{reducedMotion=()=>globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false}={}){let lastShot=-Infinity,lastPistolHit=-Infinity;const projection=new THREE.Matrix4(),inverse=new THREE.Matrix4(),shift=new THREE.Matrix4();const active=game=>!!game.pistol?.equipped&&game.player.hp>0&&!game.finished;const shots=[],transient=[],bolts=new Map(),loot=new Map(),sphere=new THREE.SphereGeometry(.15,8,6),gem=new THREE.OctahedronGeometry(.21),boltMaterial=new THREE.MeshBasicMaterial({color:0xee5526}),lootMaterials=[0xdca64d,0x48b9c5,0x70c66e].map(color=>new THREE.MeshBasicMaterial({color}));
 let requestedMode='high',motionReduced=!!reducedMotion();
 const impact=createCombatImpact({mode:requestedMode,reducedMotion:motionReduced});let feedback=impact.update(0),particleIndex=0,tracerIndex=0,flashLife=0,lastEquipped=false,basicRecoil=0,viewportWidth=globalThis.innerWidth??852,viewportHeight=globalThis.innerHeight??393;
 const pool=new THREE.Group();pool.name='Combat feedback pool';scene.add(pool);
 const unit=new THREE.BoxGeometry(1,1,1),particleMaterial=new THREE.MeshBasicMaterial({color:0xffffff}),particleMesh=new THREE.InstancedMesh(unit,particleMaterial,48),pose=new THREE.Object3D(),particleColour=new THREE.Color();particleMesh.name='Combat pooled particles';particleMesh.frustumCulled=false;particleMesh.visible=false;pool.add(particleMesh);
 const particles=Array.from({length:48},()=>({life:0,total:1,x:0,y:0,z:0,vx:0,vy:0,vz:0,size:0}));
 const tracers=Array.from({length:16},()=>{const geometry=new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(new Float32Array(6),3)),material=new THREE.LineBasicMaterial({color:0xf5d498,transparent:true,opacity:.8,depthWrite:false}),mesh=new THREE.Line(geometry,material);mesh.name='Combat pooled tracer';mesh.visible=false;mesh.frustumCulled=false;pool.add(mesh);return{mesh,life:0};});
 const muzzleFlash=new THREE.Mesh(unit,new THREE.MeshBasicMaterial({color:0xffedb0,depthWrite:false}));muzzleFlash.name='Combat muzzle flash';muzzleFlash.visible=false;pool.add(muzzleFlash);
 function tickPool(dt){for(let i=0;i<48;i++){const p=particles[i];p.life=Math.max(0,p.life-dt);if(p.life){p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vy-=8*dt;pose.position.set(p.x,p.y,p.z);pose.scale.setScalar(p.size*p.life/p.total);particleColour.setHex(0xffca85).multiplyScalar(.6+.4*p.life/p.total);particleMesh.setColorAt(i,particleColour);}else pose.scale.setScalar(0);pose.updateMatrix();particleMesh.setMatrixAt(i,pose.matrix);}particleMesh.visible=particles.some(p=>p.life>0);particleMesh.instanceMatrix.needsUpdate=true;if(particleMesh.instanceColor)particleMesh.instanceColor.needsUpdate=true;for(const t of tracers){t.life=Math.max(0,t.life-dt);t.mesh.visible=t.life>0;t.mesh.material.opacity=.8*Math.min(1,t.life/.065);}flashLife=Math.max(0,flashLife-dt);muzzleFlash.visible=flashLife>0;}
 function clearFeedback(){impact.reset();feedback=impact.update(0);for(const p of particles)p.life=0;for(const t of tracers)t.life=0;flashLife=basicRecoil=0;tickPool(0);}
 function direction(event){const d=event.direction??event.impactDirection??event.dir??{x:0,z:1};if(!world.camera)return{x:d.x,y:-d.z};const a=world.toRender(event.position??event.origin??event.actor.pos,1),b=a.clone().add(new THREE.Vector3(d.x,0,-d.z));a.project(world.camera);b.project(world.camera);return{x:(b.x-a.x)*viewportWidth/2,y:(a.y-b.y)*viewportHeight/2};}
 function burst(event,killed){const p=event.position??event.actor.pos,d=event.impactDirection??{x:0,z:1},count=feedback.mode==='off'?1:feedback.mode==='low'?3:killed?12:8,size=event.actor.mobSize??1;for(let i=0;i<count;i++){const v=particles[particleIndex++%48],a=i/count*Math.PI*2;Object.assign(v,{life:feedback.mode==='off'?.12:killed?.42:.30,total:feedback.mode==='off'?.12:killed?.42:.30,x:p.x,y:1.1*size,z:-p.z,vx:Math.cos(a)*1.8+d.x,vy:1.3+i%3*.7,vz:Math.sin(a)*1.8-d.z,size:(feedback.mode==='off'?.14:feedback.mode==='low'?.055:killed?.16:.12)*size});}}
 const pickup=new THREE.Group(),reticle=new THREE.Group();pickup.name='Starting pistol pickup';reticle.name='Pistol aim marker';
 const glowGeometry=new THREE.RingGeometry(.32,.43,32),glowMaterial=new THREE.MeshBasicMaterial({color:0xd9a750,transparent:true,opacity:.45,depthWrite:false,side:THREE.DoubleSide});
 const glow=new THREE.Mesh(glowGeometry,glowMaterial);glow.rotation.x=-Math.PI/2;glow.position.y=.035;pickup.add(glow);
 if(pistolAsset){const gun=pistolAsset.scene.clone(true);gun.rotation.set(Math.PI/2,0,.45);gun.position.y=.15;gun.scale.setScalar(1.8);pickup.add(gun);}
 const bracketGeometry=padding=>{const vertices=[];const rect=(x,y,w,h)=>{const l=x-w/2,r=x+w/2,b=y-h/2,t=y+h/2;vertices.push(l,b,0,r,b,0,r,t,0,l,b,0,r,t,0,l,t,0);};for(const x of [-1,1])for(const y of [-1,1]){rect(x*.39,y*.5,.22+padding,.045+padding);rect(x*.5,y*.39,.045+padding,.22+padding);}return new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));};
 const outlineGeometry=bracketGeometry(.06),cueGeometry=bracketGeometry(0),outlineMaterial=new THREE.MeshBasicMaterial({color:0x161b1d,transparent:true,depthWrite:false,depthTest:false,toneMapped:false}),cueMaterial=new THREE.MeshBasicMaterial({color:0xf2eee4,transparent:true,depthWrite:false,depthTest:false,toneMapped:false});
 const outline=new THREE.Mesh(outlineGeometry,outlineMaterial),brackets=new THREE.Mesh(cueGeometry,cueMaterial),accentGeometry=new THREE.PlaneGeometry(.16,.055),accentMaterial=new THREE.MeshBasicMaterial({color:0xdca64d,depthWrite:false,depthTest:false,toneMapped:false}),accent=new THREE.Mesh(accentGeometry,accentMaterial);
 outline.renderOrder=101;brackets.renderOrder=102;accent.renderOrder=103;accent.position.y=-.57;reticle.add(outline,brackets,accent);pickup.visible=reticle.visible=false;scene.add(pickup,reticle);

 function line(center,dir,radius,arc,color,expires,height=.08,stroke=false){const ring=arc>=359,points=[],steps=36,angle=Math.atan2(dir.x,-dir.z);if(!ring&&!stroke)points.push(new THREE.Vector3(0,height,0));for(let i=0;i<=steps;i++){const a=angle-arc*Math.PI/360+arc*Math.PI/180*i/steps;points.push(new THREE.Vector3(Math.sin(a)*radius,height,Math.cos(a)*radius));}if(!ring&&!stroke)points.push(new THREE.Vector3(0,height,0));const mesh=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color,transparent:true,opacity:.9,depthWrite:false}));mesh.position.copy(world.toRender(center));scene.add(mesh);transient.push({mesh,expires});return mesh;}
 function erase(effect){scene.remove(effect.mesh);effect.mesh.geometry.dispose();effect.mesh.material.dispose();}
 return {configureFeedback(mode){requestedMode=['high','low','off'].includes(mode)?mode:'low';impact.configure({mode:requestedMode,reducedMotion:!!reducedMotion()});clearFeedback();},advance(dt,{paused=false}={}){const reduced=!!reducedMotion();if(reduced!==motionReduced){motionReduced=reduced;impact.configure({mode:requestedMode,reducedMotion:reduced});clearFeedback();}feedback=impact.update(dt,{paused});if(!paused){const elapsed=Math.max(0,Number.isFinite(dt)?dt:0);basicRecoil*=Math.exp(-elapsed*12);if(basicRecoil<.001)basicRecoil=0;tickPool(elapsed);}},snapshot(){return{...feedback,requestedMode,particleCapacity:48,tracerCapacity:16,activeParticles:particles.filter(p=>p.life>0).length,activeTracers:tracers.filter(t=>t.life>0).length,muzzleFlash:muzzleFlash.visible};},clearPistolFeedback(){clearFeedback();lastShot=lastPistolHit=-Infinity;reticle.visible=false;reticle.userData.targetId=null;reticle.userData.ready=false;},pistolRecoil(game){return active(game)?feedback.mode==='off'?basicRecoil*.2:feedback.shot:0;},render(renderer,camera,game,height,width=height*(camera.aspect??1)){const visible=game.player.hp>0&&!game.finished&&!reducedMotion(),x=visible?feedback.cameraX:0,y=visible?feedback.cameraY:0;if(!(height>0)||!x&&!y)return renderer.render(scene,camera);projection.copy(camera.projectionMatrix);inverse.copy(camera.projectionMatrixInverse);camera.projectionMatrix.premultiply(shift.makeTranslation(2*x/Math.max(1,width),-2*y/height,0));camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert();try{return renderer.render(scene,camera);}finally{camera.projectionMatrix.copy(projection);camera.projectionMatrixInverse.copy(inverse);}},events(game){const dead=new Set(game.events.filter(e=>e.type==='death').map(e=>e.actor?.id));for(const event of game.events){const actor=event.actor,donor=game.pilot==='donor-knife';
 if(event.type==='shot'){shots.push(event);lastEquipped=true;basicRecoil=1;lastShot=game.time;impact.event({type:'shot',...direction(event),pistol:true});feedback=impact.update(0);}if(event.type==='holster')this.clearPistolFeedback();
 if(event.type==='enemy-attack' &&actor.swing)line(actor.pos,event.dir,event.range,event.arc,actor.kind===3?0xf9a83b:0xe45735,actor.swing.hitAt);
 if(event.type==='hit'&&donor&&!event.blocked&&event.amount>0){const killed=dead.has(actor.id);impact.event({type:killed?'death':'hit',...direction(event),pistol:event.weapon==='pistol'});feedback=impact.update(0);burst(event,killed);}
 if(event.type==='strike'){const size=actor.kind>=0?(actor.mobSize??1):1;if(donor&&event.action==='special')line(actor.pos,event.dir,1.3*(actor.combatScale??1.265),90,colors.special,game.time+.12,1.1*size,true);else if(event.action==='stab'){const a=world.toRender(actor.pos,1.1*size),b=a.clone().add(new THREE.Vector3(event.dir.x*1.8*size,0,-event.dir.z*1.8*size));const mesh=new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,b]),new THREE.LineBasicMaterial({color:colors.stab,transparent:true,opacity:.85}));scene.add(mesh);transient.push({mesh,expires:game.time+.12});}else line(actor.pos,event.dir,event.action==='special'?4.2:event.action==='heavy'?1.8*size:1.5*size,event.action==='special'?360:120,colors[event.action],game.time+.12,1.1*size,true);}
 if(['parry','block','guard-break'].includes(event.type))line(donor?(event.position??actor.pos):actor.pos,actor.facing,1.05,donor&&event.type!=='guard-break'?120:360,event.type==='parry'?0x76d4df:event.type==='block'?0xc4a665:0xe95737,game.time+.18);
 }tickPool(0);},update(game,{paused=false,visibleIds,viewportHeight:height=393,viewportWidth:width=852}={}){viewportHeight=height;viewportWidth=width;for(let i=transient.length-1;i>=0;i--)if(game.time>=transient[i].expires||game.finished){erase(transient[i]);transient.splice(i,1);}
 for(const shot of shots){const muzzle=getMuzzle(),a=muzzle?muzzle.getWorldPosition(new THREE.Vector3()):world.toRender(shot.origin,1.05),b=world.toRender(shot.end,a.y),t=tracers[tracerIndex++%16],p=t.mesh.geometry.attributes.position;p.setXYZ(0,a.x,a.y,a.z);p.setXYZ(1,b.x,b.y,b.z);p.needsUpdate=true;t.life=.065;muzzleFlash.position.copy(a);muzzleFlash.scale.setScalar(feedback.mode==='high'?.15:.09);flashLife=feedback.mode==='high'?.06:.045;}tickPool(0);shots.length=0;
 const pistol=game.pistol;if(lastEquipped&&!pistol?.equipped||game.finished||game.player.hp<=0)this.clearPistolFeedback();lastEquipped=!!pistol?.equipped;
 pickup.visible=!!pistol&&!pistol.collected&&world.areaId===pistol.pickupAreaId&&!game.finished;
 if(pickup.visible){pickup.position.copy(world.toRender(pistol.pickupPos));glowMaterial.opacity=.35+.12*Math.sin(game.time*2.4);}
 const cue=pistolCue(game,{paused,visibleIds});reticle.visible=!!cue;
 if(cue){const target=cue.targetId!=null,camera=world.camera;reticle.userData.targetId=cue.targetId;reticle.userData.ready=cue.ready;
  reticle.position.copy(world.toRender(cue.position,cue.height));
  if(camera){reticle.quaternion.copy(camera.quaternion);const depth=reticle.position.distanceTo(camera.position),pixels=target?24:10;reticle.scale.setScalar(2*pixels*depth/(Math.max(1,viewportHeight)*camera.projectionMatrix.elements[5]));}else reticle.scale.setScalar(target?.6:.2);
  cueMaterial.opacity=cue.ready?(target?.95:.55):.25;outlineMaterial.opacity=cue.ready?.85:.4;accent.visible=target&&cue.ready;
 }else{reticle.userData.targetId=null;reticle.userData.ready=false;}

 const sync=(items,map,geometry,material,height)=>{const ids=new Set(items.map(x=>x.id));for(const [id,mesh]of map)if(!ids.has(id)){scene.remove(mesh);map.delete(id);}for(const item of items){let mesh=map.get(item.id);if(!mesh){mesh=new THREE.Mesh(geometry,typeof material==='function'?material(item):material);map.set(item.id,mesh);scene.add(mesh);}mesh.position.copy(world.toRender(item.pos,height));if(geometry===gem)mesh.rotation.y=game.time*1.5;}};
 sync(game.bolts,bolts,sphere,boltMaterial,.8);sync(game.loot,loot,gem,l=>lootMaterials[l.kind],.3);
 },reset(){this.clearPistolFeedback();shots.length=0;pickup.visible=reticle.visible=false;for(const e of transient)erase(e);transient.length=0;for(const map of [bolts,loot]){for(const mesh of map.values())scene.remove(mesh);map.clear();}},dispose(){this.reset();scene.remove(pickup,reticle);glowGeometry.dispose();glowMaterial.dispose();outlineGeometry.dispose();cueGeometry.dispose();accentGeometry.dispose();outlineMaterial.dispose();cueMaterial.dispose();accentMaterial.dispose();particleMesh.dispose();unit.dispose();particleMaterial.dispose();muzzleFlash.material.dispose();for(const t of tracers){t.mesh.geometry.dispose();t.mesh.material.dispose();}scene.remove(pool);sphere.dispose();gem.dispose();boltMaterial.dispose();for(const m of lootMaterials)m.dispose();}};
}
// Small local cues: start audio only on the player's Enter/Resume gesture.
export function createAudio(options={}){if(options.donor)return createDonorAudio(options);let context=null,enabled=true;return {async unlock(){context??=new(window.AudioContext||window.webkitAudioContext)();await context.resume();},setEnabled(value){enabled=value;},pause(){if(context?.state==='running')context.suspend();},play(events){if(!enabled||context?.state!=='running')return;for(const e of events){const frequencies={attack:180,hit:95,parry:660,block:260,dodge:120,loot:880,death:55,wave:330};const frequency=frequencies[e.type];if(!frequency)continue;const oscillator=context.createOscillator(),gain=context.createGain(),start=context.currentTime,duration=e.type==='death'?.25:.08;oscillator.type=e.type==='loot'||e.type==='parry'?'sine':'triangle';oscillator.frequency.setValueAtTime(frequency,start);oscillator.frequency.exponentialRampToValueAtTime(Math.max(30,frequency*.55),start+duration);gain.gain.setValueAtTime(.035,start);gain.gain.exponentialRampToValueAtTime(.001,start+duration);oscillator.connect(gain);gain.connect(context.destination);oscillator.start(start);oscillator.stop(start+duration);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};}}};}
