import * as THREE from 'three';
const colors={slash:0xe3e9ec,stab:0xe3e9ec,heavy:0xffa64c,special:0xe8bc65};
export function createEffects(scene,world){const transient=[],bolts=new Map(),loot=new Map(),sphere=new THREE.SphereGeometry(.15,8,6),gem=new THREE.OctahedronGeometry(.21),boltMaterial=new THREE.MeshBasicMaterial({color:0xee5526}),lootMaterials=[0xdca64d,0x48b9c5,0x70c66e].map(color=>new THREE.MeshBasicMaterial({color}));
 function line(center,dir,radius,arc,color,expires,height=.08,stroke=false){const ring=arc>=359,points=[],steps=36,angle=Math.atan2(dir.x,-dir.z);if(!ring&&!stroke)points.push(new THREE.Vector3(0,height,0));for(let i=0;i<=steps;i++){const a=angle-arc*Math.PI/360+arc*Math.PI/180*i/steps;points.push(new THREE.Vector3(Math.sin(a)*radius,height,Math.cos(a)*radius));}if(!ring&&!stroke)points.push(new THREE.Vector3(0,height,0));const mesh=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color,transparent:true,opacity:.9,depthWrite:false}));mesh.position.copy(world.toRender(center));scene.add(mesh);transient.push({mesh,expires});}
 function erase(effect){scene.remove(effect.mesh);effect.mesh.geometry.dispose();effect.mesh.material.dispose();}
 return {events(game){for(const event of game.events){const actor=event.actor;
 if(event.type==='enemy-attack')line(actor.pos,event.dir,event.range,event.arc,actor.kind===3?0xf9a83b:0xe45735,actor.swing.hitAt);
 if(event.type==='strike'){if(event.action==='stab'){const a=world.toRender(actor.pos,1.1),b=a.clone().add(new THREE.Vector3(event.dir.x*1.8,0,-event.dir.z*1.8));const mesh=new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,b]),new THREE.LineBasicMaterial({color:colors.stab,transparent:true,opacity:.85}));scene.add(mesh);transient.push({mesh,expires:game.time+.12});}else line(actor.pos,event.dir,event.action==='special'?4.2:event.action==='heavy'?1.8:1.5,event.action==='special'?360:120,colors[event.action],game.time+.12,1.1,true);}
 if(['parry','block','guard-break'].includes(event.type))line(actor.pos,actor.facing,1.05,360,event.type==='parry'?0x76d4df:event.type==='block'?0xc4a665:0xe95737,game.time+.18);
 }},update(game){for(let i=transient.length-1;i>=0;i--)if(game.time>=transient[i].expires||game.finished){erase(transient[i]);transient.splice(i,1);}
 const sync=(items,map,geometry,material,height)=>{const ids=new Set(items.map(x=>x.id));for(const [id,mesh]of map)if(!ids.has(id)){scene.remove(mesh);map.delete(id);}for(const item of items){let mesh=map.get(item.id);if(!mesh){mesh=new THREE.Mesh(geometry,typeof material==='function'?material(item):material);map.set(item.id,mesh);scene.add(mesh);}mesh.position.copy(world.toRender(item.pos,height));if(geometry===gem)mesh.rotation.y=game.time*1.5;}};
 sync(game.bolts,bolts,sphere,boltMaterial,.8);sync(game.loot,loot,gem,l=>lootMaterials[l.kind],.3);
 },reset(){for(const e of transient)erase(e);transient.length=0;for(const map of [bolts,loot]){for(const mesh of map.values())scene.remove(mesh);map.clear();}},dispose(){this.reset();sphere.dispose();gem.dispose();boltMaterial.dispose();for(const m of lootMaterials)m.dispose();}};
}
// Small local cues: start audio only on the player's Enter/Resume gesture.
export function createAudio(){let context=null,enabled=true;return {async unlock(){context??=new(window.AudioContext||window.webkitAudioContext)();await context.resume();},setEnabled(value){enabled=value;},pause(){if(context?.state==='running')context.suspend();},play(events){if(!enabled||context?.state!=='running')return;for(const e of events){const frequencies={attack:180,hit:95,parry:660,block:260,dodge:120,loot:880,death:55,wave:330};const frequency=frequencies[e.type];if(!frequency)continue;const oscillator=context.createOscillator(),gain=context.createGain(),start=context.currentTime,duration=e.type==='death'?.25:.08;oscillator.type=e.type==='loot'||e.type==='parry'?'sine':'triangle';oscillator.frequency.setValueAtTime(frequency,start);oscillator.frequency.exponentialRampToValueAtTime(Math.max(30,frequency*.55),start+duration);gain.gain.setValueAtTime(.035,start);gain.gain.exponentialRampToValueAtTime(.001,start+duration);oscillator.connect(gain);gain.connect(context.destination);oscillator.start(start);oscillator.stop(start+duration);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};}}};}
